import type { Problem } from "../problem-bank";

/**
 * 数学II・B・Cの追加問題。
 * すべて新規作成。1問につき主概念を1つだけ判定する。
 */
export const expansionIIBC: Problem[] = [
  {
    id: "Q-EXP-II-01",
    conceptIds: ["II-01"],
    primaryConceptId: "II-01",
    title: "多項式の次数と最高次係数",
    prompt: "P(x)=3x⁴−2x²+x−5 の次数と最高次係数の組として正しいものは？",
    options: ["次数4、最高次係数3", "次数3、最高次係数4", "次数4、最高次係数−5", "次数5、最高次係数3"],
    answer: 0,
    explanation: "最も高い次数の項は3x⁴。したがって次数は4、最高次係数は3である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-EXP-II-02",
    conceptIds: ["II-02"],
    primaryConceptId: "II-02",
    title: "多項式の乗法",
    prompt: "(x+2)(x²−x+3)を展開した式は？",
    options: ["x³+x²+x+6", "x³−x²+5x+6", "x³+2x²−x+6", "x³+x²+5x+6"],
    answer: 0,
    explanation: "分配法則で展開すると、x³−x²+3x+2x²−2x+6=x³+x²+x+6となる。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-03",
    conceptIds: ["II-03"],
    primaryConceptId: "II-03",
    title: "二項定理の係数",
    prompt: "(x+1)⁵の展開式におけるx²の係数は？",
    options: ["5", "10", "15", "20"],
    answer: 1,
    explanation: "x²を選ぶ項は、5個の因子から2個である。係数は二項係数5C2=10。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-II-04",
    conceptIds: ["II-04"],
    primaryConceptId: "II-04",
    title: "多項式の割り算",
    prompt: "x³+2x²−x−2をx+2で割ったときの商と余りは？",
    options: ["商x²+1、余り0", "商x²−1、余り0", "商x²−2x+3、余り1", "商x²−1、余り2"],
    answer: 1,
    explanation: "x³+2x²−x−2=x²(x+2)−1(x+2)=(x+2)(x²−1)。商はx²−1、余りは0である。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-II-05",
    conceptIds: ["II-07"],
    primaryConceptId: "II-07",
    title: "高次方程式の因数分解",
    prompt: "方程式x³−4x=0の実数解の組は？",
    options: ["−2,0,2", "−4,0,4", "0,2のみ", "−2,2のみ"],
    answer: 0,
    explanation: "x³−4x=x(x²−4)=x(x−2)(x+2)なので、解は−2,0,2である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-06",
    conceptIds: ["II-08", "II-09"],
    primaryConceptId: "II-09",
    title: "複素数の割り算",
    prompt: "(1+i)/(1−i)の値は？",
    options: ["−1", "i", "−i", "1"],
    answer: 1,
    explanation: "分母の共役1+iを掛けると、(1+i)²/((1−i)(1+i))=2i/2=iとなる。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-II-07",
    conceptIds: ["II-11"],
    primaryConceptId: "II-11",
    title: "複素数解をもつ二次方程式",
    prompt: "方程式x²−2x+5=0の解は？",
    options: ["1±i", "1±2i", "−1±2i", "2±i"],
    answer: 1,
    explanation: "解の公式で、x=(2±√(4−20))/2=(2±4i)/2=1±2iとなる。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-EXP-II-08",
    conceptIds: ["II-14"],
    primaryConceptId: "II-14",
    title: "恒等式の係数比較",
    prompt: "すべてのxで(x+1)(x+a)=x²+5x+4が成り立つとき、aの値は？",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "左辺を展開するとx²+(a+1)x+a。xの係数を比べてa+1=5よりa=4。定数項も一致する。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-09",
    conceptIds: ["II-16"],
    primaryConceptId: "II-16",
    title: "座標の中点",
    prompt: "A(−2,3)とB(4,−1)を結ぶ線分の中点の座標は？",
    options: ["(1,1)", "(2,1)", "(1,2)", "(−1,1)"],
    answer: 0,
    explanation: "中点は座標ごとの平均なので、((−2+4)/2,(3−1)/2)=(1,1)。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-II-10",
    conceptIds: ["II-20"],
    primaryConceptId: "II-20",
    title: "等距離の軌跡",
    prompt: "点P(x,y)が点(2,0)と点(−2,0)から等距離にあるとき、Pの軌跡は？",
    options: ["x=0", "y=0", "x²+y²=4", "x=2"],
    answer: 0,
    explanation: "2点から等距離にある点の軌跡は垂直二等分線。2点を結ぶ線分はx軸上なので、軌跡はx=0である。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-11",
    conceptIds: ["II-21"],
    primaryConceptId: "II-21",
    title: "点と直線の距離",
    prompt: "点(1,2)と直線3x+4y−10=0との距離は？",
    options: ["1/5", "1/2", "1", "5"],
    answer: 0,
    explanation: "距離公式より|3·1+4·2−10|/√(3²+4²)=1/5。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-II-12",
    conceptIds: ["II-23"],
    primaryConceptId: "II-23",
    title: "直線と円の共有点",
    prompt: "円x²+y²=5と直線x=1の共有点は？",
    options: ["(1,2)と(1,−2)", "(2,1)と(−2,1)", "(1,√5)のみ", "共有点はない"],
    answer: 0,
    explanation: "x=1を円の式に代入すると1+y²=5、y²=4。よってy=±2である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-13",
    conceptIds: ["II-24"],
    primaryConceptId: "II-24",
    title: "円の接線条件",
    prompt: "円(x−1)²+(y+2)²=9に接する直線はどれ？",
    options: ["x=4", "x=1", "y=0", "y=−2"],
    answer: 0,
    explanation: "中心(1,−2)からx=4までの距離は3で、半径と等しい。したがってx=4は接線である。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-II-14",
    conceptIds: ["II-25"],
    primaryConceptId: "II-25",
    title: "二円の位置関係",
    prompt: "中心間距離が5、半径がそれぞれ3と2の2円の位置関係は？",
    options: ["外接する", "内接する", "2点で交わる", "離れていて交わらない"],
    answer: 0,
    explanation: "中心間距離5が半径の和3+2に等しいので、2円は外接し共有点を1個もつ。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-15",
    conceptIds: ["II-26"],
    primaryConceptId: "II-26",
    title: "二直線の角の二等分線",
    prompt: "直線x−y=0とx+y−2=0の角の二等分線の組は？",
    options: ["x=1またはy=1", "x=0またはy=0", "x=yのみ", "x+y=2のみ"],
    answer: 0,
    explanation: "角の二等分線は2直線からの距離が等しいので|x−y|=|x+y−2|。整理するとx=1またはy=1。",
    kind: "transfer",
    estimatedSeconds: 95,
  },
  {
    id: "Q-EXP-II-16",
    conceptIds: ["II-29"],
    primaryConceptId: "II-29",
    title: "領域内の最大値",
    prompt: "x≥0、y≥0、x+y≤4の領域でxyがとる最大値は？",
    options: ["2", "4", "8", "16"],
    answer: 1,
    explanation: "x+y=sを固定するとxyはx=yのとき最大。さらにs≤4なのでx=y=2のとき最大値xy=4。",
    kind: "transfer",
    estimatedSeconds: 100,
  },
  {
    id: "Q-EXP-II-17",
    conceptIds: ["II-30"],
    primaryConceptId: "II-30",
    title: "有理数指数",
    prompt: "8^(2/3)の値は？",
    options: ["2", "4", "8", "16"],
    answer: 1,
    explanation: "8^(2/3)=(³√8)²=2²=4。分数指数は、分母を根号、分子を累乗として読める。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-II-18",
    conceptIds: ["II-31"],
    primaryConceptId: "II-31",
    title: "指数関数のグラフ",
    prompt: "y=(1/3)^xについて正しい記述は？",
    options: ["単調増加し、y切片は0", "単調減少し、y切片は1", "単調増加し、y切片は1", "x軸を横切る"],
    answer: 1,
    explanation: "底が0より大きく1より小さい指数関数は単調減少。x=0でy=1、x軸は漸近線で交わらない。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-19",
    conceptIds: ["II-32"],
    primaryConceptId: "II-32",
    title: "置換を使う指数方程式",
    prompt: "4^x−5·2^x+4=0を満たすxの組は？",
    options: ["0,1", "0,2", "1,2", "−1,2"],
    answer: 1,
    explanation: "t=2^xとおくとt²−5t+4=(t−1)(t−4)=0。t>0なので2^x=1,4よりx=0,2。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-EXP-II-20",
    conceptIds: ["II-34"],
    primaryConceptId: "II-34",
    title: "対数の定義",
    prompt: "log₃(1/9)の値は？",
    options: ["−3", "−2", "−1", "2"],
    answer: 1,
    explanation: "1/9=3^(−2)なので、指数と対数の定義からlog₃(1/9)=−2。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-II-21",
    conceptIds: ["II-36"],
    primaryConceptId: "II-36",
    title: "底の変換公式",
    prompt: "log₄8の値は？",
    options: ["1/2", "1", "3/2", "2"],
    answer: 2,
    explanation: "4=2²、8=2³だからlog₄8=3/2。底の変換公式でもlog₂8/log₂4=3/2。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "Q-EXP-II-22",
    conceptIds: ["II-38"],
    primaryConceptId: "II-38",
    title: "対数不等式と真数条件",
    prompt: "log₂(x−1)≤2を満たすxの範囲は？",
    options: ["x≤5", "1<x≤5", "x<5", "−3≤x≤5"],
    answer: 1,
    explanation: "まず真数条件x−1>0よりx>1。底2は1より大きいのでx−1≤4、合わせて1<x≤5。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-EXP-II-23",
    conceptIds: ["II-39"],
    primaryConceptId: "II-39",
    title: "半減期モデル",
    prompt: "ある量が初め80で、3時間ごとに半分になる。6時間後の量は？",
    options: ["10", "20", "30", "40"],
    answer: 1,
    explanation: "6時間では半減が2回起こるので、80×(1/2)²=20。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-24",
    conceptIds: ["II-41"],
    primaryConceptId: "II-41",
    title: "一般角の三角関数",
    prompt: "sin(5π/6)の値は？",
    options: ["−√3/2", "−1/2", "1/2", "√3/2"],
    answer: 2,
    explanation: "5π/6は第2象限で、基準角はπ/6。第2象限のsinは正なのでsin(5π/6)=1/2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-25",
    conceptIds: ["II-42"],
    primaryConceptId: "II-42",
    title: "倍角公式",
    prompt: "θが第1象限にありsinθ=3/5のとき、cos2θは？",
    options: ["−7/25", "7/25", "9/25", "16/25"],
    answer: 1,
    explanation: "cos2θ=1−2sin²θ=1−2(9/25)=7/25。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-26",
    conceptIds: ["II-44"],
    primaryConceptId: "II-44",
    title: "半角公式",
    prompt: "sin²(π/8)の値は？",
    options: ["(2+√2)/4", "(2−√2)/4", "√2/4", "1/4"],
    answer: 1,
    explanation: "半角公式sin²(α/2)=(1−cosα)/2にα=π/4を入れると(1−√2/2)/2=(2−√2)/4。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-EXP-II-27",
    conceptIds: ["II-45"],
    primaryConceptId: "II-45",
    title: "三角式の合成",
    prompt: "sinx+cosxを合成した式は？",
    options: ["sin(x+π/4)", "√2sin(x+π/4)", "2sin(x+π/4)", "√2sin(x−π/4)"],
    answer: 1,
    explanation: "sin(x+π/4)=(sinx+cosx)/√2なので、sinx+cosx=√2sin(x+π/4)。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-II-28",
    conceptIds: ["II-46"],
    primaryConceptId: "II-46",
    title: "三角関数の周期",
    prompt: "y=2sin(3x−π)の周期は？",
    options: ["π/3", "2π/3", "π", "2π"],
    answer: 1,
    explanation: "sin(kx+φ)の周期は2π/|k|。ここではk=3なので周期は2π/3。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-29",
    conceptIds: ["II-48"],
    primaryConceptId: "II-48",
    title: "三角不等式",
    prompt: "0≤x<2πでcosx≥1/2を満たすxの範囲は？",
    options: ["0≤x≤π/3または5π/3≤x<2π", "π/3≤x≤5π/3", "0≤x≤2π/3", "π/6≤x≤5π/6"],
    answer: 0,
    explanation: "単位円でcosxが1/2以上なのは、x軸方向に近い第1・第4象限。範囲端を含めて答える。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-EXP-II-30",
    conceptIds: ["II-49"],
    primaryConceptId: "II-49",
    title: "周期モデルの値",
    prompt: "温度をT(t)=20+5sin(πt/6)で表すとき、t=3での温度T(3)は？",
    options: ["15", "20", "25", "30"],
    answer: 2,
    explanation: "πt/6=π/2なのでsin(π/2)=1。T(3)=20+5=25。",
    kind: "transfer",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-II-31",
    conceptIds: ["II-50"],
    primaryConceptId: "II-50",
    title: "平均変化率",
    prompt: "f(x)=x²+1のx=1からx=3までの平均変化率は？",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "平均変化率は(f(3)−f(1))/(3−1)=(10−2)/2=4。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-II-32",
    conceptIds: ["II-51"],
    primaryConceptId: "II-51",
    title: "接線の傾きへの極限",
    prompt: "f(x)=x²について、x=1とx=1+hの2点を結ぶ直線の傾きのh→0の極限は？",
    options: ["0", "1", "2", "3"],
    answer: 2,
    explanation: "傾きは(((1+h)²−1)/h)=2+h。h→0で2となり、x=1での接線の傾きに一致する。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-EXP-II-33",
    conceptIds: ["II-53"],
    primaryConceptId: "II-53",
    title: "接線の方程式",
    prompt: "f(x)=x²+2xのx=1における接線の方程式は？",
    options: ["y=2x+1", "y=3x−1", "y=4x−1", "y=4x+1"],
    answer: 2,
    explanation: "f(1)=3、f'(x)=2x+2よりf'(1)=4。接線はy−3=4(x−1)、つまりy=4x−1。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-EXP-II-34",
    conceptIds: ["II-55"],
    primaryConceptId: "II-55",
    title: "極値の判定",
    prompt: "f(x)=x³−3x²+4の極小値は？",
    options: ["0", "2", "4", "8"],
    answer: 0,
    explanation: "f'(x)=3x(x−2)。x=2の前後で減少から増加に変わるので極小。f(2)=8−12+4=0。",
    kind: "standard",
    estimatedSeconds: 90,
  },
  {
    id: "Q-EXP-II-35",
    conceptIds: ["II-58"],
    primaryConceptId: "II-58",
    title: "不定積分",
    prompt: "∫(3x²−4x+1)dxとして正しいものは？",
    options: ["3x³−4x²+x+C", "x³−2x²+x+C", "x³−4x²+x+C", "6x−4+C"],
    answer: 1,
    explanation: "各項を積分すると∫3x²dx=x³、∫−4xdx=−2x²、∫1dx=x。最後に積分定数Cを付ける。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-II-36",
    conceptIds: ["II-61"],
    primaryConceptId: "II-61",
    title: "二曲線間の面積",
    prompt: "x=0からx=1までの、y=xとy=x²に挟まれた面積は？",
    options: ["1/6", "1/4", "1/3", "1/2"],
    answer: 0,
    explanation: "0≤x≤1ではxがx²以上なので、面積は∫₀¹(x−x²)dx=1/2−1/3=1/6。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "Q-EXP-II-37",
    conceptIds: ["II-62"],
    primaryConceptId: "II-62",
    title: "速度から位置へ",
    prompt: "速度v(t)=2t+1、初期位置s(0)=3の物体について、s(2)は？",
    options: ["6", "7", "8", "9"],
    answer: 3,
    explanation: "移動距離は∫₀²(2t+1)dt=[t²+t]₀²=6。初期位置3を足してs(2)=9。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "Q-EXP-B-01",
    conceptIds: ["B-03"],
    primaryConceptId: "B-03",
    title: "等差数列の一般項",
    prompt: "初項4、公差−3の等差数列の第7項は？",
    options: ["−14", "−12", "14", "22"],
    answer: 0,
    explanation: "a₇=a₁+6d=4+6(−3)=−14。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-B-02",
    conceptIds: ["B-07"],
    primaryConceptId: "B-07",
    title: "シグマ記号の計算",
    prompt: "Σ(k=1から5まで)(2k+1)の値は？",
    options: ["25", "30", "35", "40"],
    answer: 2,
    explanation: "3+5+7+9+11=35。Σ(2k+1)=2Σk+Σ1=2·15+5でも求められる。",
    kind: "quick",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-B-03",
    conceptIds: ["B-08"],
    primaryConceptId: "B-08",
    title: "一次漸化式の一般項",
    prompt: "a₁=2、aₙ₊₁=aₙ+3で定める数列の一般項は？",
    options: ["aₙ=2n+3", "aₙ=3n−1", "aₙ=3n+1", "aₙ=2·3ⁿ"],
    answer: 1,
    explanation: "公差3の等差数列なのでaₙ=2+3(n−1)=3n−1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-B-04",
    conceptIds: ["B-09"],
    primaryConceptId: "B-09",
    title: "漸化式の置換",
    prompt: "a₁=1、aₙ₊₁=2aₙ+3で定める数列のa₃は？",
    options: ["7", "9", "13", "15"],
    answer: 2,
    explanation: "bₙ=aₙ+3とおくとbₙ₊₁=2bₙ、b₁=4。よってa₃=4·2²−3=13。直接計算でもa₂=5,a₃=13。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-B-05",
    conceptIds: ["B-10"],
    primaryConceptId: "B-10",
    title: "数学的帰納法の一歩",
    prompt: "1+3+5+…+(2n−1)=n²を帰納法で示す。n=kで成り立つと仮定した後、次に現れる式は？",
    options: ["k²+2k=(k+1)²", "k²+2k+1=(k+1)²", "k²+k+1=(k+1)²", "(k+1)²+2k=(k+2)²"],
    answer: 1,
    explanation: "次の奇数2(k+1)−1=2k+1を加えるので、k²+2k+1=(k+1)²となる。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-EXP-B-06",
    conceptIds: ["B-13"],
    primaryConceptId: "B-13",
    title: "漸化式による成長モデル",
    prompt: "初期値が100で、各期に20%増加する量をa₁=100と表す。一般項は？",
    options: ["100+0.2(n−1)", "100·1.2ⁿ", "100·1.2ⁿ⁻¹", "100·0.8ⁿ⁻¹"],
    answer: 2,
    explanation: "各期に1.2倍になる等比数列で、初項がa₁なのでaₙ=100·1.2ⁿ⁻¹。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-B-07",
    conceptIds: ["B-15"],
    primaryConceptId: "B-15",
    title: "確率分布表の不足値",
    prompt: "確率変数Xの値0,1,2に対応する確率がそれぞれ0.2,0.5,pである。pは？",
    options: ["0.1", "0.2", "0.3", "0.4"],
    answer: 2,
    explanation: "確率の合計は1なので、p=1−0.2−0.5=0.3。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-B-08",
    conceptIds: ["B-17"],
    primaryConceptId: "B-17",
    title: "確率変数の分散",
    prompt: "Xが1,3をそれぞれ確率1/2でとるとき、Xの分散は？",
    options: ["1/2", "1", "2", "4"],
    answer: 1,
    explanation: "平均は2。平均との差は−1,1なので、分散は(1+1)/2=1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-B-09",
    conceptIds: ["B-18"],
    primaryConceptId: "B-18",
    title: "確率変数の一次変換",
    prompt: "E(X)=4、V(X)=9のとき、Y=2X−1について正しい組は？",
    options: ["E(Y)=7、V(Y)=18", "E(Y)=8、V(Y)=36", "E(Y)=7、V(Y)=36", "E(Y)=9、V(Y)=36"],
    answer: 2,
    explanation: "期待値は線形なのでE(Y)=2·4−1=7。分散は定数倍の2乗でV(Y)=2²·9=36。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-B-10",
    conceptIds: ["B-20"],
    primaryConceptId: "B-20",
    title: "二項分布の平均と分散",
    prompt: "Xが二項分布Bin(10,0.3)に従うとき、E(X)とV(X)の組は？",
    options: ["(3,2.1)", "(3,3)", "(7,2.1)", "(10,0.3)"],
    answer: 0,
    explanation: "Bin(n,p)ではE(X)=np、V(X)=np(1−p)。したがって3と10·0.3·0.7=2.1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-B-11",
    conceptIds: ["B-21"],
    primaryConceptId: "B-21",
    title: "確率密度と面積",
    prompt: "Xが0≤x≤2で一様分布するとき、P(0.5≤X≤1.5)は？",
    options: ["1/4", "1/2", "3/4", "1"],
    answer: 1,
    explanation: "区間[0,2]で密度は1/2。幅1の区間の確率は面積1×1/2=1/2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-B-12",
    conceptIds: ["B-23"],
    primaryConceptId: "B-23",
    title: "標準化得点",
    prompt: "平均50、標準偏差10の正規分布で、値70の標準化得点zは？",
    options: ["−2", "−1", "1", "2"],
    answer: 3,
    explanation: "z=(70−50)/10=2。平均より標準偏差2個分高い位置にある。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-B-13",
    conceptIds: ["B-26"],
    primaryConceptId: "B-26",
    title: "標本平均の散らばり",
    prompt: "母標準偏差が12、標本サイズが36のとき、標本平均の標準偏差は？",
    options: ["1/2", "2", "6", "12"],
    answer: 1,
    explanation: "標本平均の標準偏差はσ/√n。12/√36=12/6=2。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-B-14",
    conceptIds: ["B-28"],
    primaryConceptId: "B-28",
    title: "信頼区間の解釈",
    prompt: "母平均の95%信頼区間が[48,52]だった。この説明として最も適切なのは？",
    options: ["母平均がこの区間にある確率は95%である", "同じ方法を繰り返すと、作られた区間の約95%が母平均を含む", "標本の95%が48以上52以下である", "母平均は必ず50である"],
    answer: 1,
    explanation: "母平均は固定値で、区間が標本ごとに変わる。方法を繰り返したとき約95%の区間が母平均を含む、という意味である。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "Q-EXP-B-15",
    conceptIds: ["B-30"],
    primaryConceptId: "B-30",
    title: "仮説検定の設定",
    prompt: "コインが公平かを検定する。表が出る確率をpとすると、両側検定の帰無仮説と対立仮説は？",
    options: ["H₀:p=0.5、H₁:p≠0.5", "H₀:p≠0.5、H₁:p=0.5", "H₀:p=0.5、H₁:p>0.5", "H₀:p=0、H₁:p=1"],
    answer: 0,
    explanation: "公平であることを帰無仮説H₀:p=0.5とし、公平でないことを対立仮説H₁:p≠0.5とする。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-B-16",
    conceptIds: ["B-31"],
    primaryConceptId: "B-31",
    title: "p値と棄却判断",
    prompt: "有意水準5%の検定でp値が0.03だった。通常の判断は？",
    options: ["帰無仮説を棄却する", "帰無仮説を採択する", "対立仮説を棄却する", "p値だけでは何も判断できない"],
    answer: 0,
    explanation: "p値0.03は有意水準0.05未満なので、帰無仮説のもとでは起こりにくい結果と判断し、帰無仮説を棄却する。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-B-17",
    conceptIds: ["B-32"],
    primaryConceptId: "B-32",
    title: "第一種の誤り",
    prompt: "仮説検定でいう第一種の誤りはどれ？",
    options: ["真の帰無仮説を棄却する", "偽の帰無仮説を棄却しない", "標本平均を計算し間違える", "有意水準を1にする"],
    answer: 0,
    explanation: "第一種の誤りは、帰無仮説が真なのにそれを棄却してしまう誤り。有意水準はその確率の上限として使われる。",
    kind: "transfer",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-C-01",
    conceptIds: ["C-01"],
    primaryConceptId: "C-01",
    title: "有向線分の成分",
    prompt: "A(1,2)からB(4,6)へ向かうベクトルABの成分は？",
    options: ["(3,4)", "(4,6)", "(5,8)", "(−3,−4)"],
    answer: 0,
    explanation: "終点から始点を引くので、AB=(4−1,6−2)=(3,4)。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-C-02",
    conceptIds: ["C-04"],
    primaryConceptId: "C-04",
    title: "ベクトルのスカラー倍",
    prompt: "a=(2,−1)のとき、−2aは？",
    options: ["(−4,2)", "(4,−2)", "(−2,1)", "(2,−1)"],
    answer: 0,
    explanation: "各成分を−2倍するので−2a=(−4,2)。負のスカラー倍は向きも反転させる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-EXP-C-03",
    conceptIds: ["C-05"],
    primaryConceptId: "C-05",
    title: "ベクトルの成分表示",
    prompt: "A(2,−1)からB(−1,3)へ向かうベクトルABは？",
    options: ["(−3,4)", "(3,−4)", "(1,2)", "(−1,3)"],
    answer: 0,
    explanation: "AB=B−A=(−1−2,3−(−1))=(−3,4)。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-C-04",
    conceptIds: ["C-08"],
    primaryConceptId: "C-08",
    title: "ベクトル方程式の直線",
    prompt: "点p=(1,2)、方向ベクトルa=(2,−1)の直線上で、p+3aに対応する点は？",
    options: ["(3,1)", "(5,−1)", "(7,−1)", "(7,5)"],
    answer: 2,
    explanation: "p+3a=(1,2)+3(2,−1)=(1+6,2−3)=(7,−1)。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "Q-EXP-C-05",
    conceptIds: ["C-09"],
    primaryConceptId: "C-09",
    title: "一次従属なベクトル",
    prompt: "u=(2,4)、v=(1,2)の関係として正しいものは？",
    options: ["u=v", "u=2v", "v=2u", "uとvは直交する"],
    answer: 1,
    explanation: "uの各成分はvの2倍なのでu=2v。2つのベクトルは同じ方向で一次従属である。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-C-06",
    conceptIds: ["C-11"],
    primaryConceptId: "C-11",
    title: "ベクトルで距離を求める",
    prompt: "A(1,−2)、B(4,2)の距離ABは？",
    options: ["3", "4", "5", "7"],
    answer: 2,
    explanation: "AB=(3,4)なので、|AB|=√(3²+4²)=5。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-EXP-C-07",
    conceptIds: ["C-13"],
    primaryConceptId: "C-13",
    title: "正射影",
    prompt: "u=(3,4)をv=(1,0)の方向へ正射影したベクトルは？",
    options: ["(0,4)", "(3,0)", "(3,4)", "(7,0)"],
    answer: 1,
    explanation: "射影は((u・v)/(v・v))v。u・v=3、v・v=1なので3v=(3,0)。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-EXP-C-08",
    conceptIds: ["C-17"],
    primaryConceptId: "C-17",
    title: "空間ベクトルの直交",
    prompt: "空間ベクトルu=(1,1,0)、v=(1,−1,0)の関係は？",
    options: ["同じ向き", "平行だが逆向き", "垂直", "大きさが等しいだけ"],
    answer: 2,
    explanation: "内積u・v=1−1+0=0で、どちらも零ベクトルでない。したがって垂直である。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-C-09",
    conceptIds: ["C-22", "II-10"],
    primaryConceptId: "C-22",
    title: "共役と絶対値",
    prompt: "z=3−4iについて、共役z̄と絶対値|z|の組は？",
    options: ["(3+4i,5)", "(3−4i,5)", "(−3+4i,7)", "(3+4i,25)"],
    answer: 0,
    explanation: "共役は虚部の符号を反転して3+4i。絶対値は√(3²+(-4)²)=5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-EXP-C-10",
    conceptIds: ["C-24"],
    primaryConceptId: "C-24",
    title: "偏角の象限",
    prompt: "z=−1+iの偏角を0≤arg z<2πで表すと？",
    options: ["π/4", "π/2", "3π/4", "5π/4"],
    answer: 2,
    explanation: "点(−1,1)は第2象限にあり、基準角はπ/4。したがって偏角はπ−π/4=3π/4。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-C-11",
    conceptIds: ["C-25"],
    primaryConceptId: "C-25",
    title: "複素数の積と回転",
    prompt: "z=1+iのとき、izは？",
    options: ["1−i", "−1+i", "−1−i", "1+i"],
    answer: 1,
    explanation: "iz=i(1+i)=i+i²=−1+i。複素数iを掛ける操作は反時計回り90°の回転に対応する。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "Q-EXP-C-12",
    conceptIds: ["C-27"],
    primaryConceptId: "C-27",
    title: "ド・モアブルの定理",
    prompt: "(cos(π/3)+isin(π/3))³の値は？",
    options: ["1", "i", "−1", "−i"],
    answer: 2,
    explanation: "ド・モアブルの定理よりcosπ+i sinπ=−1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-EXP-C-13",
    conceptIds: ["C-30"],
    primaryConceptId: "C-30",
    title: "偏角条件の軌跡",
    prompt: "arg z=π/4を満たす点zの軌跡は？",
    options: ["直線y=x全体", "原点を含む直線y=x", "原点を除く第1象限の半直線y=x", "円x²+y²=1"],
    answer: 2,
    explanation: "偏角π/4は第1象限方向。argは原点で定義されないので、原点を除く半直線y=xになる。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "Q-EXP-C-14",
    conceptIds: ["C-32"],
    primaryConceptId: "C-32",
    title: "媒介変数の消去",
    prompt: "x=2t、y=t²で表される曲線を、xとyの方程式で表すと？",
    options: ["y=x²", "y=x²/2", "y=x²/4", "y=2x²"],
    answer: 2,
    explanation: "x=2tよりt=x/2。これをy=t²に代入してy=(x/2)²=x²/4。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-C-15",
    conceptIds: ["C-33"],
    primaryConceptId: "C-33",
    title: "極座標から直交座標へ",
    prompt: "極座標(r,θ)=(2,π/3)に対応する直交座標は？",
    options: ["(1,√3)", "(√3,1)", "(2,√3)", "(1,1)"],
    answer: 0,
    explanation: "x=r cosθ=2·1/2=1、y=r sinθ=2·√3/2=√3。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-EXP-C-16",
    conceptIds: ["C-37"],
    primaryConceptId: "C-37",
    title: "二次曲線の標準形",
    prompt: "4x²+9y²=36が表す図形は？",
    options: ["中心原点、長半軸3の楕円", "中心原点、半径6の円", "焦点をもつ放物線", "双曲線"],
    answer: 0,
    explanation: "36で割るとx²/9+y²/4=1。分母が異なる正の項の和が1なので、中心原点の楕円で長半軸は3。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-EXP-C-17",
    conceptIds: ["C-39"],
    primaryConceptId: "C-39",
    title: "極方程式のグラフ",
    prompt: "極方程式r=2cosθが表す図形は？",
    options: ["中心(1,0)、半径1の円", "中心(0,1)、半径2の円", "原点中心、半径2の円", "直線x=2"],
    answer: 0,
    explanation: "r²=2r cosθよりx²+y²=2x、つまり(x−1)²+y²=1。中心(1,0)、半径1の円である。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
];
