import type { Problem } from "../problem-bank";

/**
 * 数学I全範囲・数学A（場合の数と確率／図形の性質）の追加問題。
 *
 * 既存の problemBank とは分離した教材パック。
 * quick → standard → transfer の順に、短時間の成功体験から
 * 共通テスト型の読み替えへ移れるようにしている。
 */
export const expansionIA: Problem[] = [
  // ── 数学I：数と式 ─────────────────────────────────────────────
  {
    id: "X-IA-I12-01",
    conceptIds: ["I-12"],
    primaryConceptId: "I-12",
    title: "分母を有理化する",
    prompt: "1/(√3+1) を分母に根号がない形にすると？",
    options: ["(√3−1)/2", "(√3+1)/2", "√3−1", "1/2"],
    answer: 0,
    explanation: "分子・分母に√3−1を掛けると、分母は3−1=2。したがって(√3−1)/2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-I15-01",
    conceptIds: ["I-15"],
    primaryConceptId: "I-15",
    title: "平方完成で解く",
    prompt: "x²−4x+1=0 の解は？",
    options: ["x=2±√3", "x=−2±√3", "x=4±√3", "x=2±√5"],
    answer: 0,
    explanation: "(x−2)²=3と平方完成できるので、x−2=±√3。よってx=2±√3。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I19-01",
    conceptIds: ["I-19"],
    primaryConceptId: "I-19",
    title: "絶対値の不等式をほどく",
    prompt: "|2x−1|<3 を満たすxの範囲は？",
    options: ["−1<x<2", "−2<x<1", "x<−1またはx>2", "−1≤x≤2"],
    answer: 0,
    explanation: "−3<2x−1<3を解くと、−2<2x<4、つまり−1<x<2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I21-01",
    conceptIds: ["I-21"],
    primaryConceptId: "I-21",
    title: "文字係数で向きが変わる",
    prompt: "不等式 (a−1)x<a−1 について、a<1のときの解は？",
    options: ["x>1", "x<1", "x=1", "すべての実数"],
    answer: 0,
    explanation: "a<1ならa−1<0。負の数で割ると不等号が逆向きになり、x>1。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "X-IA-I22-01",
    conceptIds: ["I-22"],
    primaryConceptId: "I-22",
    title: "関数に入力する",
    prompt: "f(x)=x²−3x+1 のとき、f(2)は？",
    options: ["−1", "1", "3", "5"],
    answer: 0,
    explanation: "x=2を代入すると4−6+1=−1。関数の値は入力を式に代入して求める。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I24-01",
    conceptIds: ["I-24"],
    primaryConceptId: "I-24",
    title: "2点から直線を決める",
    prompt: "点(−1,2),(2,8)を通る直線の方程式は？",
    options: ["y=2x+4", "y=3x+5", "y=2x+2", "y=x+3"],
    answer: 0,
    explanation: "傾きは(8−2)/(2−(−1))=2。点(−1,2)を代入すると切片は4。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I25-01",
    conceptIds: ["I-25"],
    primaryConceptId: "I-25",
    title: "標準形から頂点を読む",
    prompt: "y=3(x−2)²−5 の頂点は？",
    options: ["(2,−5)", "(−2,−5)", "(2,5)", "(−2,5)"],
    answer: 0,
    explanation: "y=a(x−p)²+qの頂点は(p,q)。この式では(2,−5)。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I28-01",
    conceptIds: ["I-28"],
    primaryConceptId: "I-28",
    title: "全実数での最大値",
    prompt: "f(x)=−3x²+6x+2 の最大値は？",
    options: ["2", "3", "5", "8"],
    answer: 2,
    explanation: "f(x)=−3(x−1)²+5。下に開く放物線なので、頂点の値5が最大値。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I29-01",
    conceptIds: ["I-29"],
    primaryConceptId: "I-29",
    title: "区間で最大・最小を探す",
    prompt: "f(x)=x²−4xを0≤x≤5で考える。最小値と最大値の組は？",
    options: ["(−4,5)", "(0,5)", "(−4,0)", "(0,4)"],
    answer: 0,
    explanation: "f(x)=(x−2)²−4より最小値はx=2で−4。端点の値は0と5なので最大値は5。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X-IA-I30-01",
    conceptIds: ["I-30"],
    primaryConceptId: "I-30",
    title: "直線と放物線の共有点",
    prompt: "放物線y=x²と直線y=2x+3の共有点はどれ？",
    options: ["(−1,1),(3,9)", "(−1,−1),(3,9)", "(1,1),(3,9)", "(−3,9),(1,1)"],
    answer: 0,
    explanation: "x²=2x+3より(x−3)(x+1)=0。x=−1,3をそれぞれ代入する。",
    kind: "transfer",
    estimatedSeconds: 95,
  },
  {
    id: "X-IA-I31-01",
    conceptIds: ["I-31"],
    primaryConceptId: "I-31",
    title: "判別式をグラフに読む",
    prompt: "y=x²+2x+5 とx軸の共有点の個数は？",
    options: ["0個", "1個", "2個", "4個"],
    answer: 0,
    explanation: "x²+2x+5=0の判別式は2²−4・1・5=−16<0。実数解がなく、交点は0個。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I36-01",
    conceptIds: ["I-36"],
    primaryConceptId: "I-36",
    title: "鈍角の三角比",
    prompt: "cos120°の値は？",
    options: ["−1", "−1/2", "1/2", "√3/2"],
    answer: 1,
    explanation: "120°は第2象限なのでcosは負。基準角60°よりcos120°=−cos60°=−1/2。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-I39-01",
    conceptIds: ["I-39"],
    primaryConceptId: "I-39",
    title: "sinで三角形の面積",
    prompt: "2辺の長さが5,8で、その間の角が60°の三角形の面積は？",
    options: ["10", "10√3", "20√3", "40"],
    answer: 1,
    explanation: "面積は1/2・5・8・sin60°=20・√3/2=10√3。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I40-01",
    conceptIds: ["I-40"],
    primaryConceptId: "I-40",
    title: "定理を選び分ける",
    prompt: "三角形の3辺の長さが分かっているとき、角の大きさを求めるのにまず使う定理は？",
    options: ["正弦定理", "余弦定理", "中点連結定理", "円周角の定理"],
    answer: 1,
    explanation: "3辺から角を求める関係は余弦定理。正弦定理は辺と対角の組を使う。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I42-01",
    conceptIds: ["I-42"],
    primaryConceptId: "I-42",
    title: "単位をそろえて面積を出す",
    prompt: "縦1.2m、横80cmの長方形の面積は？",
    options: ["0.096m²", "0.96m²", "9.6m²", "96m²"],
    answer: 1,
    explanation: "80cm=0.8mにそろえる。面積は1.2×0.8=0.96m²。",
    kind: "transfer",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-I43-01",
    conceptIds: ["I-43"],
    primaryConceptId: "I-43",
    title: "度数の合計を読む",
    prompt: "値1,2,3の度数がそれぞれ2,5,3の度数分布表で、データの個数は？",
    options: ["3", "5", "8", "10"],
    answer: 3,
    explanation: "データの個数は度数の合計。2+5+3=10。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I44-01",
    conceptIds: ["I-44"],
    primaryConceptId: "I-44",
    title: "累積度数を作る",
    prompt: "階級[0,10),[10,20),[20,30)の度数が4,7,5のとき、20未満の累積度数は？",
    options: ["4", "7", "11", "16"],
    answer: 2,
    explanation: "20未満には最初の2階級が入るので、4+7=11。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-I47-01",
    conceptIds: ["I-47"],
    primaryConceptId: "I-47",
    title: "偏差平方を合計する",
    prompt: "データ1,3,5,7の平均は4。このデータの偏差平方の和は？",
    options: ["8", "10", "20", "40"],
    answer: 2,
    explanation: "偏差は−3,−1,1,3。それぞれを2乗して9+1+1+9=20。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-I49-01",
    conceptIds: ["I-49"],
    primaryConceptId: "I-49",
    title: "z得点に標準化する",
    prompt: "平均60、標準偏差8のテストで、得点76のz得点は？",
    options: ["1", "2", "8", "16"],
    answer: 1,
    explanation: "z=(得点−平均)/標準偏差=(76−60)/8=2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-I50-01",
    conceptIds: ["I-50"],
    primaryConceptId: "I-50",
    title: "共分散を計算する",
    prompt: "x=(1,2,3), y=(3,5,7)の共分散を、データ数で割って求めると？",
    options: ["2/3", "4/3", "2", "4"],
    answer: 1,
    explanation: "平均はxが2,yが5。偏差積の和は2+0+2=4なので、共分散は4/3。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "X-IA-I52-01",
    conceptIds: ["I-52"],
    primaryConceptId: "I-52",
    title: "相関と因果を分ける",
    prompt: "2つのデータに強い正の相関が見られた。必ず言えることはどれ？",
    options: ["一方が他方の原因である", "偶然であることはない", "2つが連動する傾向がある", "将来も必ず同じ割合で増える"],
    answer: 2,
    explanation: "相関は連動する傾向を表すが、因果関係や将来の保証までは示さない。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
  // ── 数学I：集合・式・不等式 ───────────────────────────────────
  {
    id: "X-IA-I03-01",
    conceptIds: ["I-03"],
    primaryConceptId: "I-03",
    title: "和集合の要素数",
    prompt: "n(A)=12,n(B)=9,n(A∩B)=4のとき、n(A∪B)は？",
    options: ["13", "17", "21", "25"],
    answer: 1,
    explanation: "重なりを1回分引いて、n(A∪B)=12+9−4=17。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-I04-01",
    conceptIds: ["I-04"],
    primaryConceptId: "I-04",
    title: "命題の形を正しく読む",
    prompt: "実数xについて「x²=4ならばx=2またはx=−2である」は？",
    options: ["常に真", "常に偽", "xの値で変わる", "命題ではない"],
    answer: 0,
    explanation: "x²=4を満たす実数は2と−2だけ。仮定から結論が必ず成り立つので真。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-I06-01",
    conceptIds: ["I-06"],
    primaryConceptId: "I-06",
    title: "対偶を作る",
    prompt: "命題「nが4の倍数ならばnは偶数である」の対偶は？",
    options: [
      "nが偶数ならばnは4の倍数である",
      "nが4の倍数でないならばnは偶数でない",
      "nが偶数でないならばnは4の倍数でない",
      "nが4の倍数ならばnは奇数である",
    ],
    answer: 2,
    explanation: "pならばqの対偶は、qでないならばpでない。元の命題では「偶数でないなら4の倍数でない」。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I08-01",
    conceptIds: ["I-08"],
    primaryConceptId: "I-08",
    title: "差の平方を利用する",
    prompt: "(x+3)²−(x−3)²を簡単にすると？",
    options: ["6x", "9x", "12x", "x²−9"],
    answer: 2,
    explanation: "展開すると(x²+6x+9)−(x²−6x+9)=12x。x²と定数が消える。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-I10-01",
    conceptIds: ["I-10"],
    primaryConceptId: "I-10",
    title: "分数式を通分する",
    prompt: "x≠±1のとき、1/(x−1)−1/(x+1)を簡単にすると？",
    options: ["2/(x²−1)", "2x/(x²−1)", "−2/(x²−1)", "1/(2x)"],
    answer: 0,
    explanation: "分子は(x+1)−(x−1)=2、分母は(x−1)(x+1)=x²−1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I13-01",
    conceptIds: ["I-13"],
    primaryConceptId: "I-13",
    title: "和と積から平方和へ",
    prompt: "a+b=4,ab=1のとき、a²+b²は？",
    options: ["12", "14", "16", "18"],
    answer: 1,
    explanation: "a²+b²=(a+b)²−2ab=16−2=14。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-I17-01",
    conceptIds: ["I-17"],
    primaryConceptId: "I-17",
    title: "係数から解の和と積",
    prompt: "2x²−7x+3=0の2解をα,βとする。α+βとαβの組は？",
    options: ["(7/2,3/2)", "(−7/2,3/2)", "(7/2,−3/2)", "(7,3)"],
    answer: 0,
    explanation: "解と係数の関係より、和は−(−7)/2=7/2、積は3/2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-I18-01",
    conceptIds: ["I-18"],
    primaryConceptId: "I-18",
    title: "連立した範囲を読む",
    prompt: "−2≤3x+1<7を満たすxの範囲は？",
    options: ["−1≤x<2", "−1<x≤2", "−2≤x<7", "−1≤x≤2"],
    answer: 0,
    explanation: "両辺から1を引いて3で割ると、−1≤x<2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-I20-01",
    conceptIds: ["I-20"],
    primaryConceptId: "I-20",
    title: "二次不等式の符号表",
    prompt: "x²−5x+6≤0の解は？",
    options: ["x≤2またはx≥3", "2≤x≤3", "2<x<3", "x<2またはx>3"],
    answer: 1,
    explanation: "(x−2)(x−3)≤0。上に開くので、2と3の間を含む。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I23-01",
    conceptIds: ["I-23"],
    primaryConceptId: "I-23",
    title: "一次関数の値域",
    prompt: "y=2x+1、−1≤x≤3のとき、yの値域は？",
    options: ["−1≤y≤3", "−1≤y≤7", "1≤y≤7", "−3≤y≤6"],
    answer: 1,
    explanation: "傾きが正なので端点で最小・最大。x=−1で−1、x=3で7。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X-IA-I26-01",
    conceptIds: ["I-26"],
    primaryConceptId: "I-26",
    title: "一般形を平方完成する",
    prompt: "y=2x²−8x+1の頂点は？",
    options: ["(2,−7)", "(−2,−7)", "(2,7)", "(4,1)"],
    answer: 0,
    explanation: "y=2(x−2)²−7と変形できるので、頂点は(2,−7)。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I33-01",
    conceptIds: ["I-33"],
    primaryConceptId: "I-33",
    title: "係数を条件から決める",
    prompt: "y=a(x−1)²+2が点(3,10)を通るとき、aは？",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "10=a(3−1)²+2=4a+2。よってa=2。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  // ── 数学I：図形と計量・データ ─────────────────────────────────
  {
    id: "X-IA-I35-01",
    conceptIds: ["I-35"],
    primaryConceptId: "I-35",
    title: "直角三角形のcos",
    prompt: "直角三角形で斜辺が10、ある角に隣り合う辺が5のとき、その角のcosは？",
    options: ["1/2", "√3/2", "2", "5"],
    answer: 0,
    explanation: "cos=隣辺/斜辺なので、5/10=1/2。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I37-01",
    conceptIds: ["I-37"],
    primaryConceptId: "I-37",
    title: "正弦定理で辺を求める",
    prompt: "角A=30°の向かいの辺が6、角B=90°の向かいの辺をbとする。bは？",
    options: ["3", "6", "12", "18"],
    answer: 2,
    explanation: "正弦定理より6/sin30°=b/sin90°。b=6/(1/2)=12。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-I38-01",
    conceptIds: ["I-38"],
    primaryConceptId: "I-38",
    title: "余弦定理で残りの辺",
    prompt: "2辺が5,7で、その間の角が60°の三角形の残りの辺の長さは？",
    options: ["√21", "√31", "√39", "6"],
    answer: 2,
    explanation: "余弦定理よりx²=5²+7²−2・5・7・cos60°=39。x=√39。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "X-IA-I41-01",
    conceptIds: ["I-41"],
    primaryConceptId: "I-41",
    title: "仰角から高さを読む",
    prompt: "建物から20m離れた地点で、頂上への仰角が30°だった。目の高さを無視した建物の高さは？",
    options: ["10", "20/√3", "20√3", "40"],
    answer: 1,
    explanation: "tan30°=高さ/20。高さ=20tan30°=20/√3=20√3/3。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X-IA-I45-01",
    conceptIds: ["I-45"],
    primaryConceptId: "I-45",
    title: "四分位範囲を読む",
    prompt: "箱ひげ図で第1四分位数が12、第3四分位数が20のとき、四分位範囲は？",
    options: ["8", "12", "20", "32"],
    answer: 0,
    explanation: "四分位範囲はQ3−Q1なので、20−12=8。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I48-01",
    conceptIds: ["I-48"],
    primaryConceptId: "I-48",
    title: "データをずらした分散",
    prompt: "すべてのデータに7を加えたとき、分散はどうなる？",
    options: ["7増える", "49増える", "変わらない", "7分の1になる"],
    answer: 2,
    explanation: "全データに同じ数を加えても偏差は変わらないため、分散も変わらない。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-I51-01",
    conceptIds: ["I-51"],
    primaryConceptId: "I-51",
    title: "完全な正の相関",
    prompt: "データの組が(1,2),(2,4),(3,6)だけであるとき、相関係数rは？",
    options: ["−1", "−1/2", "0", "1"],
    answer: 3,
    explanation: "y=2xに完全に並ぶので、正の相関が完全でr=1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  // ── 数学A：場合の数と確率 ─────────────────────────────────────
  {
    id: "X-IA-A01-01",
    conceptIds: ["A-01"],
    primaryConceptId: "A-01",
    title: "場合を分けて足す",
    prompt: "3本のバス路線または2本の鉄道路線から、重ならない1つを選ぶ方法は何通り？",
    options: ["2", "3", "5", "6"],
    answer: 2,
    explanation: "バスを選ぶ3通りと鉄道を選ぶ2通りは重ならないので、3+2=5通り。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "X-IA-A02-01",
    conceptIds: ["A-02"],
    primaryConceptId: "A-02",
    title: "桁ごとに選ぶ",
    prompt: "0〜9の数字を重複を許して3個並べ、3桁の暗証番号を作る方法は何通り？",
    options: ["30", "100", "900", "1000"],
    answer: 3,
    explanation: "各桁に10通りずつ選べるので、10×10×10=1000通り。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A03-01",
    conceptIds: ["A-03"],
    primaryConceptId: "A-03",
    title: "階乗を計算する",
    prompt: "5!の値は？",
    options: ["25", "60", "120", "240"],
    answer: 2,
    explanation: "5!=5×4×3×2×1=120。",
    kind: "quick",
    estimatedSeconds: 35,
  },
  {
    id: "X-IA-A05-01",
    conceptIds: ["A-05"],
    primaryConceptId: "A-05",
    title: "組合せで選ぶ",
    prompt: "8人から委員を2人選ぶ方法は何通り？",
    options: ["16", "28", "32", "56"],
    answer: 1,
    explanation: "順番を区別しないので、8C2=8×7/2=28。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X-IA-A06-01",
    conceptIds: ["A-06"],
    primaryConceptId: "A-06",
    title: "同じものを含む並べ方",
    prompt: "A,A,B,Cの4文字を1列に並べる方法は何通り？",
    options: ["6", "8", "12", "24"],
    answer: 2,
    explanation: "同じAを区別すると4!通りだが、Aの入れ替えを2!で割り、4!/2!=12。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-A07-01",
    conceptIds: ["A-07"],
    primaryConceptId: "A-07",
    title: "円順列の回転を同一視する",
    prompt: "5人が円形のテーブルに座る方法は何通り？回転だけは同じ配置とする。",
    options: ["20", "24", "60", "120"],
    answer: 1,
    explanation: "1人を固定して残り4人を並べるので、(5−1)!=24。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-A08-01",
    conceptIds: ["A-08"],
    primaryConceptId: "A-08",
    title: "二項係数を読む",
    prompt: "(1+x)^5を展開したときのx³の係数は？",
    options: ["5", "10", "15", "20"],
    answer: 1,
    explanation: "x³の係数は5C3=5C2=10。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A09-01",
    conceptIds: ["A-09"],
    primaryConceptId: "A-09",
    title: "少なくとも1回を余事象で数える",
    prompt: "公平なさいころを2回投げ、少なくとも1回6が出る確率は？",
    options: ["1/6", "5/12", "11/36", "25/36"],
    answer: 2,
    explanation: "余事象「1回も6が出ない」は(5/6)²。求める確率は1−25/36=11/36。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-A10-01",
    conceptIds: ["A-10"],
    primaryConceptId: "A-10",
    title: "標本空間を数える",
    prompt: "公平なコインを2回投げる。表がちょうど1回出る確率は？",
    options: ["1/4", "1/3", "1/2", "3/4"],
    answer: 2,
    explanation: "標本空間はHH,HT,TH,TTの4通り。該当するHT,THの2通りなので2/4=1/2。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X-IA-A11-01",
    conceptIds: ["A-11"],
    primaryConceptId: "A-11",
    title: "和事象の重なりを数える",
    prompt: "さいころ1個で、偶数または3の倍数が出る確率は？",
    options: ["1/3", "1/2", "2/3", "5/6"],
    answer: 2,
    explanation: "該当する目は2,3,4,6の4個。確率は4/6=2/3。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X-IA-A12-01",
    conceptIds: ["A-12"],
    primaryConceptId: "A-12",
    title: "排反事象の確率を足す",
    prompt: "排反な事象A,BについてP(A)=0.4,P(B)=0.5のとき、P(A∪B)は？",
    options: ["0.1", "0.4", "0.5", "0.9"],
    answer: 3,
    explanation: "排反なら共通部分がないので、P(A∪B)=P(A)+P(B)=0.9。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A13-01",
    conceptIds: ["A-13"],
    primaryConceptId: "A-13",
    title: "条件付き確率を更新する",
    prompt: "赤玉3個、青玉2個から続けて2個を戻さず取り出す。1個目が赤だったとき、2個目も赤である確率は？",
    options: ["1/5", "1/2", "2/5", "3/5"],
    answer: 1,
    explanation: "1個目が赤と分かった後は、残り4個中赤2個。条件付き確率は2/4=1/2。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-A14-01",
    conceptIds: ["A-14"],
    primaryConceptId: "A-14",
    title: "乗法定理で連続事象",
    prompt: "赤玉3個、青玉2個から2個を戻さず取り出す。1個目が赤、2個目が青となる確率は？",
    options: ["1/5", "3/10", "2/5", "1/2"],
    answer: 1,
    explanation: "1個目が赤は3/5、続いて青は2/4。積をとって3/5×2/4=3/10。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-A15-01",
    conceptIds: ["A-15"],
    primaryConceptId: "A-15",
    title: "独立性を判定する",
    prompt: "P(A)=1/2,P(B)=2/3,P(A∩B)=1/3のとき、AとBは？",
    options: ["排反", "独立", "必ず同時に起こる", "判定できない"],
    answer: 1,
    explanation: "P(A)P(B)=1/2×2/3=1/3=P(A∩B)。したがって独立。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-A16-01",
    conceptIds: ["A-16"],
    primaryConceptId: "A-16",
    title: "独立試行を繰り返す",
    prompt: "公平なコインを4回投げて、表がちょうど3回出る確率は？",
    options: ["1/16", "1/4", "3/8", "1/2"],
    answer: 1,
    explanation: "表の位置を4C3通り選べるので、4C3×(1/2)^4=4/16=1/4。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X-IA-A17-01",
    conceptIds: ["A-17"],
    primaryConceptId: "A-17",
    title: "二項型の確率を作る",
    prompt: "さいころを3回投げ、6がちょうど1回出る確率は？",
    options: ["5/72", "25/72", "1/2", "25/36"],
    answer: 1,
    explanation: "6の位置が3通りあり、3×(1/6)×(5/6)²=75/216=25/72。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X-IA-A18-01",
    conceptIds: ["A-18"],
    primaryConceptId: "A-18",
    title: "期待値を重み付き平均で出す",
    prompt: "確率3/4で0点、確率1/4で8点を得るゲームの得点の期待値は？",
    options: ["1", "2", "4", "8"],
    answer: 1,
    explanation: "期待値は0×3/4+8×1/4=2。結果と確率を掛けて足す。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  // ── 数学A：図形の性質 ─────────────────────────────────────────
  {
    id: "X-IA-A19-01",
    conceptIds: ["A-19"],
    primaryConceptId: "A-19",
    title: "幾何の基本公理",
    prompt: "異なる2点を通る直線について、正しいものは？",
    options: ["必ず2本ある", "ちょうど1本定まる", "点の位置で本数が変わる", "直線は定まらない"],
    answer: 1,
    explanation: "異なる2点を通る直線はちょうど1本。図形を論証する出発点になる。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "X-IA-A20-01",
    conceptIds: ["A-20"],
    primaryConceptId: "A-20",
    title: "合同条件を選ぶ",
    prompt: "三角形の合同条件の1つはどれ？",
    options: ["3辺と3角のうち1角", "2辺とその間の角", "1辺と1角", "3角だけ"],
    answer: 1,
    explanation: "2辺とその間の角がそれぞれ等しい（SAS）は三角形の合同条件。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-A21-01",
    conceptIds: ["A-21"],
    primaryConceptId: "A-21",
    title: "相似条件を選ぶ",
    prompt: "三角形の相似条件の1つはどれ？",
    options: ["2つの角がそれぞれ等しい", "1辺だけが等しい", "面積が等しい", "周の長さが等しい"],
    answer: 0,
    explanation: "2角がそれぞれ等しい（AA）なら、残りの角も等しく相似になる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-A22-01",
    conceptIds: ["A-22"],
    primaryConceptId: "A-22",
    title: "外角は内対角の和",
    prompt: "三角形のある外角に対する2つの内対角が50°,60°のとき、外角は？",
    options: ["10°", "50°", "110°", "170°"],
    answer: 2,
    explanation: "三角形の外角は、隣り合わない2つの内角の和。50°+60°=110°。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A23-01",
    conceptIds: ["A-23"],
    primaryConceptId: "A-23",
    title: "メネラウスの定理を使う",
    prompt: "△ABCで、DはBC上、EはCA上、FはABのB側延長上にあり、D,E,Fは一直線上にある。BD/DC=2/3、CE/EA=3/4のとき、AF/BFは？",
    options: ["1/2", "2/3", "1", "2"],
    answer: 3,
    explanation: "メネラウスの定理より(BD/DC)(CE/EA)(AF/BF)=1。よってAF/BF=1÷(2/3×3/4)=2。",
    kind: "transfer",
    estimatedSeconds: 100,
  },
  {
    id: "X-IA-A24-01",
    conceptIds: ["A-24"],
    primaryConceptId: "A-24",
    title: "チェバの定理で比を決める",
    prompt: "3本の線分AD,BE,CFが1点で交わり、BD/DC=2、CE/EA=3、AF/FB=xである。xは？",
    options: ["1/6", "1/3", "2/3", "6"],
    answer: 0,
    explanation: "チェバの定理より(2)(3)x=1。したがってx=1/6。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X-IA-A25-01",
    conceptIds: ["A-25"],
    primaryConceptId: "A-25",
    title: "垂直二等分線の性質",
    prompt: "線分ABの垂直二等分線上にある点Pについて、必ず成り立つ関係は？",
    options: ["PA=PB", "PA=AB", "PB=AB", "PA+PB=AB"],
    answer: 0,
    explanation: "垂直二等分線上の点は、線分の両端A,Bから等距離にある。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-A26-01",
    conceptIds: ["A-26"],
    primaryConceptId: "A-26",
    title: "角の二等分線と比",
    prompt: "△ABCでAB=6,AC=9。Aの角の二等分線とBCの交点をDとすると、BD:DCは？",
    options: ["1:2", "2:3", "3:2", "2:1"],
    answer: 1,
    explanation: "角の二等分線定理よりBD:DC=AB:AC=6:9=2:3。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-A27-01",
    conceptIds: ["A-27"],
    primaryConceptId: "A-27",
    title: "重心の分割比",
    prompt: "三角形ABCで、AからBCの中点Mへ引いた中線上の重心Gについて、AG:GMは？",
    options: ["1:1", "1:2", "2:1", "3:1"],
    answer: 2,
    explanation: "重心は中線を頂点側から2:1に分けるので、AG:GM=2:1。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A28-01",
    conceptIds: ["A-28"],
    primaryConceptId: "A-28",
    title: "垂心を定義する",
    prompt: "三角形の垂心とは何の交点？",
    options: ["3本の中線", "3本の角の二等分線", "3本の高さ", "3本の垂直二等分線"],
    answer: 2,
    explanation: "垂心は、各頂点から対辺またはその延長へ下ろした3本の高さの交点。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "X-IA-A29-01",
    conceptIds: ["A-29"],
    primaryConceptId: "A-29",
    title: "内接円の半径",
    prompt: "三角形の面積が30、半周長が10のとき、内接円の半径rは？",
    options: ["2", "3", "5", "10"],
    answer: 1,
    explanation: "面積は半周長×内接円の半径、30=10rよりr=3。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X-IA-A32-01",
    conceptIds: ["A-32"],
    primaryConceptId: "A-32",
    title: "接線と弦の角",
    prompt: "円周上の点Aでの接線と弦ABがつくる角に対する円周角が40°のとき、接線と弦の角の鋭角は？",
    options: ["20°", "40°", "80°", "140°"],
    answer: 1,
    explanation: "接線と弦のつくる角は、その弦に対する円周角に等しいので40°。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-A34-01",
    conceptIds: ["A-34"],
    primaryConceptId: "A-34",
    title: "交わる弦の積",
    prompt: "円の内部で2本の弦AB,CDがPで交わり、PA=3,PB=8,PC=4,PD=xのとき、xは？",
    options: ["4", "6", "8", "12"],
    answer: 1,
    explanation: "交わる弦の定理よりPA・PB=PC・PD。3×8=4xなのでx=6。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X-IA-A35-01",
    conceptIds: ["A-35"],
    primaryConceptId: "A-35",
    title: "円周角から中心角へ",
    prompt: "円周上の三角形ABCで∠B=60°。中心Oにおける弧ACに対する中心角∠AOCは？",
    options: ["30°", "60°", "120°", "240°"],
    answer: 2,
    explanation: "同じ弧に対する中心角は円周角の2倍。∠AOC=2×60°=120°。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X-IA-A36-01",
    conceptIds: ["A-36"],
    primaryConceptId: "A-36",
    title: "軌跡を定める",
    prompt: "2点A,Bからの距離が等しい点Pの軌跡は？",
    options: ["ABを直径とする円", "ABの垂直二等分線", "ABに平行な直線", "点Aだけ"],
    answer: 1,
    explanation: "PA=PBを満たす点の集合は、線分ABの垂直二等分線。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X-IA-A37-01",
    conceptIds: ["A-37"],
    primaryConceptId: "A-37",
    title: "空間で平面を決める",
    prompt: "空間内の交わる2直線について、正しいものは？",
    options: ["必ず同じ長さである", "その2直線を含む平面がただ1つ定まる", "平面は無限に定まる", "必ず平行である"],
    answer: 1,
    explanation: "交わる2直線は同じ平面上にあり、その2直線を含む平面はただ1つ。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X-IA-A38-01",
    conceptIds: ["A-38"],
    primaryConceptId: "A-38",
    title: "平面への垂直",
    prompt: "平面上の交わる2直線の両方に垂直な直線は、その平面に対してどうなる？",
    options: ["平面に平行", "平面上にある", "平面に垂直", "必ず平面と一致"],
    answer: 2,
    explanation: "平面上の交わる2直線に垂直な直線は、その平面に垂直である。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X-IA-A39-01",
    conceptIds: ["A-39"],
    primaryConceptId: "A-39",
    title: "立方体の平行断面",
    prompt: "一辺4の立方体を、1つの面に平行な平面で切った。断面の面積は？",
    options: ["4", "8", "16", "64"],
    answer: 2,
    explanation: "面に平行な断面は一辺4の正方形なので、面積は4²=16。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
];
