import type { Problem } from "../problem-bank";

/**
 * 共通テスト対象の数学I・A・IIについて、既存問題とは別に用意した補充問題。
 * 指定概念を1問ずつ扱い、基本確認から状況の読み替えまでを混ぜている。
 */
export const gapIAII: Problem[] = [
  {
    id: "GAP-IAII-01",
    conceptIds: ["I-01"],
    primaryConceptId: "I-01",
    title: "積で判定する有理数",
    prompt: "次の数のうち、有理数であるものはどれ？",
    options: ["√8・√2", "√3+1", "√5/2", "π−1"],
    answer: 0,
    explanation: "√8・√2=√16=4であり、整数は有理数である。他の数は有理数と無理数の和や、無理数の定数倍なので無理数である。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "GAP-IAII-02",
    conceptIds: ["I-02"],
    primaryConceptId: "I-02",
    title: "不等式を区間で表す",
    prompt: "不等式−2<3x+1≤7を満たす実数xの範囲を、区間の記号で表すと？",
    options: ["[−1,2]", "(−1,2]", "[−2,7)", "(−2,7]"],
    answer: 1,
    explanation: "両辺から1を引くと−3<3x≤6。3は正なのでそのまま割り、−1<x≤2となる。したがって区間は(−1,2]である。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-IAII-03",
    conceptIds: ["I-05"],
    primaryConceptId: "I-05",
    title: "倍数条件の向きを読む",
    prompt: "xを整数とする。Pを「xが6の倍数である」、Qを「xが3の倍数である」とする。PとQの関係として正しいものは？",
    options: [
      "PはQの十分条件で、QはPの必要条件である",
      "PはQの必要条件で、QはPの十分条件である",
      "PはQの必要十分条件である",
      "PとQには必要条件・十分条件の関係はない",
    ],
    answer: 0,
    explanation: "6の倍数なら必ず3の倍数なのでP⇒Q。したがってPはQの十分条件、QはPの必要条件である。x=3はQを満たすがPを満たさないので、必要十分条件ではない。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "GAP-IAII-04",
    conceptIds: ["I-27"],
    primaryConceptId: "I-27",
    title: "式から移動を読む",
    prompt: "関数y=f(x)のグラフを、y=f(x−3)+2のグラフに移す操作として正しいものは？",
    options: ["左へ3、下へ2", "右へ3、上へ2", "右へ3、下へ2", "左へ3、上へ2"],
    answer: 1,
    explanation: "xをx−3に置き換えるとグラフは右へ3移動し、外側に+2を加えると上へ2移動する。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "GAP-IAII-05",
    conceptIds: ["I-32"],
    primaryConceptId: "I-32",
    title: "モデルの定義域を確認する",
    prompt: "ある物体の高さh(t)（m）がh(t)=−t²+6t+4（0≤t≤6）で表される。このモデルでの最高点の高さと、そのときのtの値の組は？",
    options: ["(4,0)", "(10,3)", "(13,3)", "(13,6)"],
    answer: 2,
    explanation: "h(t)=−(t−3)²+13と平方完成できる。頂点のt=3は定義域0≤t≤6に含まれるので、最高点は高さ13m、t=3である。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "GAP-IAII-06",
    conceptIds: ["A-30"],
    primaryConceptId: "A-30",
    title: "同じ弧に対する円周角",
    prompt: "円周上の4点A,B,C,Dについて、CとDが弦ABに対して同じ側にあり、∠ACB=37°である。∠ADBは？",
    options: ["37°", "74°", "143°", "180°"],
    answer: 0,
    explanation: "同じ弦ABに対する円周角で、頂点が弦ABの同じ側にあるものは等しい。したがって∠ADB=∠ACB=37°。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "GAP-IAII-07",
    conceptIds: ["A-31"],
    primaryConceptId: "A-31",
    title: "内接四角形の文字角",
    prompt: "円に内接する四角形ABCDで、∠A=(2x+10)°、∠C=(3x−5)°である。xの値は？",
    options: ["30", "35", "40", "45"],
    answer: 1,
    explanation: "円に内接する四角形の対角の和は180°だから、(2x+10)+(3x−5)=180。よって5x+5=180よりx=35。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-IAII-08",
    conceptIds: ["A-33"],
    primaryConceptId: "A-33",
    title: "2本の割線の積",
    prompt: "円の外部の点Pから2本の割線を引く。1本の割線上で、Pから2つの交点までの距離が4と10、もう1本では5とxである。xは？",
    options: ["6", "8", "10", "12"],
    answer: 1,
    explanation: "点Pの冪はどの割線でも一定なので、4×10=5×x。したがってx=8である。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "GAP-IAII-09",
    conceptIds: ["II-05"],
    primaryConceptId: "II-05",
    title: "割り算の余りを代入で求める",
    prompt: "P(x)=2x³−x+4をx+1で割ったときの余りは？",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "x+1=x−(−1)なので、剰余定理より余りはP(−1)。P(−1)=2(−1)³−(−1)+4=3である。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "GAP-IAII-10",
    conceptIds: ["II-06"],
    primaryConceptId: "II-06",
    title: "因数条件から係数を決める",
    prompt: "P(x)=x³−5x²+ax+6がx−2を因数にもつとき、aの値は？",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "因数定理よりP(2)=0。8−20+2a+6=0、すなわち2a−6=0だからa=3である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-IAII-11",
    conceptIds: ["II-17"],
    primaryConceptId: "II-17",
    title: "点と傾きから直線を作る",
    prompt: "点(−2,3)を通り、傾きが−2である直線の方程式は？",
    options: ["y=−2x−1", "y=−2x+7", "y=2x−1", "y=2x+7"],
    answer: 0,
    explanation: "点傾きの式よりy−3=−2(x+2)。整理するとy=−2x−1となる。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-IAII-12",
    conceptIds: ["II-18"],
    primaryConceptId: "II-18",
    title: "平行条件を式にする",
    prompt: "直線2x−3y+1=0に平行で、点(0,−2)を通る直線の方程式は？",
    options: ["2x−3y−6=0", "3x+2y+4=0", "2x−3y+6=0", "3x+2y−4=0"],
    answer: 0,
    explanation: "与えられた直線の傾きは2/3。平行な直線をy=(2/3)x+bとおき、(0,−2)を代入するとb=−2。整理して2x−3y−6=0となる。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "GAP-IAII-13",
    conceptIds: ["II-19"],
    primaryConceptId: "II-19",
    title: "一般形から円の中心を読む",
    prompt: "方程式x²+y²−4x+6y−3=0で表される円の中心と半径の組は？",
    options: ["(2,−3), 4", "(−2,3), 4", "(2,−3), 2", "(−2,3), 2"],
    answer: 0,
    explanation: "平方完成すると(x−2)²+(y+3)²=16。したがって中心は(2,−3)、半径は4である。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "GAP-IAII-14",
    conceptIds: ["II-22"],
    primaryConceptId: "II-22",
    title: "半平面に含まれる点",
    prompt: "不等式2x−y<3が表す領域に含まれる点はどれ？",
    options: ["(0,0)", "(2,0)", "(0,−4)", "(2,1)"],
    answer: 0,
    explanation: "各点を代入すると、(0,0)では0<3が成り立つ。他の3点では左辺がそれぞれ4,4,3となり、厳密な不等式を満たさない。",
    kind: "transfer",
    estimatedSeconds: 65,
  },
  {
    id: "GAP-IAII-15",
    conceptIds: ["II-33"],
    primaryConceptId: "II-33",
    title: "底が1未満の指数不等式",
    prompt: "(1/3)^(x−1)≥1/27を満たすxの範囲は？",
    options: ["x≤4", "x≥4", "x≤2", "x≥2"],
    answer: 0,
    explanation: "1/27=(1/3)³で、底1/3は0より大きく1より小さい。したがって指数の大小が逆になり、x−1≤3、つまりx≤4である。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "GAP-IAII-16",
    conceptIds: ["II-35"],
    primaryConceptId: "II-35",
    title: "対数の商の法則",
    prompt: "log₂12−log₂3の値は？",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "対数の商の法則よりlog₂12−log₂3=log₂(12/3)=log₂4=2。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "GAP-IAII-17",
    conceptIds: ["II-40"],
    primaryConceptId: "II-40",
    title: "ラジアンを度に直す",
    prompt: "角5π/6を度数法で表すと？",
    options: ["120°", "150°", "180°", "300°"],
    answer: 1,
    explanation: "π rad=180°なので、5π/6 rad=5×180°/6=150°である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "GAP-IAII-18",
    conceptIds: ["II-47"],
    primaryConceptId: "II-47",
    title: "周期を含む三角方程式",
    prompt: "0≤x<4πのとき、cos x=1/2を満たすxの組はどれ？",
    options: [
      "π/3,5π/3",
      "π/3,5π/3,7π/3,11π/3",
      "2π/3,4π/3,8π/3,10π/3",
      "π/6,5π/6,13π/6,17π/6",
    ],
    answer: 1,
    explanation: "cos x=1/2の基本解はπ/3と5π/3。これらに2πの整数倍を加え、0≤x<4πに入るものを全て選ぶと、π/3,5π/3,7π/3,11π/3となる。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-IAII-19",
    conceptIds: ["II-52"],
    primaryConceptId: "II-52",
    title: "各項を微分する",
    prompt: "f(x)=4x⁴−3x²+5x−7の導関数f'(x)は？",
    options: ["16x³−6x+5", "4x³−3x+5", "16x³−3x+5", "4x⁴−3x²+5"],
    answer: 0,
    explanation: "各項を微分すると、4x⁴は16x³、−3x²は−6x、5xは5、定数−7は0になる。したがってf'(x)=16x³−6x+5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "GAP-IAII-20",
    conceptIds: ["II-54"],
    primaryConceptId: "II-54",
    title: "導関数の符号表",
    prompt: "導関数がf'(x)=x(x−3)で与えられるとき、f'(x)>0となり、f(x)が増加する開区間は？",
    options: ["x<0またはx>3", "0<x<3", "x≤0またはx≥3", "すべての実数"],
    answer: 0,
    explanation: "x(x−3)の符号を考えると、x<0とx>3では正、0<x<3では負になる。よってf(x)はx<0とx>3で増加する。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "GAP-IAII-21",
    conceptIds: ["II-60"],
    primaryConceptId: "II-60",
    title: "放物線とx軸で囲む面積",
    prompt: "放物線y=4−x²とx軸、および直線x=0,x=2で囲まれる面積は？",
    options: ["4", "16/3", "8", "32/3"],
    answer: 1,
    explanation: "0≤x≤2では4−x²≥0なので、面積は∫₀²(4−x²)dx=[4x−x³/3]₀²=8−8/3=16/3である。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
];
