import type { Problem } from "../problem-bank";

/**
 * 共通テスト対象の数学Cで、既存バンクの直接演習が薄かった概念を補う問題。
 * 各概念につき1問、短い確認から表現の読み替えまで段階を混ぜている。
 */
export const gapC: Problem[] = [
  {
    id: "GAP-C-01",
    conceptIds: ["C-02"],
    primaryConceptId: "C-02",
    title: "位置が違っても等しいベクトル",
    prompt: "P(−1,2), Q(2,−2), R(4,5), S(7,1)について、等しいベクトルの組はどれ？",
    options: ["PQとRS", "PQとSR", "PRとQS", "QPとRS"],
    answer: 0,
    explanation: "PQ=(3,−4)、RS=(3,−4)なので、始点の位置が違っても向きと大きさが同じPQとRSは等しい。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-C-02",
    conceptIds: ["C-03"],
    primaryConceptId: "C-03",
    title: "ベクトルを成分ごとに足す",
    prompt: "u=(2,−3), v=(−1,5)のとき、u+vはどれ？",
    options: ["(1,2)", "(3,−8)", "(−1,2)", "(2,−3)"],
    answer: 0,
    explanation: "ベクトルの和は対応する成分を足すので、u+v=(2−1,−3+5)=(1,2)。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "GAP-C-03",
    conceptIds: ["C-06"],
    primaryConceptId: "C-06",
    title: "点の位置ベクトル",
    prompt: "空間内の点A(−3,2,1)について、位置ベクトルOAはどれ？",
    options: ["(−3,2,1)", "(3,−2,−1)", "(−3,−2,1)", "(1,2,−3)"],
    answer: 0,
    explanation: "位置ベクトルOAは原点OからAへ向かうベクトルで、点Aの3座標をそのまま成分にもつ。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "GAP-C-04",
    conceptIds: ["C-15"],
    primaryConceptId: "C-15",
    title: "空間座標の中点",
    prompt: "空間内の2点A(1,−2,3), B(4,2,−1)を結ぶ線分の中点はどれ？",
    options: ["(5/2,0,1)", "(3/2,0,2)", "(5/2,2,1)", "(4,0,−1)"],
    answer: 0,
    explanation: "中点は各座標の平均だから、((1+4)/2,(−2+2)/2,(3−1)/2)=(5/2,0,1)。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "GAP-C-05",
    conceptIds: ["C-16"],
    primaryConceptId: "C-16",
    title: "空間ベクトルの演算",
    prompt: "空間ベクトルu=(1,−2,3), v=(2,1,−1)のとき、2u−vはどれ？",
    options: ["(0,−5,7)", "(4,−3,5)", "(0,−3,5)", "(2,−4,6)"],
    answer: 0,
    explanation: "2u=(2,−4,6)なので、2u−v=(2−2,−4−1,6−(−1))=(0,−5,7)。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-C-06",
    conceptIds: ["C-18"],
    primaryConceptId: "C-18",
    title: "空間の平面を表す",
    prompt: "平面を x=(1,0,2)+s(1,1,0)+t(0,1,1) と表す。s=2, t=−1に対応する点はどれ？",
    options: ["(3,1,1)", "(2,−1,3)", "(3,−1,1)", "(1,1,3)"],
    answer: 0,
    explanation: "各成分を代入すると、(1,0,2)+2(1,1,0)−(0,1,1)=(3,1,1)。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "GAP-C-07",
    conceptIds: ["C-19"],
    primaryConceptId: "C-19",
    title: "対角線の中点をベクトルで示す",
    prompt: "四角形ABCDの頂点の位置ベクトルをa,b,c,dとする。対角線ACとBDが互いに中点で交わることを示す条件はどれ？",
    options: ["a+c=b+d", "a+b=c+d", "a−c=b−d", "a+b+c+d=0"],
    answer: 0,
    explanation: "ACの中点は(a+c)/2、BDの中点は(b+d)/2。これらが等しい条件を2倍するとa+c=b+dとなる。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "GAP-C-08",
    conceptIds: ["C-20"],
    primaryConceptId: "C-20",
    title: "ベクトルで最短距離を読む",
    prompt: "点Pがx軸上を動くとき、点A(1,2)との距離APの最小値は？",
    options: ["1", "2", "√5", "4"],
    answer: 1,
    explanation: "Aからx軸へ下ろした垂線の足(1,0)が最も近い。距離は|2−0|=2である。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "GAP-C-09",
    conceptIds: ["C-26"],
    primaryConceptId: "C-26",
    title: "複素数の商の回転と拡大",
    prompt: "z₁=2(cos(π/3)+i sin(π/3)), z₂=cos(π/6)+i sin(π/6)とする。z₁/z₂の絶対値と主偏角（0≤θ<2π）の組はどれ？",
    options: ["(1,π/6)", "(2,π/6)", "(2,π/2)", "(3,π/2)"],
    answer: 1,
    explanation: "商では絶対値を割り、偏角を引く。主偏角の範囲で|z₁/z₂|=2、θ=π/3−π/6=π/6。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-C-10",
    conceptIds: ["C-28"],
    primaryConceptId: "C-28",
    title: "複素数の3乗根",
    prompt: "方程式z³=−8iの解のうち、必ず含まれるものはどれ？",
    options: ["2i", "−2i", "2", "√3+i"],
    answer: 0,
    explanation: "(2i)³=8i³=−8iなので、2iは解。3乗根は偏角を3等分して得られ、解は全部で3個ある。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-C-11",
    conceptIds: ["C-31"],
    primaryConceptId: "C-31",
    title: "一次複素変換を分解する",
    prompt: "複素数平面上の変換w=(1+i)z+2は、幾何的にどの操作を表す？",
    options: ["45°反時計回りに回転し、√2倍してから実軸方向に2平行移動", "90°反時計回りに回転し、2倍してから実軸方向に1平行移動", "√2倍してから45°時計回りに回転し、虚軸方向に2平行移動", "2倍してから45°反時計回りに回転するだけ"],
    answer: 0,
    explanation: "1+i=√2(cos(π/4)+i sin(π/4))なので、掛け算は√2倍と45°反時計回りの回転。+2は実軸方向の平行移動である。",
    kind: "transfer",
    estimatedSeconds: 95,
  },
  {
    id: "GAP-C-12",
    conceptIds: ["C-34"],
    primaryConceptId: "C-34",
    title: "焦点と準線から放物線を作る",
    prompt: "焦点F(0,2)、準線y=−2からの距離が等しい点(x,y)の軌跡はどれ？",
    options: ["x²=8y", "x²=4y", "y²=8x", "x²+y²=4"],
    answer: 0,
    explanation: "距離の等式x²+(y−2)²=(y+2)²を整理するとx²=8y。焦点と準線の距離条件が放物線を定める。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-C-13",
    conceptIds: ["C-35"],
    primaryConceptId: "C-35",
    title: "楕円の焦点性質",
    prompt: "楕円x²/25+y²/9=1上の点Pについて、2つの焦点からPまでの距離の和はいくつ？",
    options: ["6", "8", "10", "25"],
    answer: 2,
    explanation: "楕円の長半軸はa=5。2焦点からの距離の和は一定で2aだから、2×5=10。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "GAP-C-14",
    conceptIds: ["C-36"],
    primaryConceptId: "C-36",
    title: "双曲線の焦点性質",
    prompt: "焦点が(−5,0),(5,0)で、2焦点からの距離の差の絶対値が6である双曲線の方程式はどれ？",
    options: ["x²/9−y²/16=1", "x²/25−y²/36=1", "x²/16+y²/9=1", "y²/9−x²/16=1"],
    answer: 0,
    explanation: "距離の差は2a=6よりa=3、焦点距離はc=5。b²=c²−a²=25−9=16なので、x²/9−y²/16=1。",
    kind: "transfer",
    estimatedSeconds: 100,
  },
  {
    id: "GAP-C-15",
    conceptIds: ["C-38"],
    primaryConceptId: "C-38",
    title: "放物線の接線",
    prompt: "放物線y²=4x上の点(1,2)における接線の方程式はどれ？",
    options: ["y=x+1", "y=2x", "y=x−1", "y=2x+1"],
    answer: 0,
    explanation: "2yy'=4より、点(1,2)での傾きはy'=1。点(1,2)を通るのでy−2=x−1、つまりy=x+1。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-C-16",
    conceptIds: ["C-40"],
    primaryConceptId: "C-40",
    title: "媒介変数の範囲を含めて読む",
    prompt: "x=cos t, y=sin t (0≤t≤π)で表される曲線はどれ？",
    options: ["単位円の上半分", "単位円の下半分", "直線y=x", "半径2の円全体"],
    answer: 0,
    explanation: "x²+y²=1で円周上にあり、0≤t≤πではsin t≥0。したがって単位円の上半分を表す。",
    kind: "quick",
    estimatedSeconds: 65,
  },
];
