import type { Problem } from "../problem-bank";

/**
 * 共テ対象の未カバー概念を埋める追加問題。
 * 対象は数学II 9問、数学B 10問の計19問。すべてオリジナル問題。
 */
export const gapIIB: Problem[] = [
  {
    id: "GAP-II-B-01",
    conceptIds: ["II-08"],
    primaryConceptId: "II-08",
    title: "複素数の定義",
    prompt: "複素数の定義として正しいものは？",
    options: [
      "iを実数として√(−1)と計算する",
      "i²=−1を満たす新しい数を導入し、a+bi（a,bは実数）を複素数とする",
      "i²=1を満たす数を導入する",
      "実数a,bに対してa−biだけを複素数とする",
    ],
    answer: 1,
    explanation: "実数の範囲では√(−1)を定められないため、i²=−1を満たす数iを導入する。a+bi（a,bは実数）の形の数を複素数という。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "GAP-II-B-02",
    conceptIds: ["II-10"],
    primaryConceptId: "II-10",
    title: "複素数の絶対値",
    prompt: "z=3−4iの絶対値|z|は？",
    options: ["1", "5", "7", "25"],
    answer: 1,
    explanation: "z=a+biの絶対値は√(a²+b²)。したがって|3−4i|=√(3²+(−4)²)=√25=5。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "GAP-II-B-03",
    conceptIds: ["II-12"],
    primaryConceptId: "II-12",
    title: "三次方程式の解と係数",
    prompt: "x³−6x²+11x−6=0の3解をα,β,γとすると、α+β+γの値は？",
    options: ["3", "5", "6", "11"],
    answer: 2,
    explanation: "x³−S₁x²+S₂x−S₃=0の形では、解の和S₁はx²の係数の反対符号。よってα+β+γ=6。実際に解は1,2,3である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-II-B-04",
    conceptIds: ["II-13"],
    primaryConceptId: "II-13",
    title: "置換で次数を下げる",
    prompt: "x⁴−5x²+4=0の実数解の組は？",
    options: ["−2,−1,1,2", "−4,−1,1,4", "−2,2のみ", "−1,1のみ"],
    answer: 0,
    explanation: "t=x²と置くとt²−5t+4=(t−1)(t−4)=0。t=1,4より、x=±1,±2となる。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "GAP-II-B-05",
    conceptIds: ["II-15"],
    primaryConceptId: "II-15",
    title: "平方完成による不等式",
    prompt: "すべての実数xについてx²+4x+5≥1が成り立つ理由として最も適切なのは？",
    options: ["x²+4x+5=(x+2)²+1で、(x+2)²≥0だから", "x²+4x+5=(x−2)²−1で、(x−2)²≤0だから", "x²≥xなので常に成り立つから", "xの値を一つ選べば確認できるから"],
    answer: 0,
    explanation: "x²+4x+5=(x+2)²+1。平方は0以上なので、左辺は常に1以上になる。等号はx=−2のときに成り立つ。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-II-B-06",
    conceptIds: ["II-27"],
    primaryConceptId: "II-27",
    title: "距離の和の軌跡",
    prompt: "A(−3,0), B(3,0)とし、PA+PB=10を満たす点P(x,y)の軌跡は？",
    options: ["x²/16+y²/25=1", "x²/25+y²/16=1", "x²/9+y²/25=1", "x²/25−y²/16=1"],
    answer: 1,
    explanation: "2焦点からの距離の和が10なので楕円。長半径a=5、焦点距離c=3より短半径の2乗はb²=a²−c²=16。したがってx²/25+y²/16=1。",
    kind: "transfer",
    estimatedSeconds: 100,
  },
  {
    id: "GAP-II-B-07",
    conceptIds: ["II-28"],
    primaryConceptId: "II-28",
    title: "座標で直角を示す",
    prompt: "A(0,0), B(4,0), C(0,3)について、△ABCが直角三角形であることを座標から示す計算は？",
    options: ["AB²+BC²=AC²", "AB²+AC²=BC²", "AB+AC=BC", "ABとBCの傾きが等しい"],
    answer: 1,
    explanation: "距離公式からAB=4、AC=3、BC=5。したがってAB²+AC²=4²+3²=5²=BC²であり、Aが直角であることを示せる。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "GAP-II-B-08",
    conceptIds: ["II-37"],
    primaryConceptId: "II-37",
    title: "対数関数の逆関数",
    prompt: "関数y=log₂(x−1)+3の逆関数は？",
    options: ["y=2ˣ⁻³+1", "y=2ˣ⁺³−1", "y=log₂(x+1)−3", "y=3ˣ⁻²+1"],
    answer: 0,
    explanation: "xとyを入れ替えるとx=log₂(y−1)+3。よってx−3=log₂(y−1)からy−1=2ˣ⁻³、すなわちy=2ˣ⁻³+1。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-II-B-09",
    conceptIds: ["II-56"],
    primaryConceptId: "II-56",
    title: "三次関数の増減と極値",
    prompt: "f(x)=x³−3xのグラフについて正しい説明は？",
    options: ["x=−1で極小値−2、x=1で極大値2をとる", "x=−1で極大値2、x=1で極小値−2をとる", "すべての実数で単調増加する", "x=−1とx=1でどちらも極大値2をとる"],
    answer: 1,
    explanation: "f'(x)=3(x²−1)。x=−1では増加から減少、x=1では減少から増加に変わる。f(−1)=2、f(1)=−2なので、前者が極大、後者が極小。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-II-B-10",
    conceptIds: ["B-01"],
    primaryConceptId: "B-01",
    title: "数列の項と添字",
    prompt: "一般項aₙ=2n−1で表される数列の第4項a₄は？",
    options: ["5", "6", "7", "8"],
    answer: 2,
    explanation: "第4項はn=4を代入してa₄=2×4−1=7。添字nは何番目の項かを表す。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "GAP-II-B-11",
    conceptIds: ["B-05"],
    primaryConceptId: "B-05",
    title: "等比数列の項",
    prompt: "初項3、公比−2の等比数列の第4項は？",
    options: ["−24", "−12", "12", "24"],
    answer: 0,
    explanation: "等比数列の一般項はaₙ=a₁rⁿ⁻¹。よってa₄=3(−2)³=−24。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "GAP-II-B-12",
    conceptIds: ["B-11"],
    primaryConceptId: "B-11",
    title: "帰納法の次の段階",
    prompt: "1+2+…+n=n(n+1)/2を数学的帰納法で示す。n=kで成り立つと仮定した後、n=k+1の左辺を整理した式は？",
    options: ["k(k+1)/2+(k+1)=(k+1)(k+2)/2", "k(k+1)/2+k=(k+1)²/2", "(k+1)(k+2)/2+k=(k+2)(k+3)/2", "k(k+1)/2+(k+2)=(k+1)(k+2)/2"],
    answer: 0,
    explanation: "kまでの和に次の項k+1を足すので、k(k+1)/2+(k+1)=(k+1)(k+2)/2。これはn=k+1の形である。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "GAP-II-B-13",
    conceptIds: ["B-12"],
    primaryConceptId: "B-12",
    title: "不等式の帰納法",
    prompt: "n≥1で2ⁿ≥n+1を帰納法で証明する。2ᵏ≥k+1を仮定したとき、次の段階で必要な不等式は？",
    options: ["2ᵏ⁺¹=2·2ᵏ≥2(k+1)≥k+2", "2ᵏ⁺¹=2·2ᵏ≤2(k+1)≤k+2", "2ᵏ⁺¹=2ᵏ+1≥k+1", "2ᵏ⁺¹=2(k+1)=k+1"],
    answer: 0,
    explanation: "仮定から2ᵏ⁺¹=2·2ᵏ≥2(k+1)。さらにk≥1なので2(k+1)−(k+2)=k≥0、よって2(k+1)≥k+2となる。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "GAP-II-B-14",
    conceptIds: ["B-14"],
    primaryConceptId: "B-14",
    title: "確率変数の対応",
    prompt: "コインを2回投げ、Xを表が出た回数とする。このときXがとり得る値は？",
    options: ["0,1,2", "表,裏", "1/2だけ", "0,1,2,3"],
    answer: 0,
    explanation: "表が0回、1回、2回の場合があるので、確率変数Xの値は0,1,2。確率変数は結果に数値を対応させる変数である。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "GAP-II-B-15",
    conceptIds: ["B-22"],
    primaryConceptId: "B-22",
    title: "正規分布の範囲",
    prompt: "平均50、標準偏差10の正規分布に従うデータが、40以上60以下に入る確率として近いものは？",
    options: ["約0.16", "約0.34", "約0.68", "約0.95"],
    answer: 2,
    explanation: "40から60は平均50から±1標準偏差の範囲。正規分布ではこの範囲に入る確率は約0.68である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-II-B-16",
    conceptIds: ["B-24"],
    primaryConceptId: "B-24",
    title: "母集団と標本",
    prompt: "市全体の高校生の通学時間を調べるため、無作為に選んだ200人を調査した。母集団と標本の組み合わせは？",
    options: ["母集団は200人、標本は市全体の高校生", "母集団は市全体の高校生、標本は調査した200人", "母集団も標本も調査した200人", "母集団も標本も市全体の高校生"],
    answer: 1,
    explanation: "知りたい調査対象全体である市全体の高校生が母集団。その一部として実際に選んだ200人が標本である。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "GAP-II-B-17",
    conceptIds: ["B-25"],
    primaryConceptId: "B-25",
    title: "標本平均",
    prompt: "標本データ4,6,5,7,8の標本平均は？",
    options: ["5", "5.5", "6", "6.5"],
    answer: 2,
    explanation: "標本平均はデータの合計を個数で割る。 (4+6+5+7+8)/5=30/5=6。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "GAP-II-B-18",
    conceptIds: ["B-27"],
    primaryConceptId: "B-27",
    title: "母比率の点推定",
    prompt: "ある商品の購入経験を400人に尋ねたところ、216人が『ある』と答えた。母比率pの点推定値は？",
    options: ["0.216", "0.400", "0.540", "0.600"],
    answer: 2,
    explanation: "母比率pの点推定には標本比率を使う。標本比率は216/400=0.54なので、点推定値は0.540。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "GAP-II-B-19",
    conceptIds: ["B-29"],
    primaryConceptId: "B-29",
    title: "母比率の区間推定",
    prompt: "標本比率が0.60で、近似的な95%信頼区間の誤差幅を0.05とする。母比率pの区間推定は？",
    options: ["0.05≤p≤0.60", "0.55≤p≤0.65", "0.60≤p≤0.65", "0.50≤p≤0.70"],
    answer: 1,
    explanation: "区間推定は点推定値±誤差幅。したがって0.60±0.05より、0.55≤p≤0.65となる。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
];
