export type Math3Spec = {
  definition: string;
  firstMove: string;
  trap: string;
  workedProblem: string;
  workedSteps: string[];
  workedAnswer: string;
  quickProblem: string;
  quickAnswer: string;
  quickExplanation: string;
  transferProblem: string;
  transferAnswer: string;
  transferExplanation: string;
};

/**
 * 数学IIIの独立教材仕様。
 * 各概念は「意味→最初の一手→途中式→確認→転用」の順で記述する。
 * 数値だけを変える共通テンプレートではなく、極限・微分・積分の技法を分ける。
 */
export const math3Specs: Record<string, Math3Spec> = {
  "III-01": {
    definition: "数列の極限は、番号nを大きくしたときに項a_nが近づく値。有限回の計算で到達する値ではなく、近づき方を表す。",
    firstMove: "nを大きくしたときに残る項と、0へ消える項を分ける。",
    trap: "nに適当な大きい数を代入した結果を極限だと思う。",
    workedProblem: "a_n=3+2/nの極限を求めよ。",
    workedSteps: ["n→∞では2/n→0。", "したがってa_n=3+2/n→3+0。", "近づく値は3であり、nが有限のときの項は3そのものではない。"],
    workedAnswer: "3",
    quickProblem: "a_n=5−1/nの極限は？",
    quickAnswer: "5",
    quickExplanation: "1/nが0へ近づくため、5−1/nは5へ近づく。",
    transferProblem: "初項から単調に増え、上限が4である数列の極限として最も自然な値は？",
    transferAnswer: "4",
    transferExplanation: "上限へ近づくという情報から、極限候補は4。ただし単調性と上に有界である根拠は別に確認する。",
  },
  "III-02": {
    definition: "収束する数列では、和・差・積の極限をそれぞれの極限の演算へ分解できる。商は分母の極限が0でないときに限る。",
    firstMove: "各数列の極限を別々に求め、最後に演算する。",
    trap: "分母の極限が0でも、極限の商の公式をそのまま使う。",
    workedProblem: "a_n→2、b_n→−3のとき、a_n^2+2b_nの極限を求めよ。",
    workedSteps: ["a_n→2よりa_n²→4。", "2b_n→2×(−3)=−6。", "和の極限は4−6=−2。"],
    workedAnswer: "−2",
    quickProblem: "a_n→4、b_n→2のとき、a_n/b_nの極限は？",
    quickAnswer: "2",
    quickExplanation: "分母の極限2は0でないので、極限の商は4/2=2。",
    transferProblem: "a_n→0、b_n→0のとき、a_n/b_nの極限が与えられた情報だけで決まるか？",
    transferAnswer: "決まらない",
    transferExplanation: "0/0型は近づき方に依存する。a_n=b_nなら1、a_n=2b_nなら2となる。",
  },
  "III-03": {
    definition: "無限等比級数は、初項a、公比rの項を無限に足したもの。|r|<1なら項が0へ近づき、和a/(1−r)を持つ。",
    firstMove: "初項・公比・収束条件|r|<1を確認する。",
    trap: "|r|≥1でも公式a/(1−r)を使う。",
    workedProblem: "3+3/2+3/4+…の和を求めよ。",
    workedSteps: ["初項a=3、公比r=1/2。", "|r|=1/2<1なので収束する。", "和はa/(1−r)=3/(1−1/2)=6。"],
    workedAnswer: "6",
    quickProblem: "1+1/3+1/9+…の和は？",
    quickAnswer: "3/2",
    quickExplanation: "a=1、r=1/3なので1/(1−1/3)=3/2。",
    transferProblem: "無限等比級数が収束するための公比rの条件は？",
    transferAnswer: "|r|<1",
    transferExplanation: "項が0へ近づき、部分和が一定値へ近づく条件が|r|<1。",
  },
  "III-04": {
    definition: "漸化式の極限は、隣り合う項の関係から候補を作り、実際に収束するかを別途確かめる。",
    firstMove: "極限をLと仮定して漸化式へ代入し、候補Lを出す。",
    trap: "極限候補の方程式を解いただけで、必ず収束すると判断する。",
    workedProblem: "a_1=0、a_(n+1)=(a_n+2)/2の極限を求めよ。",
    workedSteps: ["収束してLになるならL=(L+2)/2。", "2L=L+2よりL=2。", "a_nは2との差を半分にするので、0から始めても2へ近づく。"],
    workedAnswer: "2",
    quickProblem: "a_(n+1)=a_n/3、a_1=9の極限は？",
    quickAnswer: "0",
    quickExplanation: "a_n=9(1/3)^(n−1)で、公比の絶対値が1未満だから0へ収束する。",
    transferProblem: "極限候補の方程式に複数の解が出たとき、追加で必要な確認は？",
    transferAnswer: "数列の有界性・単調性・初項との関係",
    transferExplanation: "候補が複数ある場合、実際の数列がどの範囲にあり、どちらへ近づくかを確認する。",
  },
  "III-05": {
    definition: "関数の極限は、xがある値へ近づくときf(x)が近づく値。x=aでの関数値と別物の場合もある。",
    firstMove: "代入できるなら代入し、0/0などになったら因数分解や約分を試す。",
    trap: "x=aで定義されていないことだけで極限も存在しないと決める。",
    workedProblem: "lim[x→2](x²+1)を求めよ。",
    workedSteps: ["多項式は連続なので、そのままx=2を代入できる。", "2²+1=5。", "したがって極限は5。"],
    workedAnswer: "5",
    quickProblem: "lim[x→−1](x²+3x)は？",
    quickAnswer: "−2",
    quickExplanation: "多項式なので代入し、1−3=−2。",
    transferProblem: "f(a)が定義されていなくてもlim[x→a]f(x)が存在する例は？",
    transferAnswer: "(x²−a²)/(x−a)（x≠a）",
    transferExplanation: "x≠aではx+aに等しく、x→aで2aへ近づく。点の値がなくても周囲の近づき方は定まる。",
  },
  "III-06": {
    definition: "片側極限は左側・右側から近づく挙動を分けて見る。両側極限は左右の値が一致するときだけ存在する。",
    firstMove: "x→a−とx→a+を別々に調べる。分母や符号の変化を確認する。",
    trap: "右極限だけを見て両側極限があるとする。",
    workedProblem: "lim[x→0+]1/xとlim[x→0−]1/xを求めよ。",
    workedSteps: ["x→0+では正の小さい数なので1/x→+∞。", "x→0−では負の小さい数なので1/x→−∞。", "左右が一致しないので、有限な両側極限は存在しない。"],
    workedAnswer: "右:+∞、左:−∞、両側は存在しない",
    quickProblem: "lim[x→2+]1/(x−2)は？",
    quickAnswer: "+∞",
    quickExplanation: "右側からは分母が正の小さい数になるため、値は正の無限大へ発散する。",
    transferProblem: "左右の片側極限が異なるとき、両側極限は？",
    transferAnswer: "存在しない",
    transferExplanation: "両側極限は左右から同じ値へ近づくことが必要。",
  },
  "III-07": {
    definition: "x=aで連続とは、f(a)が定義され、lim[x→a]f(x)が存在し、その値がf(a)に等しいこと。",
    firstMove: "極限・関数値・一致の3点を順に確認する。",
    trap: "式が同じ形に見えるだけで、定義域や穴を確認しない。",
    workedProblem: "f(x)=(x²−1)/(x−1) (x≠1)、f(1)=2はx=1で連続か。",
    workedSteps: ["x≠1ではf(x)=x+1。", "lim[x→1]f(x)=2。", "f(1)=2と一致するので連続。"],
    workedAnswer: "連続",
    quickProblem: "f(x)=x²はx=−2で連続か？",
    quickAnswer: "連続",
    quickExplanation: "多項式はすべての実数で連続。極限も関数値も4。",
    transferProblem: "連続性を使うと、区間の両端で符号が異なる関数について何が言えるか？",
    transferAnswer: "区間内に少なくとも1つ零点がある",
    transferExplanation: "連続関数の中間値の性質により、正から負へ移る途中で0を通る。",
  },
  "III-08": {
    definition: "sin x/xの極限は、角度をラジアンで測ったとき1。三角関数の微分の基礎になる。",
    firstMove: "角度の単位がラジアンか確認し、既知の基本極限へ形を合わせる。",
    trap: "度数法のままsin x/x→1を使う。",
    workedProblem: "lim[x→0] sin(3x)/xを求めよ。",
    workedSteps: ["sin(3x)/x=3・sin(3x)/(3x)。", "3x→0なのでsin(3x)/(3x)→1。", "よって極限は3。"],
    workedAnswer: "3",
    quickProblem: "lim[x→0]sin(5x)/(5x)は？",
    quickAnswer: "1",
    quickExplanation: "基本極限sin u/u→1でu=5xと置けばよい。",
    transferProblem: "lim[x→0](1−cos x)/x²を求めよ。",
    transferAnswer: "1/2",
    transferExplanation: "1−cos x=2sin²(x/2)を使い、sin u/uの基本極限へ変形すると1/2。",
  },
  "III-09": {
    definition: "指数・対数関数の極限は、底の大小や対数の増え方を見て、0・有限値・無限大を判断する。",
    firstMove: "底が0<a<1か、a>1かを確認し、指数の向きと対数の定義域を見る。",
    trap: "a^xのx→∞の挙動を、底が1より大きい場合と小さい場合で区別しない。",
    workedProblem: "lim[x→∞]2^(−x)とlim[x→∞]log_2 xを求めよ。",
    workedSteps: ["2^(−x)=(1/2)^xで、0<1/2<1だから0へ近づく。", "log_2 xはxが増えるとゆっくり増え続ける。", "したがって前者は0、後者は+∞。"],
    workedAnswer: "0、+∞",
    quickProblem: "lim[x→∞](1/3)^xは？",
    quickAnswer: "0",
    quickExplanation: "底が0と1の間なので、指数が増えるほど0へ近づく。",
    transferProblem: "lim[x→∞]ln x/xの値は？",
    transferAnswer: "0",
    transferExplanation: "対数の増加はxの一次増加より遅い。必要ならロピタルの形ではなく増加率の比較で考える。",
  },
  "III-10": {
    definition: "不定形は、代入した結果だけでは極限が決まらない形。式変形して既知の極限へ戻す。",
    firstMove: "0/0、∞/∞などを確認し、因数分解・有理化・最高次数で割る。",
    trap: "0/0を0、∞/∞を1としてしまう。",
    workedProblem: "lim[x→0](√(1+x)−1)/xを求めよ。",
    workedSteps: ["分子を有理化し、分母分子に√(1+x)+1を掛ける。", "分子はxになり、x/[(x)(√(1+x)+1)]=1/[√(1+x)+1]。", "x→0を代入して1/2。"],
    workedAnswer: "1/2",
    quickProblem: "lim[x→1](x²−1)/(x−1)は？",
    quickAnswer: "2",
    quickExplanation: "x²−1=(x−1)(x+1)と因数分解して約分し、x+1へ戻す。",
    transferProblem: "分子分母がともに0へ近づく極限で最初に試す変形は？",
    transferAnswer: "因数分解または有理化",
    transferExplanation: "共通因子を消す、または根号を外して既知の極限へ形を整える。",
  },
  "III-11": {
    definition: "漸近線は、グラフが無限遠や特定のxで限りなく近づく直線。極限で判定する。",
    firstMove: "分母が0になるxと、x→±∞での最高次数を調べる。",
    trap: "定義域にないxの値を、グラフが通る点として描く。",
    workedProblem: "y=(2x+1)/(x−3)の垂直・水平漸近線を求めよ。",
    workedSteps: ["分母が0となるx=3で、分子は0でないため垂直漸近線x=3。", "分子分母をxで割ると(2+1/x)/(1−3/x)。", "x→±∞で2へ近づくので水平漸近線y=2。"],
    workedAnswer: "x=3、y=2",
    quickProblem: "y=1/(x+2)の垂直漸近線は？",
    quickAnswer: "x=−2",
    quickExplanation: "分母が0になるx=−2で値が発散する。",
    transferProblem: "分子と分母が同じ次数の有理関数の水平漸近線は、何で決まるか？",
    transferAnswer: "最高次係数の比",
    transferExplanation: "xで割ってx→∞とすると、低次項は0になり最高次係数の比だけが残る。",
  },
  "III-12": {
    definition: "関数の概形は、定義域・対称性・極限・切片・増減を組み合わせて全体像を描く。",
    firstMove: "定義域と端の挙動を先に確定し、次に微分で増減を調べる。",
    trap: "数点をプロットしただけで、漸近線や定義域外の形を決める。",
    workedProblem: "f(x)=1/(x²+1)の概形を説明せよ。",
    workedSteps: ["定義域は全実数、f(−x)=f(x)なのでy軸対称。", "f(0)=1、x→±∞で0へ近づく。", "f'(x)=−2x/(x²+1)²よりx<0で増加、x>0で減少。"],
    workedAnswer: "y軸対称で(0,1)が最大、両端でy=0へ近づく",
    quickProblem: "偶関数のグラフが持つ対称性は？",
    quickAnswer: "y軸対称",
    quickExplanation: "f(−x)=f(x)なら左右のxを入れ替えても値が同じ。",
    transferProblem: "概形を描くとき、微分以外に必ず確認すべき情報を2つ挙げよ。",
    transferAnswer: "定義域と極限（漸近線）",
    transferExplanation: "描ける範囲と端での近づき方が決まらないと、増減だけではグラフ全体を決められない。",
  },
  "III-13": {
    definition: "連鎖律は、外側の変化率に内側の変化率を掛ける微分法。合成関数を一段ずつほどく。",
    firstMove: "外側の関数uと内側u(x)を分ける。",
    trap: "内側の微分を掛け忘れ、外側だけを微分する。",
    workedProblem: "y=(3x²+1)^5を微分せよ。",
    workedSteps: ["u=3x²+1と置くとy=u^5。", "dy/du=5u^4、du/dx=6x。", "積を取り、dy/dx=30x(3x²+1)^4。"],
    workedAnswer: "30x(3x²+1)^4",
    quickProblem: "d/dx(2x+1)^4は？",
    quickAnswer: "8(2x+1)^3",
    quickExplanation: "外側の4乗を微分した4(2x+1)^3に、内側の微分2を掛ける。",
    transferProblem: "合成関数の微分で、外側と内側のどちらを先に微分するか？",
    transferAnswer: "外側を微分してから内側の微分を掛ける",
    transferExplanation: "dy/duとdu/dxを掛けてdy/dxにする。",
  },
  "III-14": {
    definition: "積の微分は(fg)'=f'g+fg'、商の微分は(f/g)'=(f'g−fg')/g²。積・商を一つの塊として扱わない。",
    firstMove: "積か商かを見分け、fとgを明示して公式へ代入する。",
    trap: "積をf'g'と微分したり、分子だけを微分して分母を残す。",
    workedProblem: "y=x²e^xを微分せよ。",
    workedSteps: ["f=x²、g=e^xと置く。", "f'=2x、g'=e^x。", "y'=2xe^x+x²e^x=e^x(x²+2x)。"],
    workedAnswer: "e^x(x²+2x)",
    quickProblem: "d/dx[x sin x]は？",
    quickAnswer: "sin x+x cos x",
    quickExplanation: "積の微分で、xの微分×sin x＋x×sin xの微分。",
    transferProblem: "商の微分で分母に現れる因子は？",
    transferAnswer: "分母の二乗",
    transferExplanation: "(f/g)'の分母はg²。符号はf'g−fg'の順に固定する。",
  },
  "III-15": {
    definition: "三角関数の導関数は、sin x→cos x、cos x→−sin x、tan x→1/cos²x。中身がkxなら連鎖律も使う。",
    firstMove: "基本公式と、角度の中身の微分を分けて書く。",
    trap: "cos xの微分のマイナスを落とす。",
    workedProblem: "y=sin(2x)を微分せよ。",
    workedSteps: ["外側sin uの微分はcos u。", "内側u=2xの微分は2。", "よってy'=2cos(2x)。"],
    workedAnswer: "2cos(2x)",
    quickProblem: "d/dx cos xは？",
    quickAnswer: "−sin x",
    quickExplanation: "cosの導関数は−sin。符号を必ず含める。",
    transferProblem: "d/dx tan(3x)を求めよ。",
    transferAnswer: "3/cos²(3x)",
    transferExplanation: "tan uの微分1/cos²uに、u=3xの微分3を掛ける。",
  },
  "III-16": {
    definition: "指数関数の微分は(a^x)'=a^x ln a（a>0, a≠1）、自然対数の微分は(ln x)'=1/x（x>0）。合成関数では連鎖律を使う。",
    firstMove: "底と真数を確認し、lnかa^xかを基本公式に対応させる。",
    trap: "(a^x)'をxa^(x−1)としてしまう。これは多項式の公式ではない。",
    workedProblem: "y=ln(2x+1)を微分せよ。",
    workedSteps: ["u=2x+1と置く。", "d(ln u)/du=1/u、du/dx=2。", "よってy'=2/(2x+1)。"],
    workedAnswer: "2/(2x+1)",
    quickProblem: "d/dx 3^xは？",
    quickAnswer: "3^x ln 3",
    quickExplanation: "指数関数の微分では底の自然対数が掛かる。",
    transferProblem: "a>0、a≠1、x>0の範囲で d/dx log_a xを求めよ。",
    transferAnswer: "1/(x ln a)",
    transferExplanation: "底の条件a>0,a≠1と真数条件x>0のもとで、log_a x=ln x/ln aと変換して微分する。",
  },
  "III-17": {
    definition: "逆関数のグラフはy=xに関して対称で、逆関数の傾きは元の関数の傾きの逆数になる。",
    firstMove: "対応する点を元の関数上に置き、元の導関数の値を計算する。",
    trap: "逆関数の値と導関数の逆数を混同する。",
    workedProblem: "f(x)=x³の逆関数gについて、g'(8)を求めよ。",
    workedSteps: ["g(8)=2なので、元の点は(2,8)。", "f'(x)=3x²よりf'(2)=12。", "逆関数の傾きはその逆数なのでg'(8)=1/12。"],
    workedAnswer: "1/12",
    quickProblem: "f'(a)=5で、逆関数の対応点が存在するときg'(f(a))は？",
    quickAnswer: "1/5",
    quickExplanation: "対応する接線の傾きは逆数になる。",
    transferProblem: "逆関数のグラフが対称になる直線は？",
    transferAnswer: "y=x",
    transferExplanation: "xとyを入れ替える操作が逆関数に対応する。",
  },
  "III-18": {
    definition: "陰関数の微分は、xとyの関係式をxで微分してdy/dxを解く。媒介変数ではdy/dx=(dy/dt)/(dx/dt)。",
    firstMove: "yをxの関数として扱い、yを微分する項にはdy/dxを付ける。",
    trap: "yを定数のように微分してdy/dxを落とす。",
    workedProblem: "x²+y²=25上の点(3,4)での接線の傾きを求めよ。",
    workedSteps: ["xで微分すると2x+2y(dy/dx)=0。", "dy/dx=−x/y。", "(3,4)を代入して傾き−3/4。"],
    workedAnswer: "−3/4",
    quickProblem: "x=t²、y=t³のとき（t≠0）、dy/dxを求めよ。",
    quickAnswer: "3t/2（t≠0）",
    quickExplanation: "dy/dt=3t²、dx/dt=2tなので比を取る。",
    transferProblem: "媒介変数表示でdx/dt=0の点では、通常のdy/dxをどう扱うか？",
    transferAnswer: "その点では比が定義できるか別途調べる",
    transferExplanation: "分母が0なので公式をそのまま使えない。接線が鉛直などの可能性を確認する。",
  },
  "III-19": {
    definition: "高階導関数は導関数をさらに微分したもの。二階導関数は速度の変化やグラフの曲がり方を表す。",
    firstMove: "一階、二階と順番に微分し、各導関数の意味を分ける。",
    trap: "二階導関数をf(x)の二乗と読む。",
    workedProblem: "f(x)=x^4のf''(1)を求めよ。",
    workedSteps: ["f'(x)=4x³。", "f''(x)=12x²。", "x=1を代入して12。"],
    workedAnswer: "12",
    quickProblem: "f(x)=sin xのf''(x)は？",
    quickAnswer: "−sin x",
    quickExplanation: "一回でcos x、二回で−sin x。",
    transferProblem: "位置s(t)を二回微分すると何を表すか？",
    transferAnswer: "加速度",
    transferExplanation: "s'(t)が速度、s''(t)が速度の変化率である加速度。",
  },
  "III-20": {
    definition: "導関数の値はその点での接線の傾き。一階導関数の符号は増減、二階導関数の符号は曲がり方の手掛かりになる。",
    firstMove: "求めたいのが傾き・増減・凹凸のどれかを特定する。",
    trap: "f'(a)=0を必ず極値だと判断する。",
    workedProblem: "f(x)=x³−3xのx=0における接線の傾きを求めよ。",
    workedSteps: ["f'(x)=3x²−3。", "f'(0)=−3。", "したがって接線の傾きは−3。"],
    workedAnswer: "−3",
    quickProblem: "f'(x)>0の区間で、fはどう変化するか？",
    quickAnswer: "増加する",
    quickExplanation: "接線の傾きが正なら、xが増えたときf(x)も増える。",
    transferProblem: "f'(a)=0だが極値でない例の特徴は？",
    transferAnswer: "前後でf'の符号が変わらない",
    transferExplanation: "増加から減少、または減少から増加へ変わらなければ極値とは限らない。",
  },
  "III-21": {
    definition: "曲線上の点で接線は導関数の傾きを持つ直線。接線の傾きが有限かつ0でないとき、法線の傾きとの積は−1。水平接線の法線は垂直線になる。",
    firstMove: "点の座標と接線の傾きを求め、傾きが0なら法線は垂直線、それ以外なら積が−1となる点傾き式へ入れる。",
    trap: "接線の傾きと法線の傾きを同じにする。",
    workedProblem: "y=x²のx=1での接線と法線を求めよ。",
    workedSteps: ["点は(1,1)、導関数はy'=2xなので接線の傾き2。", "接線y−1=2(x−1)よりy=2x−1。", "法線の傾きは−1/2で、y−1=−(x−1)/2。"],
    workedAnswer: "接線y=2x−1、法線y=−x/2+3/2",
    quickProblem: "y=x³のx=1での接線の傾きは？",
    quickAnswer: "3",
    quickExplanation: "y'=3x²にx=1を代入する。",
    transferProblem: "接線が水平になる点の条件は？",
    transferAnswer: "f'(x)=0",
    transferExplanation: "水平な直線の傾きは0。候補点なので、極値かどうかは符号変化も見る。",
  },
  "III-22": {
    definition: "増減表は導関数の符号を区間ごとに調べ、臨界点を境に関数の動きを整理する方法。",
    firstMove: "定義域内でf'(x)=0または未定義となる点を列挙する。",
    trap: "導関数の零点だけを求め、区間の符号を調べない。",
    workedProblem: "f(x)=x³−3xの極値を求めよ。",
    workedSteps: ["f'(x)=3(x−1)(x+1)。臨界点は−1,1。", "f'はx<−1で正、−1<x<1で負、x>1で正。", "x=−1で極大f=2、x=1で極小f=−2。"],
    workedAnswer: "極大値2、極小値−2",
    quickProblem: "f'(x)>0の区間でfは？",
    quickAnswer: "単調増加",
    quickExplanation: "導関数が正なら接線の傾きが正で、関数は増加する。",
    transferProblem: "閉区間で最大・最小を求めるとき、臨界点以外に調べる点は？",
    transferAnswer: "両端点",
    transferExplanation: "閉区間の絶対最大・最小は、臨界点と端点の値を比較して決める。",
  },
  "III-23": {
    definition: "二階導関数の符号はグラフの凹凸を表す。f''の符号が変わる点が変曲点の候補。",
    firstMove: "f''を求め、零点・未定義点の前後で符号を調べる。",
    trap: "f''(a)=0だけで変曲点と断定する。",
    workedProblem: "f(x)=x³−3xの変曲点を求めよ。",
    workedSteps: ["f'(x)=3x²−3、f''(x)=6x。", "f''=0よりx=0。", "前後でf''の符号が負から正へ変わるので、f(0)=0と合わせて(0,0)。"],
    workedAnswer: "(0,0)",
    quickProblem: "f''(x)>0の区間の凹凸は？",
    quickAnswer: "下に凸",
    quickExplanation: "接線の傾きが増えていくため、グラフは下に凸になる。",
    transferProblem: "f''の符号が前後で変わらない点は、f''=0でも何とは限らないか？",
    transferAnswer: "変曲点とは限らない",
    transferExplanation: "凹凸が切り替わることが変曲点の条件で、零点だけでは不十分。",
  },
  "III-24": {
    definition: "総合的なグラフ描画は、定義域・対称性・切片・極限・増減・凹凸を一枚に統合する。",
    firstMove: "定義域と対称性、端の極限を先に書いてから微分する。",
    trap: "増減表だけで漸近線や定義域外の部分まで描いた気になる。",
    workedProblem: "f(x)=(x²−1)/(x²+1)のグラフの特徴を挙げよ。",
    workedSteps: ["定義域は全実数、偶関数なのでy軸対称。", "f(0)=−1、x→±∞で1へ近づく。", "f'(x)=4x/(x²+1)²より、x<0で減少、x>0で増加。"],
    workedAnswer: "y軸対称、(0,−1)で最小、水平漸近線y=1",
    quickProblem: "f(−x)=f(x)を満たす関数の対称性は？",
    quickAnswer: "y軸対称",
    quickExplanation: "左右のxで同じ値なので、y軸を軸に重なる。",
    transferProblem: "グラフの端の形を確定する主な計算は？",
    transferAnswer: "x→端点・±∞の極限",
    transferExplanation: "微分は局所的な増減を与え、極限は端でどこへ近づくかを与える。",
  },
  "III-25": {
    definition: "微分による最適化は、条件を一つの変数の関数に直し、臨界点と境界を比較する。",
    firstMove: "目的量をxの関数にし、定義域と境界を決める。",
    trap: "f'(x)=0の点だけを調べ、端点や実行可能範囲を無視する。",
    workedProblem: "周長20の長方形の面積を最大にせよ。",
    workedSteps: ["一辺をx、他方を10−xとすると面積S=x(10−x)。", "S'=10−2x=0よりx=5。", "0<x<10でSは最大になり、面積は25。"],
    workedAnswer: "正方形5×5、最大面積25",
    quickProblem: "S(x)=x(10−x)の最大値を与えるxは？",
    quickAnswer: "5",
    quickExplanation: "S'=10−2x=0からx=5。",
    transferProblem: "最適化でf'(x)=0の候補と必ず比較する値は？",
    transferAnswer: "定義域の端点・境界",
    transferExplanation: "実行可能範囲が閉じている場合、最大・最小は端点で起こることもある。",
  },
  "III-26": {
    definition: "位置をs(t)とすると、速度v=s'、加速度a=v'=s''。微分の階層を単位とともに読む。",
    firstMove: "与えられた式が位置・速度・加速度のどれかを確認する。",
    trap: "速度を位置の値、加速度を速度の値と混同する。",
    workedProblem: "s(t)=t³−3tのt=2における速度と加速度を求めよ。",
    workedSteps: ["v(t)=s'(t)=3t²−3。", "a(t)=v'(t)=6t。", "t=2でv=9、a=12。"],
    workedAnswer: "速度9、加速度12",
    quickProblem: "s(t)=t²の速度v(t)は？",
    quickAnswer: "2t",
    quickExplanation: "位置を時間で微分すると速度になる。",
    transferProblem: "速度が負の区間で、位置はどう変化するか？",
    transferAnswer: "時間とともに減少する",
    transferExplanation: "速度は位置の変化率なので、負なら位置が小さくなる。",
  },
  "III-27": {
    definition: "平均値の定理は、区間全体の平均変化率と同じ瞬間変化率を持つ点が区間内に存在するという関係。",
    firstMove: "両端の値から平均変化率を計算し、f'(c)と等しいと置く。",
    trap: "その点cが必ず区間の中央だと思う。",
    workedProblem: "f(x)=x²を[0,1]で考え、平均変化率と一致する点cを求めよ。",
    workedSteps: ["平均変化率は(f(1)−f(0))/(1−0)=1。", "f'(x)=2xなので2c=1。", "c=1/2で一致する。"],
    workedAnswer: "c=1/2",
    quickProblem: "平均変化率の式は？",
    quickAnswer: "[f(b)−f(a)]/(b−a)",
    quickExplanation: "両端の出力差を入力差で割る。",
    transferProblem: "平均値の定理を使うために、区間内で必要な関数の性質は？",
    transferAnswer: "連続、開区間内で微分可能",
    transferExplanation: "端点を含む閉区間で連続、内部で微分可能という条件が必要。",
  },
  "III-28": {
    definition: "微分で不等式・方程式を考察すると、関数の増減や極値から解の個数と大小を判定できる。",
    firstMove: "左右を移項してf(x)=0またはf(x)≧0の形にし、f'の符号を見る。",
    trap: "計算で根を直接求められないと何も言えないと思う。",
    workedProblem: "f(x)=x³+x+1=0が実数解を1個だけ持つことを示せ。",
    workedSteps: ["f'(x)=3x²+1>0なのでfは全実数で単調増加。", "単調増加関数はx軸と高々1回しか交わらない。", "x→−∞でf→−∞、x→∞でf→∞なので、連続性から1回は交わる。"],
    workedAnswer: "実数解は1個",
    quickProblem: "f'(x)>0が全域で成り立つとき、f=0の解は何個までか？",
    quickAnswer: "高々1個",
    quickExplanation: "単調増加なので同じ値0を二度取れない。",
    transferProblem: "関数の最小値が正なら、f(x)=0の実数解は？",
    transferAnswer: "存在しない",
    transferExplanation: "すべてのxでf(x)>0なので、0と交わらない。",
  },
  "III-29": {
    definition: "不定積分は微分すると元の関数になる関数の族。最後に必ず積分定数Cを付ける。",
    firstMove: "各項を微分公式の逆向きに積分し、定数項を確認する。",
    trap: "x^nを積分して指数を変えず、Cを書き忘れる。",
    workedProblem: "∫(3x²−2sin x+e^x)dxを求めよ。",
    workedSteps: ["3x²の積分はx³。", "−2sin xの積分は2cos x。e^xの積分はe^x。", "まとめてx³+2cos x+e^x+C。"],
    workedAnswer: "x³+2cos x+e^x+C",
    quickProblem: "∫2x dxは？",
    quickAnswer: "x²+C",
    quickExplanation: "x²を微分すると2xになる。",
    transferProblem: "不定積分の答えが複数ある理由は？",
    transferAnswer: "微分すると消える定数が任意だから",
    transferExplanation: "Cが何であっても微分すれば0になり、同じ被積分関数へ戻る。",
  },
  "III-30": {
    definition: "置換積分は、内側の関数とその微分が見える積分を新しい文字uへ置き換える方法。",
    firstMove: "まとまりuとduが同時に現れるかを探す。",
    trap: "uだけを置き換え、dxやduの変換を忘れる。",
    workedProblem: "∫2x cos(x²)dxを求めよ。",
    workedSteps: ["u=x²と置くとdu=2x dx。", "積分は∫cos u du=sin u+C。", "uを戻してsin(x²)+C。"],
    workedAnswer: "sin(x²)+C",
    quickProblem: "∫6x(3x²+1)^4dxは？",
    quickAnswer: "(3x²+1)^5/5+C",
    quickExplanation: "u=3x²+1、du=6x dxと置く。",
    transferProblem: "置換積分でduが定数倍しか一致しないときは？",
    transferAnswer: "定数倍を外へ出して調整する",
    transferExplanation: "du=k・g(x)dxなら、kを係数として補正して置換する。",
  },
  "III-31": {
    definition: "部分積分は∫u dv=uv−∫v du。積の一方を微分し、他方を積分して積分を簡単にする。",
    firstMove: "微分すると簡単になるuと、積分しやすいdvを選ぶ。",
    trap: "uとdvの選び方を逆にして、同じ難しさの積分へ戻る。",
    workedProblem: "∫x e^x dxを求めよ。",
    workedSteps: ["u=x、dv=e^x dxと置くとdu=dx、v=e^x。", "公式よりxe^x−∫e^x dx。", "答えはe^x(x−1)+C。"],
    workedAnswer: "e^x(x−1)+C",
    quickProblem: "部分積分の公式は？",
    quickAnswer: "∫u dv=uv−∫v du",
    quickExplanation: "積の微分を積分した形を逆に使う。",
    transferProblem: "∫ln x dxで部分積分するとき、uに選ぶのは？",
    transferAnswer: "ln x",
    transferExplanation: "ln xは微分すると1/xになり、dv=dxは簡単に積分できる。",
  },
  "III-32": {
    definition: "分数関数の積分では、分母の因数へ分解し、部分分数に分けて基本積分へ戻す。",
    firstMove: "分子の次数と分母の因数分解を確認する。",
    trap: "分子分母を別々に積分できると思う。",
    workedProblem: "∫1/(x²−1)dxを求めよ。",
    workedSteps: ["x²−1=(x−1)(x+1)。", "1/(x²−1)=1/2[1/(x−1)−1/(x+1)]。", "積分して(1/2)ln|(x−1)/(x+1)|+C。"],
    workedAnswer: "(1/2)ln|(x−1)/(x+1)|+C",
    quickProblem: "1/(x(x+1))を部分分数にすると？",
    quickAnswer: "1/x−1/(x+1)",
    quickExplanation: "1/x−1/(x+1)=(x+1−x)/(x(x+1))。",
    transferProblem: "部分分数分解の目的は？",
    transferAnswer: "基本的な1/(x−a)型へ分けること",
    transferExplanation: "対数積分へ直結する単純な分数の和に変形する。",
  },
  "III-33": {
    definition: "三角関数の積分は、恒等式で積を和や平方へ変形し、基本積分・置換へつなぐ。",
    firstMove: "sin²、cos²、sin x cos xなどの形を恒等式で見直す。",
    trap: "sin²xを(sin x)^2のまま、sin xの積分公式だけで処理しようとする。",
    workedProblem: "∫sin²x dxを求めよ。",
    workedSteps: ["sin²x=(1−cos2x)/2。", "項別に積分してx/2−sin2x/4+C。", "微分してsin²xへ戻ることを確認する。"],
    workedAnswer: "x/2−sin(2x)/4+C",
    quickProblem: "sin x cos xを2倍角で表すと？",
    quickAnswer: "sin(2x)/2",
    quickExplanation: "sin2x=2sin x cos xを使う。",
    transferProblem: "sin^m x cos^n xの積分で、片方の指数が奇数のときの基本方針は？",
    transferAnswer: "奇数の因子を1つ残し、残りを1−sin²xまたは1−cos²xへ変える",
    transferExplanation: "残した因子を置換の微分に対応させる。",
  },
  "III-34": {
    definition: "指数・対数を含む積分では、微分が内側にあるか、部分積分で対数を微分できるかを判断する。ln xやlog_a xは真数x>0（さらにlog_aではa>0,a≠1）の範囲で扱う。",
    firstMove: "定義域を先に確認し、e^{g(x)}のg'、またはln xの微分1/xを探す。",
    trap: "ln xをそのまま積分してln²x/2とする。",
    workedProblem: "∫ln x dxを求めよ。",
    workedSteps: ["u=ln x、dv=dxとする。", "du=dx/x、v=x。", "部分積分よりxln x−∫1dx=xln x−x+C。"],
    workedAnswer: "xln x−x+C",
    quickProblem: "∫e^(2x)dxは？",
    quickAnswer: "e^(2x)/2+C",
    quickExplanation: "内側2xの微分2を補正する。",
    transferProblem: "∫x e^(x²)dxで適切な置換は？",
    transferAnswer: "u=x²",
    transferExplanation: "du=2x dxが含まれているので、指数の中身を置換する。",
  },
  "III-35": {
    definition: "定積分は区間の向き・分割・線形性を使って、同じ面積や変化量を短く計算できる。",
    firstMove: "区間の対称性、奇偶性、分割点を確認する。",
    trap: "積分区間の向きを反転しても符号が変わらないと思う。",
    workedProblem: "∫[−1,1](x²+x+1)dxを求めよ。",
    workedSteps: ["xは奇関数なので−1から1の積分は0。", "x²+1の積分だけを計算する。", "2/3+2=8/3。"],
    workedAnswer: "8/3",
    quickProblem: "∫[a,b]f(x)dxを∫[b,a]へ向きを変えると？",
    quickAnswer: "−∫[a,b]f(x)dx",
    quickExplanation: "積分区間の向きを反転すると符号が反転する。",
    transferProblem: "偶関数fの∫[−a,a]f(x)dxは？",
    transferAnswer: "2∫[0,a]f(x)dx",
    transferExplanation: "左右の面積・符号付き面積が等しいため、片側の2倍。",
  },
  "III-36": {
    definition: "微積分の基本定理は、積分で蓄積した量を微分すると、元の被積分関数に戻るという接続。",
    firstMove: "上端がxとして動く積分なら、微分の基本定理を直接使う。",
    trap: "積分変数tと上端xを同じ変数として混同する。",
    workedProblem: "F(x)=∫[0,x](t²+1)dtのF'(x)を求めよ。",
    workedSteps: ["積分の上端がxで、被積分関数はt²+1。", "基本定理よりF'(x)=x²+1。", "積分を先に展開してから微分しても同じ結果になる。"],
    workedAnswer: "x²+1",
    quickProblem: "d/dx ∫[1,x]cos t dtは？",
    quickAnswer: "cos x",
    quickExplanation: "上端xを代入した被積分関数がそのまま微分結果になる。",
    transferProblem: "下端もxで動く∫[x,2]f(t)dtを微分すると？",
    transferAnswer: "−f(x)",
    transferExplanation: "下端が動くため、区間の向きの変化でマイナスが付く。",
  },
  "III-37": {
    definition: "曲線とx軸の面積は、関数の符号を確認し、x軸より上ならf、下なら−fを積分する。",
    firstMove: "零点で区間を分け、上側・下側を判定する。",
    trap: "定積分の値をそのまま面積だと思い、負の部分を相殺する。",
    workedProblem: "y=xとx軸、x=0,2で囲まれる面積を求めよ。",
    workedSteps: ["0≤x≤2ではx≥0なのでグラフはx軸の上。", "面積=∫[0,2]x dx。", "=[x²/2]0^2=2。"],
    workedAnswer: "2",
    quickProblem: "y=−xをx=0から1までx軸との面積にすると？",
    quickAnswer: "1/2",
    quickExplanation: "積分値は−1/2だが、面積はその絶対値で1/2。",
    transferProblem: "曲線がx軸を横切るとき、面積計算で必要な操作は？",
    transferAnswer: "零点で積分区間を分けて絶対値を取る",
    transferExplanation: "符号が変わる点を境に、各部分を正の面積として足す。",
  },
  "III-38": {
    definition: "複数曲線で囲まれる面積は、交点と区間を決め、上の関数から下の関数を引いて積分する。",
    firstMove: "交点を解き、区間内で上下関係を一度確認する。",
    trap: "上−下の順を確認せず、面積を負にする。",
    workedProblem: "y=2xとy=x²で囲まれる第一象限側の面積を求めよ。",
    workedSteps: ["交点は2x=x²よりx=0,2。", "0<x<2では2x>x²なので上は2x。", "面積=∫[0,2](2x−x²)dx=4−8/3=4/3。"],
    workedAnswer: "4/3",
    quickProblem: "面積の被積分関数は、上の曲線をf、下をgとすると？",
    quickAnswer: "f(x)−g(x)",
    quickExplanation: "縦の長さは上のy座標から下のy座標を引く。",
    transferProblem: "上下関係が区間途中で入れ替わるときは？",
    transferAnswer: "入れ替わる交点で積分を分ける",
    transferExplanation: "一つのf−gで全区間を積分すると、面積が相殺されることがある。",
  },
  "III-39": {
    definition: "回転体の体積は、薄い円板や円環の断面積を積分して求める。半径は回転軸からの距離。",
    firstMove: "回転軸に垂直な断面の半径と区間を決める。",
    trap: "半径ではなく直径をそのままπr²へ入れる。",
    workedProblem: "y=xを0≤x≤1でx軸の周りに回転した体積を求めよ。",
    workedSteps: ["xでの断面は半径y=xの円。", "V=π∫[0,1]x²dx。", "V=π[x³/3]0^1=π/3。"],
    workedAnswer: "π/3",
    quickProblem: "半径f(x)の円板の断面積は？",
    quickAnswer: "πf(x)²",
    quickExplanation: "円の面積πr²で、r=f(x)。",
    transferProblem: "内半径r、外半径Rの円環の断面積は？",
    transferAnswer: "π(R²−r²)",
    transferExplanation: "外側の円板から内側の穴を引く。",
  },
  "III-40": {
    definition: "断面積による体積は、立体を薄く切ったときの面積A(x)を積分してV=∫A(x)dxとする。",
    firstMove: "切断方向を決め、各位置の断面の形と面積を式にする。",
    trap: "断面積を一定だと思い、最大断面積×長さだけで済ませる。",
    workedProblem: "0≤x≤2で、断面が一辺xの正方形となる立体の体積を求めよ。",
    workedSteps: ["位置xの断面積はA(x)=x²。", "V=∫[0,2]x²dx。", "V=[x³/3]0^2=8/3。"],
    workedAnswer: "8/3",
    quickProblem: "断面積A(x)から体積を作る式は？",
    quickAnswer: "∫A(x)dx",
    quickExplanation: "薄い断面を足し合わせるので、断面積を積分する。",
    transferProblem: "同じ立体を別方向の断面で積分する場合、変わるのは？",
    transferAnswer: "断面の形・面積関数と積分区間",
    transferExplanation: "体積は同じでも、切り方が変わればAと変数・区間の表現が変わる。",
  },
  "III-41": {
    definition: "曲線の長さは、微小な直角三角形の長さを積分する。媒介表示では√((dx/dt)²+(dy/dt)²)を使う。",
    firstMove: "x(t),y(t)を微分し、tの範囲を確認する。",
    trap: "x方向の長さだけを積分して曲線の長さとする。",
    workedProblem: "x=cos t、y=sin t（0≤t≤π/2）の曲線の長さを求めよ。",
    workedSteps: ["dx/dt=−sin t、dy/dt=cos t。", "速さは√(sin²t+cos²t)=1。", "長さ=∫[0,π/2]1dt=π/2。"],
    workedAnswer: "π/2",
    quickProblem: "媒介表示の曲線長の被積分関数は？",
    quickAnswer: "√((dx/dt)²+(dy/dt)²)",
    quickExplanation: "微小な横・縦の変化を三平方の定理でまとめる。",
    transferProblem: "曲線長で被積分関数が1になるのは、どんな場合か？",
    transferAnswer: "媒介変数に対する速度が1のとき",
    transferExplanation: "√(x'(t)²+y'(t)²)が平面上の速さで、1なら長さはパラメータ幅と同じ。",
  },
  "III-42": {
    definition: "媒介表示の面積は、x(t)が単調で曲線が対象領域を一度だけなぞる区間において、曲線と基準線に囲まれる符号付き面積を∫y(t)x'(t)dtで表す。幾何学的面積では上下関係・向き・絶対値を確認し、閉曲線では線積分の符号も確認する。",
    firstMove: "x'(t)dt=dxへ変換し、tの範囲、x(t)の単調性、曲線と基準線が囲む領域を確認する。",
    trap: "∫y(t)dtとしてしまい、dx/dtを掛け忘れる。",
    workedProblem: "x=t、y=t²（0≤t≤1）とx軸で囲まれる面積を求めよ。",
    workedSteps: ["dx/dt=1なので、面積=∫[0,1]t²・1dt。", "∫t²dt=[t³/3]0^1。", "面積は1/3。"],
    workedAnswer: "1/3",
    quickProblem: "媒介表示の面積で必要な因子は？",
    quickAnswer: "dx/dt",
    quickExplanation: "y dxをdtで積分するため、dx/dtを掛ける。",
    transferProblem: "x(t)が減少する向きに媒介表示されると、積分値の符号は？",
    transferAnswer: "向きに応じて負になり得る",
    transferExplanation: "線積分的な表現では向きが符号に反映されるため、面積としては絶対値や順序を確認する。",
  },
  "III-43": {
    definition: "極座標の面積は、原点からの距離rと角度θで細い扇形を足し、1/2∫r²dθとする。",
    firstMove: "θの範囲と、rが表す境界を決める。",
    trap: "直交座標の∫y dxをそのまま極座標へ持ち込む。",
    workedProblem: "r=2、0≤θ≤2πで囲まれる面積を求めよ。",
    workedSteps: ["半径が常に2の円。", "A=1/2∫[0,2π]2²dθ。", "A=1/2・4・2π=4π。"],
    workedAnswer: "4π",
    quickProblem: "極座標の面積公式は？",
    quickAnswer: "1/2∫r²dθ",
    quickExplanation: "微小扇形の面積は1/2 r²dθ。",
    transferProblem: "r=2cosθ（−π/2≤θ≤π/2）はどんな図形か？",
    transferAnswer: "中心(1,0)、半径1の円",
    transferExplanation: "r²=2r cosθよりx²+y²=2x、平方完成して円へ直す。",
  },
  "III-44": {
    definition: "数値積分は、曲線下の面積を小さな長方形・台形へ分割して近似する考え。分割を細かくすると精度が上がる。",
    firstMove: "区間幅hと各点の関数値を表にする。",
    trap: "台形公式の端点を2倍してしまう。",
    workedProblem: "台形公式を2分割で使い、∫[0,2]x²dxを近似せよ。",
    workedSteps: ["h=(2−0)/2=1、値はf(0)=0,f(1)=1,f(2)=4。", "台形近似はh/2[f(0)+2f(1)+f(2)]。", "=1/2(0+2+4)=3。"],
    workedAnswer: "3",
    quickProblem: "台形公式で内側の点に掛かる係数は？",
    quickAnswer: "2",
    quickExplanation: "隣り合う2つの台形に共有されるため、内側の点は2回現れる。",
    transferProblem: "分割数を増やすと、通常は近似積分の誤差はどうなるか？",
    transferAnswer: "小さくなる",
    transferExplanation: "曲線を細かい台形で近似するため、滑らかな関数なら真の面積へ近づく。",
  },
  "III-45": {
    definition: "積分による評価は、関数の上下関係を区間全体で積分し、面積・平均値の大小を不等式にする。",
    firstMove: "区間内でf≤gが本当に成り立つかを確認してから積分する。",
    trap: "一部の点だけの大小を、積分区間全体の大小だと思う。",
    workedProblem: "0≤x≤1でx²≤xを積分して不等式を作れ。",
    workedSteps: ["0≤x≤1ではx(1−x)≥0なのでx²≤x。", "両辺を積分して∫x²dx≤∫x dx。", "1/3≤1/2が得られる。"],
    workedAnswer: "1/3≤1/2",
    quickProblem: "区間内で0≤f(x)≤g(x)なら、積分後の関係は？",
    quickAnswer: "0≤∫f≤∫g",
    quickExplanation: "非負の差g−fを積分しても非負のまま。",
    transferProblem: "平均値を評価したいとき、∫fの両辺を何で割るか？",
    transferAnswer: "区間の長さ",
    transferExplanation: "積分値を区間長b−aで割ると、区間平均の値になる。",
  },
  "III-46": {
    definition: "微積分のモデル統合は、変化率を微分、累積量を積分、最良の選択を微分による最適化として一つの現象でつなぐ。",
    firstMove: "何が状態量・変化率・累積量・目的量かを言葉で分ける。",
    trap: "速度を積分した量と、位置の値を混同する。",
    workedProblem: "位置s(t)=t³−3t²+2t（0≤t≤2）の初めと終わりの位置、および速度を求めよ。",
    workedSteps: ["s(0)=0、s(2)=8−12+4=0なので変位は0。", "速度v=s'=3t²−6t+2。", "速度の積分∫[0,2]v(t)dt=s(2)−s(0)=0で、微分と積分が一致する。"],
    workedAnswer: "初め0、終わり0、速度v(t)=3t²−6t+2",
    quickProblem: "変化率v(t)から累積変化量を求める操作は？",
    quickAnswer: "v(t)を積分する",
    quickExplanation: "速度を時間で積分すると位置の変化量になる。",
    transferProblem: "モデル化で微積分を使う前に、最初に固定すべきものは？",
    transferAnswer: "変数・単位・初期条件",
    transferExplanation: "何を測る式か、初期値が何かを決めないと、計算結果を現象へ戻せない。",
  },
};
