import type { Problem } from "../problem-bank";

/**
 * 問題数4倍化・第4バッチ。
 * 数学I/A/II/B/C/IIIから5問ずつ、条件文・表・グラフの読み替えを含む
 * オリジナルの共通テスト型問題を収録する。公式過去問の転載は行わない。
 */
export const problemExpansionBatch04: Problem[] = [
  // 数学I：二次関数・図形と計量・データの分析
  {
    id: "X4-210",
    conceptIds: ["I-29"],
    primaryConceptId: "I-29",
    title: "区間内の最大値をグラフから読む",
    prompt: "ある区間−1≦x≦3で、関数f(x)=−(x−1)^2+4が表す高さを考える。この区間での高さの最大値はどれか。",
    options: ["3", "4", "5", "8"],
    answer: 1,
    explanation: "f(x)は頂点(1,4)が上に開かない放物線の頂点なので、x=1で最大になる。1は区間−1≦x≦3に含まれるため、最大値は4。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-211",
    conceptIds: ["I-41", "I-35"],
    primaryConceptId: "I-41",
    title: "測量の条件文を高さへ変換する",
    prompt: "地面から1.5mの高さにある観測点から塔の頂点を見上げた。塔の足元までの水平距離は20mで、仰角をθとするとtanθ=3/4である。塔の高さは何mか。",
    options: ["15", "16", "16.5", "18.5"],
    answer: 2,
    explanation: "観測点から頂点までの高さの差は20×tanθ=20×3/4=15m。観測点の高さ1.5mを加えるので、塔の高さは15+1.5=16.5m。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "X4-212",
    conceptIds: ["I-45"],
    primaryConceptId: "I-45",
    title: "箱ひげ図の5数要約を読む",
    prompt: "あるデータの箱ひげ図から、最小値7、第1四分位数12、中央値18、第3四分位数25、最大値31が読み取れた。このデータについて確実に言えることはどれか。",
    options: ["データの50%は12以上25以下である", "平均値は18である", "データの75%は12以上である", "範囲は13である"],
    answer: 0,
    explanation: "第1四分位数から第3四分位数までの箱の部分には中央の50%のデータが入る。したがって12以上25以下のデータが50%を占める。平均値は箱ひげ図だけでは決まらず、範囲は31−7=24。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-213",
    conceptIds: ["I-48", "I-47"],
    primaryConceptId: "I-48",
    title: "表の散らばりを標準偏差で比較する",
    prompt: "2つのデータA、Bは次の表で与えられる。A={8,9,10,11,12}、B={6,8,10,12,14}。両方の平均値は10である。標準偏差の大小関係として正しいものはどれか。",
    options: ["Aの標準偏差はBの2倍", "Bの標準偏差はAの2倍", "AとBの標準偏差は等しい", "平均値が同じなので比較できない"],
    answer: 1,
    explanation: "平均からの偏差はAでは−2,−1,0,1,2、Bでは−4,−2,0,2,4。偏差平方の平均はそれぞれ2と8なので、標準偏差は√2と√8=2√2となり、BがAの2倍。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-214",
    conceptIds: ["I-51", "I-52"],
    primaryConceptId: "I-51",
    title: "散布図の対応表を相関へ読み替える",
    prompt: "4人の学習時間xと得点yを表にすると、(x,y)=(1,52),(2,58),(3,64),(4,70)であった。このデータの相関係数rとして最も適切なものはどれか。",
    options: ["−1", "−0.5", "0.5", "1"],
    answer: 3,
    explanation: "得点はy=46+6xで学習時間の一次関数として完全に増加している。したがって散布図の点は1本の右上がりの直線上にあり、相関係数は1。",
    kind: "standard",
    estimatedSeconds: 70,
  },

  // 数学A：場合の数と確率・図形・整数
  {
    id: "X4-215",
    conceptIds: ["A-05"],
    primaryConceptId: "A-05",
    title: "役割を区別しない選び方",
    prompt: "5人の中から、発表資料を確認する担当者を2人選ぶ。2人の間に役割の違いがないとき、選び方は何通りか。",
    options: ["5", "8", "10", "20"],
    answer: 2,
    explanation: "順番を区別しない2人の選択なので、組合せ5C2=5×4/(2×1)=10通り。担当者A、BとB、Aを別々に数えない。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-216",
    conceptIds: ["A-12", "A-13"],
    primaryConceptId: "A-12",
    title: "アンケート表を加法定理へ変換する",
    prompt: "40人に2つの講座P、Qの受講経験を尋ねたところ、Pを受講した人は60%、Qを受講した人は45%、両方を受講した人は25%だった。少なくとも一方を受講した人の割合はどれか。",
    options: ["0.70", "0.80", "0.85", "1.05"],
    answer: 1,
    explanation: "加法定理よりP(P∪Q)=P(P)+P(Q)−P(P∩Q)=0.60+0.45−0.25=0.80。両方を受講した人を二重に数えた分を引く。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-217",
    conceptIds: ["A-17", "A-05"],
    primaryConceptId: "A-17",
    title: "反復試行の成功回数を読む",
    prompt: "表が出る確率が1/2のコインを4回投げる。表がちょうど3回出る確率はどれか。",
    options: ["1/16", "1/8", "1/4", "1/2"],
    answer: 2,
    explanation: "表が出る回を4回から3回選ぶ方法が4通りあり、各並びの確率は(1/2)^4。したがって4×(1/2)^4=1/4。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-218",
    conceptIds: ["A-30"],
    primaryConceptId: "A-30",
    title: "中心角を円周角へ読み替える",
    prompt: "円Oで、弧ABに対する中心角∠AOBが120°である。同じ弧ABに対する円周角∠ACB（Cは弧AB上にない点）は何度か。",
    options: ["30°", "60°", "120°", "240°"],
    answer: 1,
    explanation: "同じ弧に対する円周角は中心角の半分なので、∠ACB=120°÷2=60°。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-219",
    conceptIds: ["A-44", "A-45"],
    primaryConceptId: "A-44",
    title: "余りの表を合同式で判定する",
    prompt: "整数nを5で割ったときの余りが2である。次の数のうち、この条件を満たすものはどれか。",
    options: ["17", "18", "21", "23"],
    answer: 0,
    explanation: "条件はn≡2 (mod 5)。17=5×3+2なので条件を満たす。一方18,21,23の余りはそれぞれ3,1,3。",
    kind: "quick",
    estimatedSeconds: 45,
  },

  // 数学II：座標・指数対数・三角関数・微分
  {
    id: "X4-220",
    conceptIds: ["II-23", "II-19"],
    primaryConceptId: "II-23",
    title: "直線と円の共有点を連立する",
    prompt: "円x^2+y^2=25と直線y=3の共有点として正しいものはどれか。",
    options: ["(3,4)と(3,−4)", "(4,3)と(−4,3)", "(5,3)と(−5,3)", "共有点は1個"],
    answer: 1,
    explanation: "y=3を円の式に代入するとx^2+9=25、よってx^2=16、x=±4。共有点は(4,3),(−4,3)の2点。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-221",
    conceptIds: ["II-31", "II-39"],
    primaryConceptId: "II-31",
    title: "表の倍率を指数関数へ変換する",
    prompt: "時刻xと測定値yの表が、x=0,1,2,3に対してy=5,10,20,40となっている。この変化を表す式とx=4の値の組として正しいものはどれか。",
    options: ["y=5x、20", "y=2^x+5、21", "y=5×2^x、80", "y=10×2^x、160"],
    answer: 2,
    explanation: "xが1増えるたびにyが2倍で、x=0の値が5だからy=5×2^x。x=4では5×16=80。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-222",
    conceptIds: ["II-38", "II-34"],
    primaryConceptId: "II-38",
    title: "対数不等式の定義域を先に確認する",
    prompt: "不等式log_2(x−1)≧3を満たすxの範囲はどれか。",
    options: ["x≧8", "x>8", "x≧9", "1<x≦9"],
    answer: 2,
    explanation: "真数条件x−1>0を確認し、底2は1より大きいので不等号の向きは変わらない。x−1≧2^3=8よりx≧9。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-223",
    conceptIds: ["II-47", "II-41"],
    primaryConceptId: "II-47",
    title: "単位円の位置から三角方程式を解く",
    prompt: "0≦θ<2πの範囲で、2sinθ−1=0を満たすθの組はどれか。",
    options: ["θ=π/6", "θ=5π/6", "θ=π/6, 5π/6", "θ=π/3, 2π/3"],
    answer: 2,
    explanation: "sinθ=1/2。単位円で正になる第1象限と第2象限に解があり、θ=π/6,5π/6。指定区間ではこれ以外にない。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-224",
    conceptIds: ["II-57", "I-29"],
    primaryConceptId: "II-57",
    title: "制約付きの面積最大を微分へ変換する",
    prompt: "周の長さが20の長方形で、横をx、縦を10−x（0<x<10）とする。面積が最大になるときの面積はどれか。",
    options: ["20", "24", "25", "30"],
    answer: 2,
    explanation: "面積S=x(10−x)=−x^2+10x。S'=−2x+10=0よりx=5で、S=5×5=25。端に近づくと面積は小さくなるので最大値は25。",
    kind: "transfer",
    estimatedSeconds: 85,
  },

  // 数学B：数列・統計的な推測・モデル
  {
    id: "X4-225",
    conceptIds: ["B-05"],
    primaryConceptId: "B-05",
    title: "表の倍率から等比数列を特定する",
    prompt: "ある等比数列は第1項が81、第2項が27である。この数列の第5項はどれか。",
    options: ["1/3", "1", "3", "9"],
    answer: 1,
    explanation: "公比は27/81=1/3。したがって第5項は81×(1/3)^4=81/81=1。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-226",
    conceptIds: ["B-13", "B-08"],
    primaryConceptId: "B-13",
    title: "日ごとの変化を漸化式へ読む",
    prompt: "初日に10個の部品があり、翌日から毎日3個ずつ増える。n日目の個数をa_nとするとき、7日目の個数はどれか。",
    options: ["28", "29", "30", "31"],
    answer: 0,
    explanation: "a_1=10、a_{n+1}=a_n+3なので等差数列。a_7=10+(7−1)×3=28。増加は6回分であることに注意する。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-227",
    conceptIds: ["B-19", "B-20"],
    primaryConceptId: "B-19",
    title: "二項分布の表を確率に戻す",
    prompt: "1回の試行が成功する確率が0.8で、5回の試行は独立である。成功回数がちょうど4回となる確率はどれか。",
    options: ["0.08192", "0.2048", "0.4096", "0.8192"],
    answer: 2,
    explanation: "成功4回・失敗1回の並びは5通り。確率は5×(0.8)^4×0.2=5×0.4096×0.2=0.4096。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-228",
    conceptIds: ["B-28", "B-25"],
    primaryConceptId: "B-28",
    title: "標本平均から母平均の区間を作る",
    prompt: "母標準偏差が4と分かっている母集団から大きさ16の標本を取り、標本平均が52となった。標準正規分布の上側2.5%点を1.96とすると、母平均の95%信頼区間はどれか。",
    options: ["[48.04, 55.96]", "[50.04, 53.96]", "[51.00, 53.00]", "[52.00, 55.92]"],
    answer: 1,
    explanation: "標本平均の標準誤差は4/√16=1。したがって95%信頼区間は52±1.96×1、つまり[50.04,53.96]。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X4-229",
    conceptIds: ["B-31", "B-30"],
    primaryConceptId: "B-31",
    title: "p値を棄却域の判断へ読み替える",
    prompt: "有意水準5%で帰無仮説を検定したところ、p値が0.03となった。この結果の解釈として正しいものはどれか。",
    options: ["帰無仮説を棄却する", "帰無仮説を必ず正しいと認める", "有意水準を10%に変えないと判断できない", "p値が正なので帰無仮説を採択する"],
    answer: 0,
    explanation: "p値0.03は有意水準0.05より小さいため、観測結果は帰無仮説のもとでは起こりにくいと判断し、帰無仮説を棄却する。",
    kind: "standard",
    estimatedSeconds: 70,
  },

  // 数学C：ベクトル・複素数平面・グラフの表現
  {
    id: "X4-230",
    conceptIds: ["C-05", "C-01"],
    primaryConceptId: "C-05",
    title: "座標表をベクトルの成分へ変換する",
    prompt: "点A(1,2)から点B(4,−2)へ向かうベクトルABの成分表示はどれか。",
    options: ["(5,0)", "(3,−4)", "(−3,4)", "(4,−2)"],
    answer: 1,
    explanation: "終点の座標から始点の座標を引くので、AB=(4−1,−2−2)=(3,−4)。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-231",
    conceptIds: ["C-12", "C-10"],
    primaryConceptId: "C-12",
    title: "直交条件を内積の表へ読み替える",
    prompt: "ベクトルu=(2,1)とv=(x,−4)が直交するとき、xの値はどれか。",
    options: ["−4", "−2", "2", "4"],
    answer: 2,
    explanation: "直交条件は内積が0。u・v=2x+1×(−4)=2x−4=0よりx=2。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X4-232",
    conceptIds: ["C-20", "C-11"],
    primaryConceptId: "C-20",
    title: "軌跡を距離の最小問題へ変換する",
    prompt: "点P(t)=(t,2−t)が直線x+y=2上を動く。原点からP(t)までの距離が最小になるときの距離はどれか。",
    options: ["1", "√2", "2", "2√2"],
    answer: 1,
    explanation: "距離の2乗はd^2=t^2+(2−t)^2=2(t−1)^2+2。最小はt=1のときでd^2=2、よってd=√2。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "X4-233",
    conceptIds: ["C-29", "C-21"],
    primaryConceptId: "C-29",
    title: "複素数の条件を軌跡へ読み替える",
    prompt: "複素数zが|z−2|=3を満たすとき、複素数平面上でzが動く図形はどれか。",
    options: ["中心2、半径3の円", "中心−2、半径3の円", "中心2、半径9の円", "実軸上の線分"],
    answer: 0,
    explanation: "|z−2|は複素数平面上で点zと実軸上の点2との距離を表す。距離が3で一定なので、中心2、半径3の円になる。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-234",
    conceptIds: ["C-42", "C-41"],
    primaryConceptId: "C-42",
    title: "目盛りを確認して棒グラフを読む",
    prompt: "2地域の割合を棒グラフで比較した。地域Aは92%、地域Bは96%で、グラフの縦軸は90%から始まっている。このグラフの読み方として正しいものはどれか。",
    options: ["BはAより4ポイント高い", "Bの棒の高さはAの2倍である", "AとBの差は約50%である", "縦軸が90%から始まるので比較できない"],
    answer: 0,
    explanation: "数値の差は96−92=4ポイント。縦軸を90%から始めると差が大きく見えることはあるが、実際の割合の差は4ポイントである。",
    kind: "transfer",
    estimatedSeconds: 70,
  },

  // 数学III：極限・微分・積分・数値計算
  {
    id: "X4-235",
    conceptIds: ["III-05", "III-10"],
    primaryConceptId: "III-05",
    title: "関数の極限を約分へ読み替える",
    prompt: "lim(x→2)(x^2−4)/(x−2)の値はどれか。",
    options: ["0", "2", "4", "発散する"],
    answer: 2,
    explanation: "x^2−4=(x−2)(x+2)なので、x≠2で式はx+2に等しい。したがって極限は2+2=4。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-236",
    conceptIds: ["III-18", "III-14"],
    primaryConceptId: "III-18",
    title: "媒介変数の表を接線の傾きへ変換する",
    prompt: "曲線をx=t^2、y=t^3で表す。t=1における接線の傾きdy/dxはどれか。",
    options: ["1/2", "1", "3/2", "2"],
    answer: 2,
    explanation: "媒介変数表示ではdy/dx=(dy/dt)/(dx/dt)。dy/dt=3t^2、dx/dt=2tなので、t=1では3/2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-237",
    conceptIds: ["III-25", "III-22"],
    primaryConceptId: "III-25",
    title: "増減表から最大値を選ぶ",
    prompt: "区間0≦x≦3でf(x)=−x^3+3x^2+1を考える。導関数の符号を調べたとき、この区間での最大値はどれか。",
    options: ["1", "3", "5", "7"],
    answer: 2,
    explanation: "f'(x)=−3x(x−2)。臨界点はx=0,2で、f(0)=1、f(2)=5、f(3)=1。端点も含めて比較すると最大値は5。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-238",
    conceptIds: ["III-38", "III-37"],
    primaryConceptId: "III-38",
    title: "2曲線の上下関係を面積へ変換する",
    prompt: "0≦x≦1で、曲線y=xとy=x^2に囲まれる部分の面積はどれか。",
    options: ["1/12", "1/6", "1/4", "1/3"],
    answer: 1,
    explanation: "区間0≦x≦1ではx≧x^2なので、面積は∫_0^1(x−x^2)dx=[x^2/2−x^3/3]_0^1=1/2−1/3=1/6。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-239",
    conceptIds: ["III-44", "III-35"],
    primaryConceptId: "III-44",
    title: "表の値を台形公式へ読み替える",
    prompt: "関数fの値が表f(0)=1、f(1)=3、f(2)=5で与えられている。刻み幅1の台形公式で∫_0^2 f(x)dxを近似するといくらか。",
    options: ["4", "5", "6", "7"],
    answer: 2,
    explanation: "台形公式は1/2×{f(0)+2f(1)+f(2)}。値を代入すると1/2×(1+6+5)=6。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
];
