import type { Problem } from "../problem-bank";

/**
 * 問題数4倍化の第二バッチ。
 * 既存のX4-001〜X4-075とは異なる状況・数値・問い方で、数学I/Aの
 * 表・条件文・場合分け・グラフ読解を含むオリジナル問題を収録する。
 */
export const problemExpansionBatch02: Problem[] = [
  // 数学I：数と式・二次関数
  {
    id: "X4-076",
    conceptIds: ["I-01"],
    primaryConceptId: "I-01",
    title: "有理数と無理数を見分ける",
    prompt: "次の数のうち、無理数はどれか。",
    options: ["0.4", "√9", "7/5", "√7"],
    answer: 3,
    explanation: "0.4=2/5、√9=3、7/5はいずれも有理数である。一方、√7は整数の比で表せない無理数である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-077",
    conceptIds: ["I-02"],
    primaryConceptId: "I-02",
    title: "一次不等式を区間で表す",
    prompt: "不等式 −2＜3x+1≦10を満たすxの範囲を、区間の記号で表せ。",
    options: ["[−1,3]", "(−1,3]", "[−1,3)", "(−1,3)"],
    answer: 1,
    explanation: "両辺から1を引くと−3＜3x≦9。3で割って−1＜x≦3となるので、左端は含まず右端を含む(−1,3]である。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-078",
    conceptIds: ["I-03"],
    primaryConceptId: "I-03",
    title: "和集合と共通部分を同時に読む",
    prompt: "A={1,2,4,5}、B={2,3,5}とする。A∪BからA∩Bを除いた集合はどれか。",
    options: ["{1,3,4}", "{2,5}", "{1,2,3,4,5}", "{1,4,5}"],
    answer: 0,
    explanation: "A∪B={1,2,3,4,5}、A∩B={2,5}である。共通部分を除くと{1,3,4}が残る。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "X4-079",
    conceptIds: ["I-04"],
    primaryConceptId: "I-04",
    title: "命題の真偽を代入で確認する",
    prompt: "命題「x²=0ならばx=0である」について正しいものはどれか。",
    options: ["真である", "偽であり、x=1が反例", "偽であり、x=−1が反例", "xの範囲がないので命題ではない"],
    answer: 0,
    explanation: "実数xについてx²=0となるのはx=0だけである。したがって仮定から結論が必ず導かれ、命題は真である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-080",
    conceptIds: ["I-05"],
    primaryConceptId: "I-05",
    title: "倍数条件の必要十分",
    prompt: "整数nについて、「nが6の倍数である」ことは「nが3の倍数である」ことの何条件か。",
    options: ["必要条件だが十分条件ではない", "十分条件だが必要条件ではない", "必要十分条件", "必要条件でも十分条件でもない"],
    answer: 1,
    explanation: "6の倍数なら必ず3の倍数なので十分条件である。しかし3の倍数でも6の倍数とは限らないため、必要条件ではない。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-081",
    conceptIds: ["I-06"],
    primaryConceptId: "I-06",
    title: "対偶を使った証明",
    prompt: "整数aについて「a²が偶数ならばaは偶数である」を証明する方針として最も適切なものはどれか。",
    options: ["aが偶数の場合だけを調べる", "a²が偶数になる例を1つ示す", "aが奇数ならばa²も奇数であることを示す", "a²を必ず展開して値を求める"],
    answer: 2,
    explanation: "元の命題の対偶は「aが奇数ならばa²は奇数」である。対偶を示せば元の命題も示せる。奇数a=2k+1ならa²=4k(k+1)+1で奇数になる。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-082",
    conceptIds: ["I-07"],
    primaryConceptId: "I-07",
    title: "数直線上の距離",
    prompt: "数直線上で、点−2と点5の距離を求めよ。",
    options: ["−7", "−3", "3", "7"],
    answer: 3,
    explanation: "距離は座標の差の絶対値なので|5−(−2)|=|7|=7である。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "X4-083",
    conceptIds: ["I-08"],
    primaryConceptId: "I-08",
    title: "二つの式をまとめて展開する",
    prompt: "(x−2)(x+3)+(x+1)²を整理した式はどれか。",
    options: ["2x²+x−5", "2x²+3x−5", "x²+3x−5", "2x²+x+5"],
    answer: 1,
    explanation: "(x−2)(x+3)=x²+x−6、(x+1)²=x²+2x+1なので、和は2x²+3x−5である。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-084",
    conceptIds: ["I-09"],
    primaryConceptId: "I-09",
    title: "三次式を段階的に因数分解する",
    prompt: "x³−4xを因数分解した結果はどれか。",
    options: ["x(x−4)(x+4)", "x(x−2)(x+2)", "(x−2)(x+2)", "x²(x−4)"],
    answer: 1,
    explanation: "まずxをくくるとx(x²−4)。差の平方を使えばx(x−2)(x+2)となる。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
  {
    id: "X4-085",
    conceptIds: ["I-10"],
    primaryConceptId: "I-10",
    title: "分数式の約分と条件",
    prompt: "x≠0,3のとき、(x²−9)/(x²−3x)を簡単にした式はどれか。",
    options: ["(x−3)/x", "(x+3)/x", "x+3", "(x²+3)/x"],
    answer: 1,
    explanation: "分子は(x−3)(x+3)、分母はx(x−3)なので、x≠3を使って約分すると(x+3)/xとなる。x≠0も分母の条件である。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-086",
    conceptIds: ["I-11"],
    primaryConceptId: "I-11",
    title: "根号を含む分数を整理する",
    prompt: "(√18+√8)/√2の値を求めよ。",
    options: ["3", "5", "5√2", "10"],
    answer: 1,
    explanation: "√18=3√2、√8=2√2なので、分子は5√2。これを√2で割ると5になる。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-087",
    conceptIds: ["I-12"],
    primaryConceptId: "I-12",
    title: "二項式の分母を有理化する",
    prompt: "(√5+1)/(√5−1)を分母に根号を含まない形で表せ。",
    options: ["(3−√5)/2", "(3+√5)/2", "3+√5", "(5+√5)/2"],
    answer: 1,
    explanation: "分母の共役√5+1を掛けると、分母は5−1=4、分子は(√5+1)²=6+2√5。よって(3+√5)/2である。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-088",
    conceptIds: ["I-13"],
    primaryConceptId: "I-13",
    title: "文字の値を代入する",
    prompt: "x=−2、y=3のとき、x²−2xy+y²の値を求めよ。",
    options: ["1", "5", "13", "25"],
    answer: 3,
    explanation: "x²−2xy+y²=(x−y)²である。x−y=−5だから、値は(−5)²=25。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-089",
    conceptIds: ["I-14"],
    primaryConceptId: "I-14",
    title: "係数が1でない二次方程式",
    prompt: "3x²−x−2=0を解け。",
    options: ["x=−1, 2/3", "x=1, −2/3", "x=−1, −2/3", "x=1, 2/3"],
    answer: 1,
    explanation: "3x²−x−2=(3x+2)(x−1)なので、x=−2/3またはx=1である。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-090",
    conceptIds: ["I-15"],
    primaryConceptId: "I-15",
    title: "解の公式から大きい解を選ぶ",
    prompt: "2x²−4x−3=0の大きい方の解を求めよ。",
    options: ["(2+√10)/2", "(2−√10)/2", "2+√10", "(4+√10)/2"],
    answer: 0,
    explanation: "解の公式よりx=(4±√(16+24))/4=(4±2√10)/4=(2±√10)/2。大きい方なので(2+√10)/2である。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-091",
    conceptIds: ["I-16"],
    primaryConceptId: "I-16",
    title: "判別式で重解を見抜く",
    prompt: "方程式4x²−4x+1=0の実数解の個数は何個か。",
    options: ["0個", "1個", "2個", "3個"],
    answer: 1,
    explanation: "判別式D=(−4)²−4×4×1=0なので、異なる解はなく重解1個である。実数解の個数は1個と数える。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-092",
    conceptIds: ["I-17"],
    primaryConceptId: "I-17",
    title: "解の逆数の和",
    prompt: "2次方程式2x²−7x+3=0の2解をα、βとする。1/α+1/βの値はどれか。",
    options: ["7/3", "3/7", "7/2", "2/3"],
    answer: 0,
    explanation: "解と係数の関係からα+β=7/2、αβ=3/2。したがって1/α+1/β=(α+β)/(αβ)=(7/2)/(3/2)=7/3。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "X4-093",
    conceptIds: ["I-18"],
    primaryConceptId: "I-18",
    title: "分母を払って一次不等式を解く",
    prompt: "不等式 (x−2)/3≧1−x/2 を満たすxの範囲はどれか。",
    options: ["x≦2", "x≧2", "x≦−2", "x≧−2"],
    answer: 1,
    explanation: "両辺に6を掛けると2x−4≧6−3x。よって5x≧10、したがってx≧2である。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "X4-094",
    conceptIds: ["I-19"],
    primaryConceptId: "I-19",
    title: "絶対値不等式を距離で読む",
    prompt: "|x+1|<3を満たすxの範囲はどれか。",
    options: ["−3<x<3", "−4<x<2", "−2<x<4", "x<−4またはx>2"],
    answer: 1,
    explanation: "−3<x+1<3を順に解くと、−4<x<2となる。絶対値が3未満なので、中心−1から距離3未満の範囲である。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-095",
    conceptIds: ["I-20"],
    primaryConceptId: "I-20",
    title: "二次式の符号表",
    prompt: "不等式 (x−1)(x+3)≦0を満たすxの範囲はどれか。",
    options: ["−3≦x≦1", "x≦−3または1≦x", "−1≦x≦3", "x<−3またはx>1"],
    answer: 0,
    explanation: "2つの因子の符号が異なる区間は2つの解−3と1の間である。等号を含むので−3≦x≦1となる。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-096",
    conceptIds: ["I-21"],
    primaryConceptId: "I-21",
    title: "係数の符号で場合分けする",
    prompt: "実数aについて、(a−2)x>a−2を満たすxの範囲の説明として正しいものはどれか。",
    options: ["a>2ならx<1、a<2ならx>1、a=2ならすべての実数", "a>2ならx>1、a<2ならx<1、a=2なら解なし", "常にx>1", "常にx<1"],
    answer: 1,
    explanation: "a−2が正なら割って不等号は変わらずx>1、負なら割ると不等号が反転してx<1。a=2では0>0となり不成立なので解なし。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X4-097",
    conceptIds: ["I-22"],
    primaryConceptId: "I-22",
    title: "平方根関数の定義域",
    prompt: "関数 f(x)=√(x−4) の定義域はどれか。",
    options: ["x≦4", "x<4", "x≧4", "すべての実数"],
    answer: 2,
    explanation: "平方根の中身は0以上でなければならないのでx−4≧0、すなわちx≧4である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-098",
    conceptIds: ["I-23"],
    primaryConceptId: "I-23",
    title: "区間上のグラフから値域を読む",
    prompt: "関数y=−(x−2)²+5を0≦x≦4の範囲で考える。このときの値域はどれか。",
    options: ["1≦y≦5", "−5≦y≦1", "0≦y≦4", "1≦y≦4"],
    answer: 0,
    explanation: "頂点(2,5)で最大値5をとり、端点x=0,4ではy=1。したがって値域は1≦y≦5である。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "X4-099",
    conceptIds: ["I-24"],
    primaryConceptId: "I-24",
    title: "料金グラフの交点以後を読む",
    prompt: "料金プランA、Bのx km利用時の料金をそれぞれA=300+80x、B=500+50xとする。整数xについて、Bの方が安くなる最小の距離xは何kmか。",
    options: ["5km", "6km", "7km", "8km"],
    answer: 2,
    explanation: "B<Aを解くと500+50x<300+80x、つまり200<30x、x>20/3。xは整数なので最小は7である。",
    kind: "transfer",
    estimatedSeconds: 85,
  },
  {
    id: "X4-100",
    conceptIds: ["I-25"],
    primaryConceptId: "I-25",
    title: "標準形の頂点を読む",
    prompt: "二次関数y=2(x−3)²−1のグラフの頂点はどれか。",
    options: ["(−3,−1)", "(3,−1)", "(3,1)", "(−3,1)"],
    answer: 1,
    explanation: "y=a(x−p)²+qの頂点は(p,q)。ここではp=3、q=−1なので頂点は(3,−1)である。",
    kind: "quick",
    estimatedSeconds: 45,
  },
];
