import type { Problem } from "../problem-bank";

/**
 * 問題数4倍化・第5バッチ。
 * 数学I/A/II/B/C/IIIのオリジナル共通テスト型問題を50問収録する。
 * 表・条件文・グラフの読み取りと、誤答の原因を見抜く設問を混ぜている。
 */
export const problemExpansionBatch05: Problem[] = [
  // 数学I・A：式、関数、データ、確率、図形、整数
  {
    id: "X4-240",
    conceptIds: ["I-33"],
    primaryConceptId: "I-33",
    title: "2点の値から二次関数を決める",
    prompt: "関数f(x)=x^2+px+qがf(1)=0、f(3)=2を満たすとき、(p,q)の組はどれか。",
    options: ["(−3,2)", "(−2,1)", "(3,−2)", "(2,−3)"],
    answer: 0,
    explanation: "f(1)=0より1+p+q=0、f(3)=2より9+3p+q=2。差をとると8+2p=2なのでp=−3、さらにq=2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-241",
    conceptIds: ["I-34", "I-20"],
    primaryConceptId: "I-34",
    title: "条件を重ねた二次不等式",
    prompt: "x^2−5x+6≦0かつx≧1を満たすxの範囲はどれか。",
    options: ["1≦x≦2", "2≦x≦3", "x≦2またはx≧3", "1≦x≦3"],
    answer: 1,
    explanation: "x^2−5x+6=(x−2)(x−3)なので、二次不等式の解は2≦x≦3。これはx≧1も満たすため、そのまま答えになる。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-242",
    conceptIds: ["I-42", "I-41"],
    primaryConceptId: "I-42",
    title: "表の縮尺を実際の長さへ戻す",
    prompt: "地図の縮尺が1cmあたり2.5mである。表に記録された道の長さが7.2cmのとき、実際の長さは何mか。",
    options: ["16m", "18m", "18.5m", "20m"],
    answer: 1,
    explanation: "1cmが2.5mなので、7.2cmは7.2×2.5=18m。単位をcmのまま答えないようにする。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-243",
    conceptIds: ["I-49", "I-46"],
    primaryConceptId: "I-49",
    title: "標準化した得点を読む",
    prompt: "平均60、標準偏差8のテストで、ある生徒の得点が76点だった。この得点のz得点はどれか。",
    options: ["−2", "−1", "2", "8"],
    answer: 2,
    explanation: "z=(得点−平均)/標準偏差=(76−60)/8=2。平均より標準偏差2個分高い位置にある。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-244",
    conceptIds: ["A-13", "A-14"],
    primaryConceptId: "A-13",
    title: "条件付き確率を表から逆向きに読む",
    prompt: "箱Aを選ぶ確率は3/5、箱Bを選ぶ確率は2/5である。箱Aには青玉が2/3、箱Bには青玉が1/4の割合で入っている。青玉が出たとき、箱Aを選んだ確率はどれか。",
    options: ["2/5", "3/5", "3/4", "4/5"],
    answer: 3,
    explanation: "箱Aから青玉が出る確率は(3/5)(2/3)=2/5、箱Bからは(2/5)(1/4)=1/10。青玉全体は1/2なので、求める確率は(2/5)/(1/2)=4/5。",
    kind: "transfer",
    estimatedSeconds: 90,
  },
  {
    id: "X4-245",
    conceptIds: ["A-18"],
    primaryConceptId: "A-18",
    title: "得点表から期待値を計算する",
    prompt: "あるルーレットの得点Xは、0点を1/2、4点を1/3、9点を1/6の確率でとる。Xの期待値はどれか。",
    options: ["3/2", "17/6", "3", "17/3"],
    answer: 1,
    explanation: "期待値は0×1/2+4×1/3+9×1/6=4/3+3/2=17/6。各得点にその確率を掛けて足す。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-246",
    conceptIds: ["A-21"],
    primaryConceptId: "A-21",
    title: "相似の比を条件文に適用する",
    prompt: "△ABCで、辺AB上にDをとりAD:DB=1:2とする。Dを通りBCに平行な直線とACの交点をEとし、BC=12とする。このときDEは何か。",
    options: ["3", "4", "6", "8"],
    answer: 1,
    explanation: "AD:AB=1:(1+2)=1/3。△ADE∽△ABCよりDE:BC=1:3なので、DE=12/3=4。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-247",
    conceptIds: ["A-45", "A-44"],
    primaryConceptId: "A-45",
    title: "余りの周期を利用する",
    prompt: "整数nを3で割った余りを考える。2^2026を3で割ったときの余りはどれか。",
    options: ["0", "1", "2", "3"],
    answer: 1,
    explanation: "2の累乗の余りは2,1,2,1,…と2周期で繰り返す。2026は偶数なので、余りは1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-248",
    conceptIds: ["A-31", "A-30"],
    primaryConceptId: "A-31",
    title: "円に内接する四角形の角度表",
    prompt: "四角形ABCDが円に内接し、∠A=73°である。対角∠Cは何度か。",
    options: ["73°", "90°", "107°", "180°"],
    answer: 2,
    explanation: "円に内接する四角形では、向かい合う角の和が180°。したがって∠C=180°−73°=107°。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-249",
    conceptIds: ["I-52", "I-51"],
    primaryConceptId: "I-52",
    title: "外れ値が相関に与える影響を分析する",
    prompt: "散布図の相関係数が、1点を含めると0.92、その点を除くと0.55になった。この結果の解釈として最も適切なものはどれか。",
    options: [
      "相関係数が正なので、必ず因果関係がある",
      "平均値が変わらないので、1点の影響はない",
      "その1点が相関係数を大きく動かす影響点なので、含めた場合と除いた場合を比較して報告する",
      "相関係数は0.92と0.55の平均である",
    ],
    answer: 2,
    explanation: "相関係数は外れ値や影響点に左右される。1点を除いて値が大きく変わるなら、両方の散布図を確認し、その点の影響を明示する必要がある。相関だけで因果関係は決まらない。",
    kind: "transfer",
    estimatedSeconds: 80,
  },

  // 数学II：式・座標
  {
    id: "X4-250",
    conceptIds: ["II-05"],
    primaryConceptId: "II-05",
    title: "余りを代入で求める",
    prompt: "多項式P(x)=x^3−2x^2+ax+5をx−1で割ったときの余りが4である。aの値はどれか。",
    options: ["0", "1", "2", "4"],
    answer: 0,
    explanation: "剰余定理より余りはP(1)。P(1)=1−2+a+5=a+4なので、a+4=4からa=0。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-251",
    conceptIds: ["II-14"],
    primaryConceptId: "II-14",
    title: "係数比較で定数を決める",
    prompt: "すべてのxで2(x−1)^2+(x−1)+c=2x^2−3x+4が成り立つ。このときcはいくつか。",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "左辺を展開すると2x^2−4x+2+x−1+c=2x^2−3x+(1+c)。右辺の定数項4と比較して1+c=4、よってc=3。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-252",
    conceptIds: ["II-17"],
    primaryConceptId: "II-17",
    title: "表の2点から直線を読む",
    prompt: "表にx=1,3に対してy=5,9と記録されている。これら2点を通る直線の方程式はどれか。",
    options: ["y=x+4", "y=2x+3", "y=3x+2", "y=4x+1"],
    answer: 1,
    explanation: "傾きは(9−5)/(3−1)=2。x=1,y=5を代入して5=2×1+bよりb=3、したがってy=2x+3。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-253",
    conceptIds: ["II-18", "II-17"],
    primaryConceptId: "II-18",
    title: "垂直条件から直線を立てる",
    prompt: "直線y=2x+1に垂直で、点(1,4)を通る直線の方程式はどれか。",
    options: ["y=−2x+6", "y=(1/2)x+7/2", "y=2x+2", "y=−(1/2)x+9/2"],
    answer: 3,
    explanation: "傾き2の直線に垂直な直線の傾きは−1/2。点(1,4)を使うとy−4=−(1/2)(x−1)、よってy=−(1/2)x+9/2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-254",
    conceptIds: ["II-22"],
    primaryConceptId: "II-22",
    title: "不等式の表す領域を点で判定する",
    prompt: "座標平面上で、y≧x+1かつy≦3が表す領域に入る点はどれか。",
    options: ["(0,0)", "(1,2)", "(2,2)", "(3,4)"],
    answer: 1,
    explanation: "(1,2)は2≧1+1かつ2≦3を満たす。他の点はそれぞれ最初の不等式または2つ目の不等式を満たさない。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-255",
    conceptIds: ["II-24", "II-19"],
    primaryConceptId: "II-24",
    title: "円の接点で接線を決める",
    prompt: "円x^2+y^2=25上の点(3,4)における接線の方程式はどれか。",
    options: ["3x+4y=25", "4x−3y=25", "3x+4y=5", "x+y=7"],
    answer: 0,
    explanation: "中心から接点への半径の方向ベクトルは(3,4)で、接線の法線ベクトルになる。したがって3x+4y=3×3+4×4=25。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-256",
    conceptIds: ["II-29"],
    primaryConceptId: "II-29",
    title: "条件付き最大値を平方完成で読む",
    prompt: "x^2+y^2=1の条件のもとで、x+yの最大値はどれか。",
    options: ["1", "√2", "2", "4"],
    answer: 1,
    explanation: "(x+y)^2≦2(x^2+y^2)=2よりx+y≦√2。x=y=1/√2のとき等号が成立するので最大値は√2。",
    kind: "transfer",
    estimatedSeconds: 80,
  },

  // 数学II：指数・対数
  {
    id: "X4-257",
    conceptIds: ["II-30"],
    primaryConceptId: "II-30",
    title: "有理指数の計算法則",
    prompt: "a>0のとき、a^(3/2)÷a^(1/2)を簡単にしたものはどれか。",
    options: ["a^(1/2)", "a", "a^2", "a^3"],
    answer: 1,
    explanation: "同じ底の割り算では指数を引くので、a^(3/2−1/2)=a^1=a。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-258",
    conceptIds: ["II-32"],
    primaryConceptId: "II-32",
    title: "底をそろえて指数方程式を解く",
    prompt: "4^x=8を満たすxはどれか。",
    options: ["1", "3/2", "2", "3"],
    answer: 1,
    explanation: "4^x=(2^2)^x=2^(2x)、8=2^3なので2x=3。したがってx=3/2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-259",
    conceptIds: ["II-33"],
    primaryConceptId: "II-33",
    title: "底が1より小さい指数不等式",
    prompt: "(1/3)^x<1/27を満たすxの範囲はどれか。",
    options: ["x<3", "x≦3", "x>3", "x≧3"],
    answer: 2,
    explanation: "1/27=(1/3)^3。底1/3は0より大きく1より小さいため、指数関数は減少する。よって(1/3)^x<(1/3)^3からx>3。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-260",
    conceptIds: ["II-35"],
    primaryConceptId: "II-35",
    title: "対数の和を積にまとめる",
    prompt: "log_2 8+log_2 4の値はどれか。",
    options: ["4", "5", "6", "12"],
    answer: 1,
    explanation: "log_2 8=3、log_2 4=2なので和は5。対数の和をlog_2(8×4)としてもlog_2 32=5。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-261",
    conceptIds: ["II-36", "II-35"],
    primaryConceptId: "II-36",
    title: "表の対数値から底を変換する",
    prompt: "log_2 3≈1.585、log_2 5≈2.322が与えられている。log_2 15の近似値はどれか。",
    options: ["0.737", "2.322", "3.170", "3.907"],
    answer: 3,
    explanation: "15=3×5なのでlog_2 15=log_2 3+log_2 5≈1.585+2.322=3.907。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "X4-262",
    conceptIds: ["II-37"],
    primaryConceptId: "II-37",
    title: "対数関数のグラフを読む",
    prompt: "y=log_2 xのグラフから確実に読み取れることはどれか。",
    options: ["定義域はx<0である", "y軸に関して対称である", "x切片は(1,0)である", "xが増えるとyは減少する"],
    answer: 2,
    explanation: "log_2 1=0なので(1,0)を通る。定義域はx>0で、底2>1だから右上がり。y軸は漸近線ではなく、x=0が縦の漸近線になる。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-263",
    conceptIds: ["II-39", "II-31"],
    primaryConceptId: "II-39",
    title: "表の倍率から成長モデルを作る",
    prompt: "表でn=0,1,2に対して値が80,100,125となっている。毎回同じ倍率で増えるとき、n=3の値はどれか。",
    options: ["145", "150", "156.25", "160"],
    answer: 2,
    explanation: "倍率は100/80=125/100=1.25。したがって次の値は125×1.25=156.25で、モデルは80×1.25^n。",
    kind: "standard",
    estimatedSeconds: 65,
  },

  // 数学II：三角関数
  {
    id: "X4-264",
    conceptIds: ["II-40"],
    primaryConceptId: "II-40",
    title: "度数法を弧度法へ直す",
    prompt: "150°を弧度法で表したものはどれか。",
    options: ["2π/3", "5π/6", "3π/4", "5π/4"],
    answer: 1,
    explanation: "180°=πなので、150°=150π/180=5π/6。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-265",
    conceptIds: ["II-42"],
    primaryConceptId: "II-42",
    title: "三角恒等式の誤答を直す",
    prompt: "誤答分析：ある生徒が「1+tan^2θ=secθ」と書いた。正しい右辺に直したものはどれか。",
    options: ["sinθ", "cosθ", "sec^2θ", "csc^2θ"],
    answer: 2,
    explanation: "基本恒等式は1+tan^2θ=sec^2θ。右辺の平方を落としているのが誤りで、secθではない。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-266",
    conceptIds: ["II-43"],
    primaryConceptId: "II-43",
    title: "加法定理を条件に適用する",
    prompt: "α,βがともに鋭角で、sinα=3/5、cosβ=12/13である。sin(α+β)の値はどれか。",
    options: ["36/65", "44/65", "52/65", "56/65"],
    answer: 3,
    explanation: "鋭角なのでcosα=4/5、sinβ=5/13。加法定理よりsin(α+β)=3/5×12/13+4/5×5/13=56/65。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "X4-267",
    conceptIds: ["II-44"],
    primaryConceptId: "II-44",
    title: "倍角公式で値を求める",
    prompt: "θが鋭角でcosθ=3/5のとき、cos2θの値はどれか。",
    options: ["−7/25", "7/25", "9/25", "18/25"],
    answer: 0,
    explanation: "cos2θ=2cos^2θ−1=2×(3/5)^2−1=18/25−25/25=−7/25。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-268",
    conceptIds: ["II-45"],
    primaryConceptId: "II-45",
    title: "三角式の合成で最大値を読む",
    prompt: "xが実数全体を動くとき、3sinx+4cosxの最大値はどれか。",
    options: ["3", "4", "5", "7"],
    answer: 2,
    explanation: "3sinx+4cosxはRsin(x+φ)の形に合成でき、R=√(3^2+4^2)=5。sinの最大値1より最大値は5。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-269",
    conceptIds: ["II-46", "II-49"],
    primaryConceptId: "II-46",
    title: "グラフ変換後の特徴を読む",
    prompt: "y=sinxを、横方向にπ/3だけ右へ、縦方向に2倍してから上へ1だけ移したグラフの式はどれか。",
    options: ["y=2sin(x+π/3)+1", "y=2sin(x−π/3)+1", "y=sin(2x−π/3)+1", "y=2sinx−π/3+1"],
    answer: 1,
    explanation: "右へπ/3の移動はxをx−π/3に置き換え、縦2倍と上へ1を加えるのでy=2sin(x−π/3)+1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-270",
    conceptIds: ["II-48", "II-41"],
    primaryConceptId: "II-48",
    title: "単位円から三角不等式の範囲を読む",
    prompt: "0≦x<2πのとき、sinx≧1/2を満たすxの範囲はどれか。",
    options: ["0≦x≦π/6", "π/6≦x≦π/2", "π/6≦x≦5π/6", "5π/6≦x<2π"],
    answer: 2,
    explanation: "sinx=1/2となるのはπ/6と5π/6で、その間の第1・第2象限でsinxは1/2以上になる。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-271",
    conceptIds: ["II-49", "II-46"],
    primaryConceptId: "II-49",
    title: "周期表からモデルを読み取る",
    prompt: "時刻tと値yの表が、t=0,π/2,π,3π/2に対してy=2,5,2,−1となっている。モデルy=2+3sintで、t=5π/2の値はどれか。",
    options: ["−1", "0", "2", "5"],
    answer: 3,
    explanation: "5π/2はπ/2と同じ位置なのでsin(5π/2)=1。よってy=2+3×1=5。表の中心2、振幅3、周期2πを読み取る。",
    kind: "standard",
    estimatedSeconds: 70,
  },

  // 数学II：微分・積分
  {
    id: "X4-272",
    conceptIds: ["II-50"],
    primaryConceptId: "II-50",
    title: "平均変化率を表から求める",
    prompt: "関数f(x)=x^2について、x=1からx=3までの平均変化率はどれか。",
    options: ["2", "4", "8", "9"],
    answer: 1,
    explanation: "平均変化率は(f(3)−f(1))/(3−1)=(9−1)/2=4。2点を結ぶ直線の傾きにあたる。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-273",
    conceptIds: ["II-51"],
    primaryConceptId: "II-51",
    title: "接線の傾きを瞬間変化率で読む",
    prompt: "f(x)=x^2+3xとする。x=2における曲線の接線の傾きはどれか。",
    options: ["3", "5", "7", "10"],
    answer: 2,
    explanation: "f'(x)=2x+3なので、x=2での瞬間変化率はf'(2)=7。接線の傾きは導関数の値である。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-274",
    conceptIds: ["II-52"],
    primaryConceptId: "II-52",
    title: "多項式の導関数を選ぶ",
    prompt: "P(x)=x^4−3x^2+2x−1の導関数P'(x)はどれか。",
    options: ["4x^3−6x+2", "4x^3−3x+2", "x^3−6x+2", "4x^3−6x−1"],
    answer: 0,
    explanation: "項別に微分すると、x^4は4x^3、−3x^2は−6x、2xは2、定数−1は0になる。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-275",
    conceptIds: ["II-53", "II-51"],
    primaryConceptId: "II-53",
    title: "接点の座標から接線を立てる",
    prompt: "f(x)=x^2−4x+1のx=3における接線の方程式はどれか。",
    options: ["y=2x−4", "y=2x−6", "y=2x−7", "y=2x−8"],
    answer: 3,
    explanation: "f(3)=−2、f'(x)=2x−4よりf'(3)=2。接線はy+2=2(x−3)なのでy=2x−8。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-276",
    conceptIds: ["II-54"],
    primaryConceptId: "II-54",
    title: "導関数の符号表から減少区間を読む",
    prompt: "f'(x)=(x−1)(x+2)である。f(x)が減少する区間はどれか。",
    options: ["x<−2", "−2<x<1", "x>1", "すべての実数"],
    answer: 1,
    explanation: "積の符号はx<−2で正、−2<x<1で負、x>1で正。導関数が負の区間−2<x<1でfは減少する。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-277",
    conceptIds: ["II-55", "II-54"],
    primaryConceptId: "II-55",
    title: "極値の候補を比較する",
    prompt: "f(x)=x^3−3xについて、x=1における極小値はどれか。",
    options: ["−2", "−1", "1", "2"],
    answer: 0,
    explanation: "f'(x)=3x^2−3=3(x−1)(x+1)。x=1の前後で導関数は負から正へ変わるので極小。f(1)=1−3=−2。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-278",
    conceptIds: ["II-57"],
    primaryConceptId: "II-57",
    title: "面積モデルを最大化する",
    prompt: "縦x、横10−2xの長方形を作る。ただし0<x<5とする。面積が最大になるxはどれか。",
    options: ["1", "2", "5/2", "4"],
    answer: 2,
    explanation: "面積S=x(10−2x)=−2x^2+10x。S'=−4x+10=0よりx=5/2。二次関数の頂点で最大になる。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "X4-279",
    conceptIds: ["II-58"],
    primaryConceptId: "II-58",
    title: "導関数から原始関数を復元する",
    prompt: "∫(3x^2−4x+1)dxとして正しいものはどれか。",
    options: ["3x^3−4x^2+x+C", "x^3−4x^2+x+C", "x^3−2x^2+x+C", "x^3−2x^2+C"],
    answer: 2,
    explanation: "各項を積分すると3x^2はx^3、−4xは−2x^2、1はx。最後に積分定数Cを加える。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-280",
    conceptIds: ["II-59"],
    primaryConceptId: "II-59",
    title: "原始関数の差で定積分を求める",
    prompt: "F'(x)=f(x)、F(1)=2、F(4)=11が成り立つとき、∫[1,4]f(x)dxの値はどれか。",
    options: ["7", "8", "9", "13"],
    answer: 2,
    explanation: "微積分の基本的な関係より∫[1,4]f(x)dx=F(4)−F(1)=11−2=9。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-281",
    conceptIds: ["II-60"],
    primaryConceptId: "II-60",
    title: "曲線下の面積を積分で読む",
    prompt: "0≦x≦3で、曲線y=2xとx軸に囲まれる部分の面積はどれか。",
    options: ["6", "9", "12", "18"],
    answer: 1,
    explanation: "面積は∫[0,3]2x dx=[x^2][0,3]=9。底辺6、高さ6の三角形の面積(1/2)×3×6としても確認できる。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-282",
    conceptIds: ["II-61"],
    primaryConceptId: "II-61",
    title: "2曲線の上下関係を確認して面積を求める",
    prompt: "0≦x≦1で、曲線y=xとy=x^2に囲まれる部分の面積はどれか。",
    options: ["1/6", "1/4", "1/3", "1/2"],
    answer: 0,
    explanation: "この区間ではx≧x^2なので、面積は∫[0,1](x−x^2)dx=[x^2/2−x^3/3][0,1]=1/6。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-283",
    conceptIds: ["II-62"],
    primaryConceptId: "II-62",
    title: "位置の表から速度の符号を読む",
    prompt: "物体の位置がs(t)=t^3−3t^2+2tで表される。t=1での速度と運動の向きはどれか。",
    options: ["速度−1で、負の向き", "速度0で、停止", "速度1で、正の向き", "速度2で、正の向き"],
    answer: 0,
    explanation: "速度はs'(t)=3t^2−6t+2。s'(1)=3−6+2=−1なので、速度は−1、負の向きに動いている。",
    kind: "transfer",
    estimatedSeconds: 70,
  },

  // 数学B・C・III
  {
    id: "X4-284",
    conceptIds: ["B-03", "B-01"],
    primaryConceptId: "B-03",
    title: "等差数列の表を一般項へつなぐ",
    prompt: "等差数列でa_1=5、隣り合う項の差が3である。a_10はどれか。",
    options: ["27", "30", "32", "35"],
    answer: 2,
    explanation: "等差数列の一般項はa_n=a_1+(n−1)d。a_10=5+9×3=32。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-285",
    conceptIds: ["B-19", "B-20"],
    primaryConceptId: "B-19",
    title: "二項分布の確率表を計算する",
    prompt: "成功確率0.2の試行を5回独立に行う。成功回数がちょうど1回となる確率はどれか。",
    options: ["0.32768", "0.4096", "0.512", "0.8"],
    answer: 1,
    explanation: "5回から成功する1回を選ぶので5通り。確率は5×0.2×0.8^4=0.4096。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "X4-286",
    conceptIds: ["B-22", "B-23"],
    primaryConceptId: "B-23",
    title: "正規分布を標準化する",
    prompt: "確率変数Xが平均50、標準偏差5の正規分布に従う。45≦X≦55は、標準正規変数Zの範囲でどれか。",
    options: ["−2≦Z≦2", "−1≦Z≦0", "−1≦Z≦1", "0≦Z≦1"],
    answer: 2,
    explanation: "Z=(X−50)/5。X=45ではZ=−1、X=55ではZ=1なので、範囲は−1≦Z≦1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-287",
    conceptIds: ["C-05", "C-03", "C-04"],
    primaryConceptId: "C-05",
    title: "ベクトルの成分表を計算する",
    prompt: "u=(2,−1)、v=(−3,4)のとき、2u−vはどれか。",
    options: ["(1,3)", "(−1,2)", "(4,−2)", "(7,−6)"],
    answer: 3,
    explanation: "2u=(4,−2)なので、2u−v=(4,−2)−(−3,4)=(7,−6)。成分ごとに計算する。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-288",
    conceptIds: ["C-29", "C-21"],
    primaryConceptId: "C-29",
    title: "複素数平面の軌跡を円として読む",
    prompt: "z=x+yiが|z−(2+i)|=3を満たして動くとき、その軌跡はどれか。",
    options: ["中心(2,1)、半径3の円", "中心(−2,−1)、半径3の円", "中心(2,−1)、半径9の円", "直線x=2"],
    answer: 0,
    explanation: "z−(2+i)は点(2,1)からの差を表す。絶対値が3なので、中心(2,1)、半径3の円になる。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "X4-289",
    conceptIds: ["III-30", "II-58"],
    primaryConceptId: "III-30",
    title: "置換積分で指数関数を処理する",
    prompt: "∫[0,1]2x e^(x^2)dxの値はどれか。",
    options: ["1", "e", "e−1", "e^2−1"],
    answer: 2,
    explanation: "u=x^2とおくとdu=2x dx。積分区間はu=0から1になり、∫[0,1]e^u du=e−1。",
    kind: "standard",
    estimatedSeconds: 75,
  },
];
