import type { Problem } from "../problem-bank";

/**
 * 問題4倍化・第3バッチ。
 * 数学II・B・Cを中心に、式だけでなく図形・表・状況文への読み替えを問う
 * オリジナルの共通テスト型問題。quick / standard / transfer を34/33/33問で収録する。
 */
export const problemExpansionBatch03: Problem[] = [
  // quick: X4-176〜X4-209
  {
    id: "X4-176",
    conceptIds: ["II-05"],
    primaryConceptId: "II-05",
    title: "割り算を代入に読み替える",
    prompt: "多項式P(x)=2x^3−3x+1をx−2で割ったときの余りはどれか。",
    options: ["11", "9", "7", "5"],
    answer: 0,
    explanation: "剰余定理より余りはP(2)。2×2^3−3×2+1=16−6+1=11。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-177",
    conceptIds: ["II-06", "II-07"],
    primaryConceptId: "II-06",
    title: "根を因数へ読み替える",
    prompt: "P(x)=x^3−4x^2+x+6について、P(a)=0となる整数aはどれか。",
    options: ["a=−3", "a=−2", "a=1", "a=2"],
    answer: 3,
    explanation: "P(2)=8−16+2+6=0。したがって因数x−2をもつので、a=2。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-178",
    conceptIds: ["II-08", "II-09"],
    primaryConceptId: "II-08",
    title: "実部と虚部を別々に計算する",
    prompt: "複素数(2+3i)+(1−5i)をa+biの形に表したとき、(a,b)はどれか。",
    options: ["(3,−2)", "(1,−2)", "(3,8)", "(−1,2)"],
    answer: 0,
    explanation: "実部どうし、虚部どうしを足す。(2+1)+(3−5)i=3−2iなので(a,b)=(3,−2)。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-179",
    conceptIds: ["II-10"],
    primaryConceptId: "II-10",
    title: "共役との積を距離へ読み替える",
    prompt: "(3+2i)(3−2i)の値はどれか。",
    options: ["5", "9", "13", "17"],
    answer: 2,
    explanation: "共役との積なので3^2+2^2=9+4=13。展開しても9−6i+6i−4i^2=13となる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-180",
    conceptIds: ["II-16"],
    primaryConceptId: "II-16",
    title: "座標表を距離へ読み替える",
    prompt: "座標平面上のA(1,−2), B(4,2)間の距離はどれか。",
    options: ["4", "5", "6", "√13"],
    answer: 1,
    explanation: "横の差は3、縦の差は4なので、距離は√(3^2+4^2)=5。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-181",
    conceptIds: ["II-17"],
    primaryConceptId: "II-17",
    title: "点と傾きを直線へ読み替える",
    prompt: "点(2,−1)を通り、傾き3の直線の方程式はどれか。",
    options: ["y=3x−7", "y=3x+5", "y=−3x+5", "y=2x−1"],
    answer: 0,
    explanation: "点傾き式y+1=3(x−2)を整理して、y=3x−7。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-182",
    conceptIds: ["II-19"],
    primaryConceptId: "II-19",
    title: "方程式を円の情報へ読み替える",
    prompt: "x^2+y^2−4x+6y−12=0で表される円の半径はどれか。",
    options: ["3", "4", "5", "6"],
    answer: 2,
    explanation: "平方完成すると(x−2)^2+(y+3)^2=25。半径は√25=5。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-183",
    conceptIds: ["II-21"],
    primaryConceptId: "II-21",
    title: "直線までの距離を図形へ読み替える",
    prompt: "原点と直線3x+4y−12=0との距離はどれか。",
    options: ["1/5", "2", "12/5", "5"],
    answer: 2,
    explanation: "点と直線の距離公式より|−12|/√(3^2+4^2)=12/5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-184",
    conceptIds: ["II-30"],
    primaryConceptId: "II-30",
    title: "有理数指数を根号へ読み替える",
    prompt: "8^(2/3)の値はどれか。",
    options: ["2", "4", "8", "16"],
    answer: 1,
    explanation: "8^(2/3)=(³√8)^2=2^2=4。先に分母の3を根号として読む。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-185",
    conceptIds: ["II-34"],
    primaryConceptId: "II-34",
    title: "対数を指数へ読み替える",
    prompt: "log_3(1/9)の値はどれか。",
    options: ["−3", "−2", "−1", "2"],
    answer: 1,
    explanation: "1/9=3^(−2)なので、log_3(1/9)=−2。真数が正であることも確認する。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-186",
    conceptIds: ["B-03"],
    primaryConceptId: "B-03",
    title: "表の差を公差へ読み替える",
    prompt: "初項5、公差3の等差数列の第10項はどれか。",
    options: ["29", "30", "32", "35"],
    answer: 2,
    explanation: "a_10=5+(10−1)×3=5+27=32。公差を10倍しないことに注意する。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-187",
    conceptIds: ["B-04"],
    primaryConceptId: "B-04",
    title: "並びを等差数列の和へ読み替える",
    prompt: "2+5+8+…+29の値はどれか。",
    options: ["145", "150", "155", "160"],
    answer: 2,
    explanation: "項数は2+(n−1)×3=29よりn=10。平均(2+29)/2に10を掛けて155。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-188",
    conceptIds: ["B-05"],
    primaryConceptId: "B-05",
    title: "倍率を公比へ読み替える",
    prompt: "初項3、公比2の等比数列の第6項はどれか。",
    options: ["48", "64", "96", "192"],
    answer: 2,
    explanation: "a_6=3×2^(6−1)=3×32=96。第6項では公比を5回掛ける。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-189",
    conceptIds: ["B-06"],
    primaryConceptId: "B-06",
    title: "等比の並びを合計へ読み替える",
    prompt: "1+2+4+8+16+32の値はどれか。",
    options: ["31", "48", "63", "64"],
    answer: 2,
    explanation: "初項1、公比2、6項の和なので(2^6−1)/(2−1)=63。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-190",
    conceptIds: ["B-07"],
    primaryConceptId: "B-07",
    title: "Σを項の合計へ読み替える",
    prompt: "Σ[k=1から4](2k+1)の値はどれか。",
    options: ["20", "22", "24", "26"],
    answer: 2,
    explanation: "(2×1+1)+(2×2+1)+(2×3+1)+(2×4+1)=3+5+7+9=24。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-191",
    conceptIds: ["B-08"],
    primaryConceptId: "B-08",
    title: "漸化式を反復計算へ読み替える",
    prompt: "a_1=2, a_(n+1)=a_n+3で定める数列のa_5はどれか。",
    options: ["11", "12", "14", "17"],
    answer: 2,
    explanation: "2,5,8,11,14と順に3ずつ増えるのでa_5=14。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-192",
    conceptIds: ["B-15"],
    primaryConceptId: "B-15",
    title: "欠けた確率を表から読む",
    prompt: "確率変数Xが0,1,2をとり、P(X=0)=0.2, P(X=1)=0.5である。P(X=2)はどれか。",
    options: ["0.2", "0.3", "0.5", "0.7"],
    answer: 1,
    explanation: "確率の合計は1なので、P(X=2)=1−0.2−0.5=0.3。値の合計ではない。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-193",
    conceptIds: ["B-16"],
    primaryConceptId: "B-16",
    title: "確率分布を重み付き平均へ読み替える",
    prompt: "P(X=0)=0.2, P(X=1)=0.5, P(X=2)=0.3のとき、E(X)はどれか。",
    options: ["0.8", "1.0", "1.1", "1.3"],
    answer: 2,
    explanation: "E(X)=0×0.2+1×0.5+2×0.3=0.5+0.6=1.1。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-194",
    conceptIds: ["B-18"],
    primaryConceptId: "B-18",
    title: "変換後の平均と分散を読む",
    prompt: "E(X)=4, V(X)=9のときY=2X−1とする。E(Y), V(Y)の組はどれか。",
    options: ["(7,18)", "(7,36)", "(8,36)", "(9,18)"],
    answer: 1,
    explanation: "E(Y)=2E(X)−1=7、V(Y)=2^2V(X)=36。定数−1は分散を変えない。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-195",
    conceptIds: ["B-19"],
    primaryConceptId: "B-19",
    title: "成功回数を二項分布へ読み替える",
    prompt: "成功確率1/2の独立な試行を4回行う。成功がちょうど2回の確率はどれか。",
    options: ["1/8", "1/4", "3/8", "1/2"],
    answer: 2,
    explanation: "成功位置の選び方は4C2=6通りで、各場合の確率は(1/2)^4。よって6/16=3/8。",
    kind: "quick",
    estimatedSeconds: 65,
  },
  {
    id: "X4-196",
    conceptIds: ["C-03"],
    primaryConceptId: "C-03",
    title: "移動をベクトルの和へ読み替える",
    prompt: "u=(2,−1), v=(−3,4)のときu+vはどれか。",
    options: ["(−1,3)", "(5,−5)", "(−1,−5)", "(1,3)"],
    answer: 0,
    explanation: "成分ごとに足して(2−3,−1+4)=(−1,3)。長さを足す問題ではない。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-197",
    conceptIds: ["C-05", "C-06"],
    primaryConceptId: "C-05",
    title: "座標差をベクトルへ読み替える",
    prompt: "A(−1,3)からB(4,−2)へ向かうベクトルABはどれか。",
    options: ["(−5,5)", "(3,1)", "(5,−5)", "(4,−2)"],
    answer: 2,
    explanation: "終点−始点なのでAB=(4−(−1),−2−3)=(5,−5)。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-198",
    conceptIds: ["C-10"],
    primaryConceptId: "C-10",
    title: "内積を成分の積の和へ読み替える",
    prompt: "u=(1,2), v=(3,−1)の内積u・vはどれか。",
    options: ["−5", "−1", "1", "5"],
    answer: 2,
    explanation: "u・v=1×3+2×(−1)=3−2=1。内積の結果はベクトルではなく数。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-199",
    conceptIds: ["C-11"],
    primaryConceptId: "C-11",
    title: "成分をベクトルの大きさへ読み替える",
    prompt: "u=(−6,8)の大きさ|u|はどれか。",
    options: ["2", "10", "14", "100"],
    answer: 1,
    explanation: "|u|=√{(−6)^2+8^2}=√100=10。成分の絶対値を足すのではない。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-200",
    conceptIds: ["C-14"],
    primaryConceptId: "C-14",
    title: "ベクトルを三角形の面積へ読み替える",
    prompt: "|u|=4, |v|=5で、uとvのなす角が30°のとき、uとvが作る三角形の面積はどれか。",
    options: ["5", "10", "20", "40"],
    answer: 0,
    explanation: "三角形の面積は(1/2)|u||v|sin30°=(1/2)×4×5×(1/2)=5。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "X4-201",
    conceptIds: ["C-15"],
    primaryConceptId: "C-15",
    title: "空間座標を距離へ読み替える",
    prompt: "空間内のA(1,−2,3), B(4,2,3)間の距離はどれか。",
    options: ["4", "5", "√34", "9"],
    answer: 1,
    explanation: "差は(3,4,0)なので距離は√(3^2+4^2+0^2)=5。z成分は今回は0だが、三成分で確認する。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-202",
    conceptIds: ["C-21"],
    primaryConceptId: "C-21",
    title: "複素数を平面上の点へ読み替える",
    prompt: "複素数z=−2+3iに対応する複素平面上の点はどれか。",
    options: ["(3,−2)", "(−2,3)", "(2,−3)", "(−3,2)"],
    answer: 1,
    explanation: "実部が横座標、iの係数である虚部3が縦座標なので(−2,3)。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-203",
    conceptIds: ["C-22"],
    primaryConceptId: "C-22",
    title: "複素数を距離と対称点へ読み替える",
    prompt: "z=3−4iについて、|z|と共役zバーの組はどれか。",
    options: ["(5,3+4i)", "(5,3−4i)", "(7,3+4i)", "(5,−3+4i)"],
    answer: 0,
    explanation: "|z|=√(3^2+(−4)^2)=5、共役は虚部の符号だけを変えた3+4i。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-204",
    conceptIds: ["C-27"],
    primaryConceptId: "C-27",
    title: "極形式の累乗を回転へ読み替える",
    prompt: "(cos(π/6)+i sin(π/6))^3の値はどれか。",
    options: ["1", "i", "−1", "−i"],
    answer: 1,
    explanation: "ド・モアブルの定理よりcos(π/2)+i sin(π/2)=i。偏角は3倍になる。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-205",
    conceptIds: ["II-40"],
    primaryConceptId: "II-40",
    title: "度数法を弧度法へ読み替える",
    prompt: "150°を弧度法で表したものはどれか。",
    options: ["2π/3", "3π/4", "5π/6", "7π/6"],
    answer: 2,
    explanation: "150×π/180=5π/6。度にπ/180を掛ける。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "X4-206",
    conceptIds: ["II-41"],
    primaryConceptId: "II-41",
    title: "単位円を座標へ読み替える",
    prompt: "θ=5π/6のときsinθの値はどれか。",
    options: ["−√3/2", "−1/2", "1/2", "√3/2"],
    answer: 2,
    explanation: "5π/6は第2象限で、基準角π/6。sinは正でsin(π/6)=1/2。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-207",
    conceptIds: ["II-52"],
    primaryConceptId: "II-52",
    title: "変化率を導関数へ読み替える",
    prompt: "f(x)=3x^4−2x+1の導関数f'(x)はどれか。",
    options: ["3x^3−2", "12x^3−2", "12x^4−2", "4x^3−2x"],
    answer: 1,
    explanation: "各項を微分して12x^3−2。定数1の微分は0。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "X4-208",
    conceptIds: ["II-58"],
    primaryConceptId: "II-58",
    title: "累積量を原始関数へ読み替える",
    prompt: "∫[0から2](x+1)dxの値はどれか。",
    options: ["2", "3", "4", "5"],
    answer: 2,
    explanation: "原始関数はx^2/2+x。値の差は(2+2)−0=4。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "X4-209",
    conceptIds: ["II-60"],
    primaryConceptId: "II-60",
    title: "グラフを面積へ読み替える",
    prompt: "0≤x≤1で、y=xとy=x^2に囲まれる部分の面積はどれか。",
    options: ["1/12", "1/6", "1/3", "1/2"],
    answer: 1,
    explanation: "区間内ではxが上、x^2が下。面積は∫[0から1](x−x^2)dx=1/2−1/3=1/6。",
    kind: "quick",
    estimatedSeconds: 65,
  },
];
