export type Problem = {
  id: string;
  conceptIds: string[];
  title: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  kind: "quick" | "standard" | "transfer";
  estimatedSeconds: number;
};

// オリジナルの確認問題。公式過去問は問題文を転載せず、出題構造だけを別途参照する。
export const problemBank: Problem[] = [
  {
    id: "Q-F02-01",
    conceptIds: ["F-02"],
    title: "符号の基本",
    prompt: "(-3) - (-8) の値は？",
    options: ["-11", "-5", "5", "11"],
    answer: 2,
    explanation: "負の数を引くことは、反対の数を足すこと。(-3)+8=5。",
    kind: "quick",
    estimatedSeconds: 35,
  },
  {
    id: "Q-F05-01",
    conceptIds: ["F-05", "I-11"],
    title: "平方根",
    prompt: "√72を最も簡単な形にすると？",
    options: ["2√18", "3√8", "6√2", "12√2"],
    answer: 2,
    explanation: "72=36×2なので、√72=6√2。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I07-01",
    conceptIds: ["I-07", "I-19"],
    title: "絶対値を距離として読む",
    prompt: "数直線上で、点xと点3の距離が5である。xの値は？",
    options: ["x=8のみ", "x=-2のみ", "x=-2または8", "x=2または8"],
    answer: 2,
    explanation: "|x-3|=5。距離なので右へ5の8と、左へ5の-2がある。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I08-01",
    conceptIds: ["I-08"],
    title: "展開公式",
    prompt: "(2x-3)²を展開した式は？",
    options: ["4x²-9", "4x²-6x+9", "4x²-12x+9", "2x²-12x+9"],
    answer: 2,
    explanation: "(a-b)²=a²-2ab+b²。a=2x,b=3を代入する。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I09-01",
    conceptIds: ["I-09", "F-08"],
    title: "因数分解",
    prompt: "x²-7x+12を因数分解すると？",
    options: ["(x-2)(x-6)", "(x+3)(x+4)", "(x-3)(x-4)", "(x+2)(x-6)"],
    answer: 2,
    explanation: "積が12、和が-7になる-3と-4を使う。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-I14-01",
    conceptIds: ["I-14", "I-15"],
    title: "二次方程式",
    prompt: "2x²-5x-3=0の解は？",
    options: ["x=3,-1/2", "x=-3,1/2", "x=1,3", "x=-1,-3"],
    answer: 0,
    explanation: "(2x+1)(x-3)=0より、x=3,-1/2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I16-01",
    conceptIds: ["I-16", "I-31"],
    title: "判別式",
    prompt: "x²+4x+k=0が異なる2つの実数解をもつ条件は？",
    options: ["k<4", "k=4", "k>4", "k≤4"],
    answer: 0,
    explanation: "判別式D=16-4k。D>0なのでk<4。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I18-01",
    conceptIds: ["I-18", "F-11"],
    title: "一次不等式",
    prompt: "3-2x<9を満たすxの範囲は？",
    options: ["x<-3", "x>-3", "x<3", "x>3"],
    answer: 1,
    explanation: "-2x<6。負の数で割るので不等号が反転し、x>-3。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I20-01",
    conceptIds: ["I-20", "I-21"],
    title: "二次不等式",
    prompt: "x²-5x+6≤0を満たすxの範囲は？",
    options: ["x≤2またはx≥3", "2≤x≤3", "x<2またはx>3", "-3≤x≤-2"],
    answer: 1,
    explanation: "(x-2)(x-3)≤0。上に開く放物線なので、2と3の間。",
    kind: "standard",
    estimatedSeconds: 90,
  },
  {
    id: "Q-I26-01",
    conceptIds: ["I-25", "I-26"],
    title: "頂点と軸",
    prompt: "y=x²-6x+11の頂点は？",
    options: ["(3,2)", "(-3,2)", "(3,11)", "(-3,11)"],
    answer: 0,
    explanation: "y=(x-3)²+2。頂点は(3,2)。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I29-01",
    conceptIds: ["I-28", "I-29"],
    title: "区間上の最大最小",
    prompt: "0≤x≤4で、y=(x-1)²+2の最小値は？",
    options: ["0", "1", "2", "3"],
    answer: 2,
    explanation: "頂点x=1が区間内にあり、最小値は2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I34-01",
    conceptIds: ["I-30", "I-31", "I-34"],
    title: "式とグラフの接続",
    prompt: "y=x²-4x+3とx軸の共有点の個数は？",
    options: ["0個", "1個", "2個", "3個"],
    answer: 2,
    explanation: "x²-4x+3=(x-1)(x-3)。共有点はx=1,3の2個。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I45-01",
    conceptIds: ["I-45", "I-46"],
    title: "四分位範囲",
    prompt: "データ1,2,3,5,8,10,12の中央値は？",
    options: ["3", "5", "6", "8"],
    answer: 1,
    explanation: "7個の中央、4番目の値が中央値なので5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A05-01",
    conceptIds: ["A-04", "A-05"],
    title: "順列と組合せ",
    prompt: "5人から委員長と副委員長を1人ずつ選ぶ方法は何通り？",
    options: ["5", "10", "20", "25"],
    answer: 2,
    explanation: "役職が異なるので順序を区別する。5P2=5×4=20。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-A13-01",
    conceptIds: ["A-13", "A-14"],
    title: "条件付き確率",
    prompt: "赤2個、青3個の袋から1個取り出した。赤だったとき、次に赤を引く確率は？（戻さない）",
    options: ["1/5", "1/4", "1/2", "2/5"],
    answer: 1,
    explanation: "赤を1個使った後は赤1個・青3個の計4個。1/4。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-II30-01",
    conceptIds: ["II-30", "II-31"],
    title: "指数方程式",
    prompt: "2^x=8を満たすxは？",
    options: ["2", "3", "4", "8"],
    answer: 1,
    explanation: "8=2^3なので、底をそろえるとx=3。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II36-01",
    conceptIds: ["II-35", "II-36"],
    title: "対数の読み替え",
    prompt: "log₂8の値は？",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "log₂8は2を何乗すると8になるかを表す。2³=8なので3。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II43-01",
    conceptIds: ["II-41", "II-43"],
    title: "三角関数の加法定理",
    prompt: "sin30°cos60°+cos30°sin60°の値は？",
    options: ["0", "1/2", "1", "√3/2"],
    answer: 2,
    explanation: "sin(30°+60°)にまとめられるので、sin90°=1。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-II57-01",
    conceptIds: ["II-55", "II-57"],
    title: "微分と最小値",
    prompt: "f(x)=x²-4x+1の最小値をとるxは？",
    options: ["0", "1", "2", "4"],
    answer: 2,
    explanation: "f'(x)=2x-4=0よりx=2。上に開く二次関数なので最小。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-II59-01",
    conceptIds: ["II-58", "II-59"],
    title: "定積分と面積",
    prompt: "∫₀² x dxの値は？",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "原始関数x²/2を0から2まで計算して2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-B04-01",
    conceptIds: ["B-03", "B-04"],
    title: "等差数列の和",
    prompt: "1+2+3+…+10の値は？",
    options: ["45", "50", "55", "60"],
    answer: 2,
    explanation: "初項1、末項10、項数10なので10(1+10)/2=55。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-B06-01",
    conceptIds: ["B-05", "B-06"],
    title: "等比数列の和",
    prompt: "1+2+4+8の値は？",
    options: ["7", "8", "15", "16"],
    answer: 2,
    explanation: "各項を順に足せば15。等比数列の和の公式でも確認できる。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-B16-01",
    conceptIds: ["B-15", "B-16"],
    title: "確率変数の期待値",
    prompt: "Xが0を確率1/2、2を確率1/2でとるとき、E(X)は？",
    options: ["0", "1/2", "1", "2"],
    answer: 2,
    explanation: "期待値は値×確率の合計。0×1/2+2×1/2=1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-B20-01",
    conceptIds: ["B-19", "B-20"],
    title: "二項分布の確率",
    prompt: "成功確率1/2の試行を3回行い、ちょうど2回成功する確率は？",
    options: ["1/8", "2/8", "3/8", "4/8"],
    answer: 2,
    explanation: "成功する回の選び方が3通りあり、各並びは(1/2)³。よって3/8。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-C10-01",
    conceptIds: ["C-05", "C-10"],
    title: "ベクトルの内積",
    prompt: "(1,2)・(3,-1)の値は？",
    options: ["-1", "0", "1", "5"],
    answer: 2,
    explanation: "成分ごとの積を足して1×3+2×(-1)=1。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-C21-01",
    conceptIds: ["C-21", "C-22"],
    title: "複素数平面",
    prompt: "複素数z=2+iに対応する点の座標は？",
    options: ["(1,2)", "(2,1)", "(-2,1)", "(2,-1)"],
    answer: 1,
    explanation: "実部がx座標、虚部の係数がy座標なので(2,1)。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-C29-01",
    conceptIds: ["C-22", "C-29"],
    title: "複素数の軌跡",
    prompt: "|z-1|=2が表す図形は？",
    options: ["中心1、半径2の円", "中心0、半径1の円", "直線x=1", "点z=2"],
    answer: 0,
    explanation: "|z-a|=rは、複素数平面で中心a、半径rの円を表す。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
];
