import { expansionIA } from "./content/expansion-ia";
import { expansionIIBC } from "./content/expansion-iibc";
import { gapC } from "./content/gap-c";
import { gapIIB } from "./content/gap-ii-b";

export type Problem = {
  id: string;
  conceptIds: string[];
  primaryConceptId?: string;
  title: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  kind: "quick" | "standard" | "transfer";
  estimatedSeconds: number;
};

// オリジナルの確認問題。公式過去問は問題文を転載せず、出題構造だけを別途参照する。
const baseProblemBank: Problem[] = [
  {
    id: "Q-F01-01",
    conceptIds: ["F-01"],
    title: "等号は関係を表す",
    prompt: "3 + 4 = 7 について、等号が表していることとして最も適切なのは？",
    options: ["左辺と右辺の値が等しい", "左辺を右辺に変形する記号", "7を3と4に分ける記号", "計算を必ず始める記号"],
    answer: 0,
    explanation: "等号は、左辺と右辺が同じ値であるという関係を表す。式を読むときは、等号の左右を同じものとして見る。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "Q-F02-01",
    conceptIds: ["F-02"],
    title: "符号の基本",
    prompt: "(-3) - (-8) の値は？",
    options: ["-11", "-5", "5", "11"],
    answer: 2,
    explanation: "負の数を引くことは、反対の数を足すこと。(-3)+8=5。",
    kind: "quick",
    estimatedSeconds: 35,
  },
  {
    id: "Q-I01-01",
    conceptIds: ["I-01"],
    title: "実数の分類",
    prompt: "次の数のうち、無理数はどれ？",
    options: ["-3", "0.25", "√2", "7/2"],
    answer: 2,
    explanation: "√2は整数の比で表せない無理数。整数・有限小数・分数は有理数に含まれる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I02-01",
    conceptIds: ["I-02"],
    title: "区間で表す",
    prompt: "-1以上3未満の実数xの範囲を、区間の記号で表すと？",
    options: ["(-1,3)", "[-1,3)", "(-1,3]", "[-1,3]"],
    answer: 1,
    explanation: "-1は含むので角括弧、3は含まないので丸括弧。したがって[-1,3)。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I03-01",
    conceptIds: ["I-03"],
    title: "集合の共通部分",
    prompt: "A={1,2,3}, B={2,3,4}のとき、A∩Bは？",
    options: ["{1,2,3,4}", "{1,4}", "{2,3}", "空集合"],
    answer: 2,
    explanation: "共通部分A∩Bは、AとBの両方に含まれる要素を集めるので{2,3}。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I04-01",
    conceptIds: ["I-04"],
    title: "命題の真偽",
    prompt: "命題『x=2ならばx²=4である』について正しいものは？",
    options: ["真である", "偽である", "xによって真偽が変わる", "命題ではない"],
    answer: 0,
    explanation: "x=2を代入するとx²=4。仮定を満たすすべての場合に結論が成り立つので真。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-I05-01",
    conceptIds: ["I-05"],
    title: "必要条件と十分条件",
    prompt: "方程式x²=4に対して、条件x=2はどのような条件？",
    options: ["必要条件だが十分条件ではない", "十分条件だが必要条件ではない", "必要十分条件", "どちらでもない"],
    answer: 1,
    explanation: "x=2ならx²=4なので十分。ただしx=-2でもx²=4なので必要ではない。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I06-01",
    conceptIds: ["I-06"],
    title: "反例を見つける",
    prompt: "『x²=1ならばx=1である』が偽であることを示す反例は？",
    options: ["x=0", "x=1", "x=-1", "x=2"],
    answer: 2,
    explanation: "x=-1でもx²=1だがx=1ではない。したがってこの命題の反例になる。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I10-01",
    conceptIds: ["I-10"],
    title: "分数式の約分",
    prompt: "x≠3のとき、(x²-9)/(x-3)を簡単にすると？",
    options: ["x-3", "x+3", "x²-3", "1"],
    answer: 1,
    explanation: "x²-9=(x-3)(x+3)。x≠3なのでx-3を約分でき、x+3。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-I13-01",
    conceptIds: ["I-13"],
    title: "式の値をまとめる",
    prompt: "a+b=5のとき、2a+2bの値は？",
    options: ["5", "7", "10", "25"],
    answer: 2,
    explanation: "2a+2b=2(a+b)=2×5=10。個別のa,bを求めなくてもよい。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I17-01",
    conceptIds: ["I-17"],
    title: "解と係数",
    prompt: "x²-5x+6=0の2解をα,βとすると、α+βとαβの組は？",
    options: ["(5,6)", "(-5,6)", "(5,-6)", "(-5,-6)"],
    answer: 0,
    explanation: "二次方程式x²+bx+c=0では、解の和=-b、積=c。よって(5,6)。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I22-01",
    conceptIds: ["I-22"],
    title: "定義域を読む",
    prompt: "f(x)=√(x-1)の定義域は？",
    options: ["x≤1", "x<1", "x≥1", "すべての実数"],
    answer: 2,
    explanation: "平方根の中身は0以上。x-1≥0よりx≥1。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I27-01",
    conceptIds: ["I-27"],
    title: "グラフの平行移動",
    prompt: "y=x²をx方向に2、y方向に3だけ平行移動した式は？",
    options: ["y=(x+2)²+3", "y=(x-2)²+3", "y=(x-2)²-3", "y=x²+2x+3"],
    answer: 1,
    explanation: "右へ2はxをx-2に、上へ3は+3に置き換えるのでy=(x-2)²+3。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-I43-01",
    conceptIds: ["I-46"],
    title: "平均値",
    prompt: "データ1,2,3,4,5の平均値は？",
    options: ["2", "2.5", "3", "3.5"],
    answer: 2,
    explanation: "合計15をデータ数5で割るので平均値は3。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-F05-01",
    conceptIds: ["F-05", "I-11"],
    primaryConceptId: "I-11",
    title: "平方根",
    prompt: "√72を最も簡単な形にすると？",
    options: ["2√18", "3√8", "6√2", "12√2"],
    answer: 2,
    explanation: "72=36×2なので、√72=6√2。2√18や3√8も同じ値だが、さらに簡単にできる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I07-01",
    conceptIds: ["I-07", "I-19"],
    primaryConceptId: "I-07",
    title: "絶対値を距離として読む",
    prompt: "数直線上で、点xと点3の距離が5である。xの値は？",
    options: ["x=8のみ", "x=-2のみ", "x=-2または8", "x=2または8"],
    answer: 2,
    explanation: "|x-3|=5。距離なので右へ5の8と、左へ5の-2がある。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I08-01",
    conceptIds: ["I-08"],
    title: "展開公式",
    prompt: "(2x-3)²を展開した式は？",
    options: ["4x²-9", "4x²-6x+9", "4x²-12x+9", "2x²-12x+9"],
    answer: 2,
    explanation: "(a-b)²=a²-2ab+b²。a=2x,b=3を代入する。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I09-01",
    conceptIds: ["I-09", "F-08"],
    primaryConceptId: "I-09",
    title: "因数分解",
    prompt: "x²-7x+12を因数分解すると？",
    options: ["(x-2)(x-6)", "(x+3)(x+4)", "(x-3)(x-4)", "(x+2)(x-6)"],
    answer: 2,
    explanation: "積が12、和が-7になる-3と-4を使う。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-I14-01",
    conceptIds: ["I-14"],
    primaryConceptId: "I-14",
    title: "二次方程式",
    prompt: "2x²-5x-3=0の解は？",
    options: ["x=3,-1/2", "x=-3,1/2", "x=1,3", "x=-1,-3"],
    answer: 0,
    explanation: "(2x+1)(x-3)=0より、x=3,-1/2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I16-01",
    conceptIds: ["I-16"],
    primaryConceptId: "I-16",
    title: "判別式",
    prompt: "x²+4x+k=0が異なる2つの実数解をもつ条件は？",
    options: ["k<4", "k=4", "k>4", "k≤4"],
    answer: 0,
    explanation: "判別式D=16-4k。D>0なのでk<4。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I18-01",
    conceptIds: ["I-18", "F-11"],
    primaryConceptId: "I-18",
    title: "一次不等式",
    prompt: "3-2x<9を満たすxの範囲は？",
    options: ["x<-3", "x>-3", "x<3", "x>3"],
    answer: 1,
    explanation: "-2x<6。負の数で割るので不等号が反転し、x>-3。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I20-01",
    conceptIds: ["I-20"],
    primaryConceptId: "I-20",
    title: "二次不等式",
    prompt: "x²-5x+6≤0を満たすxの範囲は？",
    options: ["x≤2またはx≥3", "2≤x≤3", "x<2またはx>3", "-3≤x≤-2"],
    answer: 1,
    explanation: "(x-2)(x-3)≤0。上に開く放物線なので、2以上3以下（端点を含む）。",
    kind: "standard",
    estimatedSeconds: 90,
  },
  {
    id: "Q-I26-01",
    conceptIds: ["I-25", "I-26"],
    primaryConceptId: "I-26",
    title: "頂点と軸",
    prompt: "y=x²-6x+11の頂点は？",
    options: ["(3,2)", "(-3,2)", "(3,11)", "(-3,11)"],
    answer: 0,
    explanation: "y=(x-3)²+2。頂点は(3,2)。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I29-01",
    conceptIds: ["I-28", "I-29"],
    primaryConceptId: "I-29",
    title: "区間上の最大最小",
    prompt: "0≤x≤4で、y=(x-1)²+2の最小値は？",
    options: ["0", "1", "2", "3"],
    answer: 2,
    explanation: "頂点x=1が区間内にあり、最小値は2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I34-01",
    conceptIds: ["I-34"],
    primaryConceptId: "I-34",
    title: "式とグラフの接続",
    prompt: "y=x²-4x+3とx軸の共有点の個数は？",
    options: ["0個", "1個", "2個", "3個"],
    answer: 2,
    explanation: "x²-4x+3=(x-1)(x-3)。共有点のx座標は1,3なので2個。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I45-01",
    conceptIds: ["I-46"],
    primaryConceptId: "I-46",
    title: "中央値",
    prompt: "データ1,2,3,5,8,10,12の中央値は？",
    options: ["3", "5", "6", "8"],
    answer: 1,
    explanation: "7個の中央、4番目の値が中央値なので5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A05-01",
    conceptIds: ["A-04"],
    primaryConceptId: "A-04",
    title: "順列と組合せ",
    prompt: "5人から委員長と副委員長を1人ずつ選ぶ方法は何通り？",
    options: ["5", "10", "20", "25"],
    answer: 2,
    explanation: "役職が異なるので順序を区別する。5P2=5×4=20。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-A13-01",
    conceptIds: ["A-13"],
    primaryConceptId: "A-13",
    title: "条件付き確率",
    prompt: "赤2個、青3個の袋から1個取り出した。赤だったとき、次に赤を引く確率は？（戻さない）",
    options: ["1/5", "1/4", "1/2", "2/5"],
    answer: 1,
    explanation: "赤を1個使った後は赤1個・青3個の計4個。1/4。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-II30-01",
    conceptIds: ["II-32"],
    primaryConceptId: "II-32",
    title: "指数方程式",
    prompt: "2^x=8を満たすxは？",
    options: ["2", "3", "4", "8"],
    answer: 1,
    explanation: "8=2^3なので、底をそろえるとx=3。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II36-01",
    conceptIds: ["II-34"],
    primaryConceptId: "II-34",
    title: "対数の読み替え",
    prompt: "log₂8の値は？",
    options: ["1", "2", "3", "4"],
    answer: 2,
    explanation: "log₂8は2を何乗すると8になるかを表す。2³=8なので3。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II43-01",
    conceptIds: ["II-43"],
    primaryConceptId: "II-43",
    title: "三角関数の加法定理",
    prompt: "sin30°cos60°+cos30°sin60°の値は？",
    options: ["0", "1/2", "1", "√3/2"],
    answer: 2,
    explanation: "sin(30°+60°)にまとめられるので、sin90°=1。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-II57-01",
    conceptIds: ["II-55", "II-57"],
    primaryConceptId: "II-57",
    title: "微分と最小値",
    prompt: "f(x)=x²-4x+1の最小値をとるxは？",
    options: ["0", "1", "2", "4"],
    answer: 2,
    explanation: "f'(x)=2x-4=0よりx=2。上に開く二次関数なので最小。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-II59-01",
    conceptIds: ["II-58", "II-59"],
    primaryConceptId: "II-59",
    title: "定積分と面積",
    prompt: "∫₀² x dxの値は？",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "原始関数x²/2を0から2まで計算して2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-B04-01",
    conceptIds: ["B-03", "B-04"],
    primaryConceptId: "B-04",
    title: "等差数列の和",
    prompt: "1+2+3+…+10の値は？",
    options: ["45", "50", "55", "60"],
    answer: 2,
    explanation: "初項1、末項10、項数10なので10(1+10)/2=55。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-B06-01",
    conceptIds: ["B-05", "B-06"],
    primaryConceptId: "B-06",
    title: "等比数列の和",
    prompt: "1+2+4+8+16+32の値は？",
    options: ["31", "63", "64", "127"],
    answer: 1,
    explanation: "初項1、公比2、6項の等比数列。和の公式より(2⁶-1)/(2-1)=63。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-B16-01",
    conceptIds: ["B-15", "B-16"],
    primaryConceptId: "B-16",
    title: "確率変数の期待値",
    prompt: "Xが0を確率1/2、2を確率1/2でとるとき、E(X)は？",
    options: ["0", "1/2", "1", "2"],
    answer: 2,
    explanation: "期待値は値×確率の合計。0×1/2+2×1/2=1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-B20-01",
    conceptIds: ["B-19"],
    primaryConceptId: "B-19",
    title: "二項分布の確率",
    prompt: "成功確率1/2の試行を3回行い、ちょうど2回成功する確率は？",
    options: ["1/8", "2/8", "3/8", "4/8"],
    answer: 2,
    explanation: "成功する回の選び方が3通りあり、各並びは(1/2)³。よって3/8。",
    kind: "standard",
    estimatedSeconds: 85,
  },
  {
    id: "Q-C10-01",
    conceptIds: ["C-05", "C-10"],
    primaryConceptId: "C-10",
    title: "ベクトルの内積",
    prompt: "(1,2)・(3,-1)の値は？",
    options: ["-1", "0", "1", "5"],
    answer: 2,
    explanation: "成分ごとの積を足して1×3+2×(-1)=1。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-C21-01",
    conceptIds: ["C-21"],
    primaryConceptId: "C-21",
    title: "複素数平面",
    prompt: "複素数z=2+iに対応する点の座標は？",
    options: ["(1,2)", "(2,1)", "(-2,1)", "(2,-1)"],
    answer: 1,
    explanation: "実部がx座標、虚部の係数がy座標なので(2,1)。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-C29-01",
    conceptIds: ["C-29"],
    primaryConceptId: "C-29",
    title: "複素数の軌跡",
    prompt: "|z-1|=2が表す図形は？",
    options: ["中心(1,0)、半径2の円", "中心(0,0)、半径1の円", "直線x=1", "点z=2"],
    answer: 0,
    explanation: "|z-a|=rは、複素数平面で中心a、半径rの円を表す。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I21-01",
    conceptIds: ["I-21"],
    title: "文字係数の不等式",
    prompt: "a<0のとき、ax≥aを満たすxの範囲は？",
    options: ["x≥1", "x>1", "x≤1", "x<1"],
    answer: 2,
    explanation: "aは負なので、aで割ると不等号が反転する。したがってx≤1。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I23-01",
    conceptIds: ["I-23"],
    title: "一次関数の値域",
    prompt: "-1≤x≤2のとき、y=2x+1の値域は？",
    options: ["-1≤y≤5", "-1<y<5", "1≤y≤4", "0≤y≤3"],
    answer: 0,
    explanation: "傾きが正なので端点で最小・最大をとる。x=-1でy=-1、x=2でy=5。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-I32-01",
    conceptIds: ["I-32"],
    title: "二次関数のモデル",
    prompt: "縦x、横10-xの長方形の面積を最大にするxは？（0<x<10）",
    options: ["x=2", "x=4", "x=5", "x=8"],
    answer: 2,
    explanation: "面積はx(10-x)=-(x-5)²+25。頂点x=5で最大になる。",
    kind: "transfer",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I33-01",
    conceptIds: ["I-33"],
    title: "二次関数の係数決定",
    prompt: "y=x²+bx+cのグラフがx軸とx=1,3で交わるとき、(b,c)は？",
    options: ["(-3,2)", "(-4,3)", "(4,3)", "(4,-3)"],
    answer: 1,
    explanation: "y=(x-1)(x-3)=x²-4x+3なので、b=-4,c=3。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I35-01",
    conceptIds: ["I-35"],
    title: "直角三角形の正弦",
    prompt: "直角三角形で、斜辺が5、角θの向かい側の辺が3のとき、sinθは？",
    options: ["2/5", "3/5", "4/5", "5/3"],
    answer: 1,
    explanation: "sinθ=（向かい側の辺）/（斜辺）=3/5。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-I37-01",
    conceptIds: ["I-37"],
    title: "正弦定理",
    prompt: "三角形ABCでA=30°、B=45°、a=2のとき、bは？",
    options: ["√2", "2", "2√2", "4"],
    answer: 2,
    explanation: "正弦定理よりb/sin45°=2/sin30°=4。よってb=2√2。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I38-01",
    conceptIds: ["I-38"],
    title: "余弦定理",
    prompt: "2辺が3,4で、その間の角が60°の三角形の残りの辺の長さは？",
    options: ["√7", "√13", "5", "7"],
    answer: 1,
    explanation: "c²=3²+4²-2·3·4·cos60°=13。よってc=√13。",
    kind: "standard",
    estimatedSeconds: 80,
  },
  {
    id: "Q-I41-01",
    conceptIds: ["I-41"],
    title: "測量モデル",
    prompt: "地面上の点から建物の頂点を見上げる角が45°、建物までの水平距離が10mのとき、高さは？",
    options: ["5m", "10m", "10√2m", "20m"],
    answer: 1,
    explanation: "tan45°=高さ/10=1なので、高さは10m。",
    kind: "transfer",
    estimatedSeconds: 75,
  },
  {
    id: "Q-I45-02",
    conceptIds: ["I-45"],
    title: "四分位範囲",
    prompt: "データ1,2,3,5,8,10,12の四分位範囲は？",
    options: ["5", "6", "8", "10"],
    answer: 2,
    explanation: "中央値5を除くと、下半分の中央値Q1=2、上半分の中央値Q3=10。Q3-Q1=8。",
    kind: "quick",
    estimatedSeconds: 65,
  },
  {
    id: "Q-I48-01",
    conceptIds: ["I-48"],
    title: "分散の計算",
    prompt: "データ2,4,6を母集団とみなすとき、分散は？",
    options: ["2/3", "4/3", "8/3", "4"],
    answer: 2,
    explanation: "平均は4。偏差平方の平均は(4+0+4)/3=8/3。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-I51-01",
    conceptIds: ["I-51"],
    title: "相関の向き",
    prompt: "散布図で、xが大きいほどyが小さくなる傾向が強い。このとき相関係数の符号は？",
    options: ["正", "負", "0のみ", "判断できない"],
    answer: 1,
    explanation: "一方が増えると他方が減る傾向なので、相関係数は負になる。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-A01-01",
    conceptIds: ["A-01", "A-02"],
    primaryConceptId: "A-02",
    title: "場合の数の積の法則",
    prompt: "シャツ3種類とズボン2種類から、1組の服を選ぶ方法は何通り？",
    options: ["5", "6", "8", "9"],
    answer: 1,
    explanation: "シャツの選び方3通りそれぞれにズボン2通りを組み合わせるので、3×2=6通り。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-A09-01",
    conceptIds: ["A-09"],
    title: "余事象で数える",
    prompt: "コインを3回投げて、少なくとも1回表が出る確率は？",
    options: ["1/8", "3/8", "5/8", "7/8"],
    answer: 3,
    explanation: "少なくとも1回表の余事象は3回とも裏。1-(1/2)^3=7/8。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "Q-A12-01",
    conceptIds: ["A-12"],
    title: "確率の加法定理",
    prompt: "正六面体のサイコロを1回振る。偶数または3の倍数が出る確率は？",
    options: ["1/3", "1/2", "2/3", "5/6"],
    answer: 2,
    explanation: "該当する目は2,3,4,6の4個。よって4/6=2/3。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A15-01",
    conceptIds: ["A-15"],
    title: "独立な事象",
    prompt: "コインで表が出て、かつサイコロで6が出る確率は？",
    options: ["1/12", "1/8", "1/6", "1/3"],
    answer: 0,
    explanation: "独立なので確率を掛ける。1/2×1/6=1/12。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A17-01",
    conceptIds: ["A-17"],
    title: "二項型の確率",
    prompt: "成功確率1/3の試行を3回行う。成功がちょうど1回の確率は？",
    options: ["2/9", "4/9", "1/2", "2/3"],
    answer: 1,
    explanation: "成功する回の選び方が3通り。3×(1/3)×(2/3)^2=4/9。",
    kind: "standard",
    estimatedSeconds: 75,
  },
  {
    id: "Q-A18-01",
    conceptIds: ["A-18"],
    title: "期待値",
    prompt: "賞金0円、100円、300円を、それぞれ確率1/2,3/10,1/5で受け取るとき、期待値は？",
    options: ["60円", "90円", "120円", "150円"],
    answer: 1,
    explanation: "0×1/2+100×3/10+300×1/5=30+60=90円。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-A21-01",
    conceptIds: ["A-21"],
    title: "三角形の相似",
    prompt: "3辺が3,4,5の三角形と、3辺が6,8,10の三角形の関係は？",
    options: ["合同", "相似", "どちらでもない", "必ず正三角形"],
    answer: 1,
    explanation: "対応する辺の比がすべて2なので、3辺の比による相似。大きさが違うため合同ではない。",
    kind: "quick",
    estimatedSeconds: 60,
  },
  {
    id: "Q-A22-01",
    conceptIds: ["A-22"],
    title: "平行線と角",
    prompt: "平行な2直線を1本の直線が横切るとき、ある錯角が65°なら、対応する角は？",
    options: ["25°", "65°", "115°", "180°"],
    answer: 1,
    explanation: "平行線では錯角や同位角が等しいので、対応する角も65°。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-A30-01",
    conceptIds: ["A-30"],
    title: "円周角の定理",
    prompt: "ある弧に対する中心角が80°のとき、同じ弧に対する円周角は？",
    options: ["20°", "40°", "80°", "160°"],
    answer: 1,
    explanation: "円周角は同じ弧に対する中心角の半分。80°÷2=40°。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-A31-01",
    conceptIds: ["A-31"],
    title: "円に内接する四角形",
    prompt: "円に内接する四角形のある角が70°のとき、その対角は？",
    options: ["70°", "90°", "110°", "290°"],
    answer: 2,
    explanation: "円に内接する四角形では対角の和が180°。180°-70°=110°。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A33-01",
    conceptIds: ["A-33"],
    title: "点の冪",
    prompt: "点Pから円への接線の長さをtとする。Pからの割線の長さが3と12のとき、tは？",
    options: ["3", "4", "6", "9"],
    answer: 2,
    explanation: "接線と割線の関係よりt²=3×12=36。長さなのでt=6。",
    kind: "standard",
    estimatedSeconds: 70,
  },
  {
    id: "Q-A40-01",
    conceptIds: ["A-40"],
    title: "約数の個数",
    prompt: "60の正の約数の個数は？",
    options: ["6", "8", "10", "12"],
    answer: 3,
    explanation: "60=2²×3×5なので、約数の個数は(2+1)(1+1)(1+1)=12。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-A42-01",
    conceptIds: ["A-42"],
    title: "ユークリッドの互除法",
    prompt: "84と30の最大公約数は？",
    options: ["3", "6", "12", "14"],
    answer: 1,
    explanation: "84=30×2+24、30=24+6より、最大公約数は6。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-II05-01",
    conceptIds: ["II-05"],
    title: "剰余定理",
    prompt: "P(x)=x²+3x+1をx-2で割った余りは？",
    options: ["3", "7", "9", "11"],
    answer: 3,
    explanation: "剰余定理より余りはP(2)=4+6+1=11。",
    kind: "quick",
    estimatedSeconds: 55,
  },
  {
    id: "Q-II06-01",
    conceptIds: ["II-06"],
    title: "因数定理",
    prompt: "多項式P(x)がx-2を因数にもつ条件は？",
    options: ["P(0)=0", "P(1)=0", "P(2)=0", "P(-2)=0"],
    answer: 2,
    explanation: "因数定理より、x-aが因数であることとP(a)=0は同値。ここではP(2)=0。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II17-01",
    conceptIds: ["II-17"],
    title: "直線の方程式",
    prompt: "点(1,2),(3,6)を通る直線の方程式は？",
    options: ["y=x+1", "y=2x", "y=2x+1", "y=3x-1"],
    answer: 1,
    explanation: "傾きは(6-2)/(3-1)=2。点(1,2)を代入するとy=2x。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-II18-01",
    conceptIds: ["II-18"],
    title: "垂直な直線",
    prompt: "直線y=2x+1に垂直な直線の傾きは？",
    options: ["-2", "-1/2", "1/2", "2"],
    answer: 1,
    explanation: "垂直な2直線の傾きの積は-1。2×(-1/2)=-1。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II19-01",
    conceptIds: ["II-19"],
    title: "円の方程式",
    prompt: "中心(2,-1)、半径3の円の方程式は？",
    options: ["(x+2)²+(y-1)²=9", "(x-2)²+(y+1)²=9", "(x-2)²+(y-1)²=3", "x²+y²=9"],
    answer: 1,
    explanation: "中心(a,b)、半径rなら(x-a)²+(y-b)²=r²。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-II22-01",
    conceptIds: ["II-22"],
    title: "不等式と領域",
    prompt: "原点を含む領域を表す不等式はどれ？",
    options: ["x+y≥4", "x+y≤4", "x-y≥4", "x-y≤-4"],
    answer: 1,
    explanation: "境界線x+y=4に原点(0,0)を代入すると0≤4。よってx+y≤4。",
    kind: "transfer",
    estimatedSeconds: 65,
  },
  {
    id: "Q-II33-01",
    conceptIds: ["II-33"],
    title: "指数不等式",
    prompt: "2^x>8を満たすxの範囲は？",
    options: ["x>2", "x>3", "x<3", "x≥3"],
    answer: 1,
    explanation: "8=2³で、底2は1より大きいので指数を比較してx>3。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-II35-01",
    conceptIds: ["II-35"],
    title: "対数の計算法則",
    prompt: "log₂8+log₂4の値は？",
    options: ["3", "4", "5", "6"],
    answer: 2,
    explanation: "log₂8=3、log₂4=2なので、和は5。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II38-01",
    conceptIds: ["II-38"],
    title: "対数方程式",
    prompt: "log₂(x-1)=3を満たすxは？",
    options: ["7", "8", "9", "10"],
    answer: 2,
    explanation: "x-1=2³=8。定義域もx>1を満たすのでx=9。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-II40-01",
    conceptIds: ["II-40"],
    title: "弧度法",
    prompt: "180°を弧度法で表すと？",
    options: ["π/2", "π", "2π", "180π"],
    answer: 1,
    explanation: "半円の弧の長さと半径の比がπなので、180°=π。",
    kind: "quick",
    estimatedSeconds: 40,
  },
  {
    id: "Q-II47-01",
    conceptIds: ["II-47"],
    title: "三角方程式",
    prompt: "0≤x<2πでsinx=1/2を満たすxは？",
    options: ["π/6のみ", "π/6,5π/6", "π/3,2π/3", "5π/6,7π/6"],
    answer: 1,
    explanation: "単位円でy座標が1/2になる第1・第2象限の角はπ/6と5π/6。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-II52-01",
    conceptIds: ["II-52"],
    title: "多項式の微分",
    prompt: "f(x)=x³-2xの導関数f'(x)は？",
    options: ["x²-2", "3x²-2", "3x²-2x", "x³-2"],
    answer: 1,
    explanation: "x³を微分すると3x²、-2xを微分すると-2。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-II54-01",
    conceptIds: ["II-54"],
    title: "導関数と増減",
    prompt: "f'(x)=2x-4のとき、f(x)が減少する範囲は？",
    options: ["x<2", "x>2", "x≤2", "すべてのx"],
    answer: 0,
    explanation: "x<2ではf'(x)<0なので、関数は減少する。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-II60-01",
    conceptIds: ["II-60"],
    title: "曲線下の面積",
    prompt: "y=x²とx軸、x=0,x=1で囲まれる面積は？",
    options: ["1/4", "1/3", "1/2", "1"],
    answer: 1,
    explanation: "面積は∫₀¹x²dx=[x³/3]₀¹=1/3。",
    kind: "transfer",
    estimatedSeconds: 70,
  },
  {
    id: "Q-B02-01",
    conceptIds: ["B-02"],
    title: "数列の一般項",
    prompt: "数列の一般項がaₙ=3n-1で表されるとき、a₅は？",
    options: ["12", "14", "15", "16"],
    answer: 1,
    explanation: "n=5を代入してa₅=3×5-1=14。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-B08-01",
    conceptIds: ["B-08"],
    title: "漸化式の計算",
    prompt: "a₁=0、aₙ₊₁=2aₙ+1で定める数列のa₂は？",
    options: ["0", "1", "2", "3"],
    answer: 1,
    explanation: "a₂=2a₁+1=1。",
    kind: "quick",
    estimatedSeconds: 45,
  },
  {
    id: "Q-B17-01",
    conceptIds: ["B-17"],
    title: "確率変数の分散",
    prompt: "Xが0,2をそれぞれ確率1/2でとるとき、Xの分散は？",
    options: ["1/2", "1", "2", "4"],
    answer: 1,
    explanation: "E(X)=1、E(X²)=2なので、V(X)=E(X²)-E(X)²=2-1=1。",
    kind: "standard",
    estimatedSeconds: 65,
  },
  {
    id: "Q-C07-01",
    conceptIds: ["C-07"],
    title: "内分点",
    prompt: "A(0,0)とB(6,3)を1:2に内分する点Pの座標は？",
    options: ["(1,1/2)", "(2,1)", "(3,3/2)", "(4,2)"],
    answer: 1,
    explanation: "AP:PB=1:2なので、AからBへ1/3進んだ点。P=(2,1)。",
    kind: "standard",
    estimatedSeconds: 60,
  },
  {
    id: "Q-C12-01",
    conceptIds: ["C-12"],
    title: "ベクトルの直交条件",
    prompt: "ベクトル(1,2)と(x,1)が垂直になるxは？",
    options: ["-2", "-1/2", "1/2", "2"],
    answer: 0,
    explanation: "内積が0なので1×x+2×1=0。よってx=-2。",
    kind: "standard",
    estimatedSeconds: 55,
  },
  {
    id: "Q-C14-01",
    conceptIds: ["C-14"],
    title: "ベクトルと面積",
    prompt: "ベクトルu=(1,0), v=(0,2)がつくる平行四辺形の面積は？",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "面積は|det(u,v)|=|1×2-0×0|=2。",
    kind: "quick",
    estimatedSeconds: 50,
  },
  {
    id: "Q-C23-01",
    conceptIds: ["C-23", "C-24"],
    primaryConceptId: "C-23",
    title: "複素数の極形式",
    prompt: "z=1+iの絶対値と偏角の組は？",
    options: ["(1,π/4)", "(√2,π/4)", "(√2,π/2)", "(2,π/4)"],
    answer: 1,
    explanation: "絶対値は√(1²+1²)=√2、偏角は45°=π/4。",
    kind: "standard",
    estimatedSeconds: 65,
  },
];

export const problemBank: Problem[] = [...baseProblemBank, ...expansionIA, ...expansionIIBC, ...gapC, ...gapIIB];
